### ISSUE TITLE
[Paladin][Blood elf] does not work correctly judgement of blood

### ISSUE THREAD

**Issue by MRuzek95** [SunwellWoW/Sunwell-TBC-Bugtracker#1280]
Decription: 
I test some ret paladins  and see   does not work correctly judgement of blood and seal of blood

How it works: 
In spells say  when i jubgement  seal of blood i do  33% damage to self  but in Sunwell i  do 50% of damage done  . And we have same problems with proc of seal of blood  damage not 10%  it is like 25-35%  and Sela ob blood have some bug in proc  seak dont have 100% proc and after 25 attacks    froc only 22  but  must 25

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by sicknot1** [comment]
>And we have same problems with proc of seal of blood damage not 10% it is like 25-35% 

this has to be fixed asap, because it's a very well known bug and people would roll horde and then ret because of it. this was present on HG

**Comment by Atrecom** [comment]
well, well. tested something and got this:
1st screen shows u 11 aa, 1 dodgem but 1 missed proc of seal of blood. this missed proc appears after 15-20 sec after enabling seal.
Next 3 screenshots shows innormal dmg called "10% OF TOTAL DMG DONE:. means melee + seal dmg=100%. btw u can watch better the dmg caused when different crits are done.
p.s. unleashing seal dealsdmg  close to 33% of health every time, but not equal.
![1](https://user-images.githubusercontent.com/44858756/48297735-f6301480-e4c0-11e8-8f8a-d16f25760b84.jpg)
![kmvwizd](https://user-images.githubusercontent.com/44858756/48297736-f6301480-e4c0-11e8-8aa9-84c5a082f3cd.jpg)
![video-games-world-of-warcraft-spirit-pc-angel-1920x1080-15243](https://user-images.githubusercontent.com/44858756/48297737-f6301480-e4c0-11e8-9bee-ad46fd3f2932.jpg)
![img-20180626-wa0002](https://user-images.githubusercontent.com/44858756/48297738-f6301480-e4c0-11e8-87a4-fb87b8bd20d1.jpg)
![img-20180626-wa0002](https://user-images.githubusercontent.com/44858756/48297739-f6301480-e4c0-11e8-8a55-52b17f01fc36.jpg)

**Comment by sicknot1** [comment]
@Atrecom i have understood poorly the bug described and because my own bias i interpreted it as to what my mind wanted it to be.

**Comment by Atrecom** [comment]
> @Atrecom i have understood poorly the bug described and because my own bias i interpreted it as to what my mind wanted it to be.

Okaay, if it`s about my description, so i wanted to tell the maths: when u deal 11 autoattacks, and 1 dodged, u should get 10 points of seal of blood procs, not 9 as u can see on screen n.1. So 1 is lost.

Due to self-dmg from seal. In the descrition: "u take 10% of total dmg", but u take:
2.nd screen: 707+578=1285. Must take 129 dmg, but 134 inflected.
3.nd screen with seal crit: 986+613=1599. Must take 160 dmg, but 116 inflected.
4.th screen with judgement: U TAKE 33% of DMG DONE UNLEASHING SEAL.
But u deal 442 and took 172 back, but should take 148.
![kmvwizd](https://user-images.githubusercontent.com/44858756/48304008-640d2800-e523-11e8-8ee8-c46467d0e249.jpg)
![img-20180626-wa0002](https://user-images.githubusercontent.com/44858756/48304009-68d1dc00-e523-11e8-928f-242b221dde8d.jpg)
![video-games-world-of-warcraft-spirit-pc-angel-1920x1080-15243](https://user-images.githubusercontent.com/44858756/48304011-6e2f2680-e523-11e8-81e6-ef4d55bb114c.jpg)


Here u can see proofs of not 100% proc of seal:
1350 dmg screen, combat log with bugged seal, an u dont see any proc of seal in log, Still taking 210dmg after 1350.
And combat log with normal combat log when seal deals dmg. It must works like this!

The end.
