### ISSUE TITLE
[Druid] Primal Fury talent does not work

### ISSUE THREAD

**Issue by Stondis** [SunwellWoW/Sunwell-TBC-Bugtracker#1281]
Decription: The talent does not always give give an extra combo point

How it works:  Grants you the extra combo point maybe 50% of the time.

How it should work:  You put two points in the talent and you will have 100% chance of getting an extra combo point when you crit with an ability that gives a combo point.
![wowscrnshot_110918_134128](https://user-images.githubusercontent.com/44775624/48260743-448fd580-e425-11e8-953e-bc08a866d07f.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by zapsuu** [comment]
Correctly, it's not always work, I think the problem is block from mob.

![wowscrnshot_111118_111259](https://user-images.githubusercontent.com/43937876/48311649-42538580-e5a3-11e8-873e-077b4a76b278.jpg)

**Comment by Stondis** [comment]
@zapsuu I dont think so. I leveled my druid from scratch on the open world server and I definately spent two points on the talent. Its easy to notice when you are gaining and spending talent points relatively slowly. But having said that I don't know what causes it either.

**Comment by zapsuu** [comment]
Try spend talents once again. Check my screen shots. 0/2 Primal Fury you have 44 points, 1 click and you have 2/2 Primal Fury and 43 talent points to spend. This happend every time.

**Comment by Jekenius** [comment]
Tested Primal fury now, and it's Bear part isnt working aswell. Talent states: "Gives you a 100% chance to gain an additional 5 Rage anytime you get a critical strike while in Bear and Dire Bear Form and your critical strikes from Cat Form abilities that add combo points have a 100% chance to add an additional combo point.". Due to description difference("you get a critical strike" and "your critical strikes" means different things) and some knowledge how that talent works on other servers i can say that bear part(that gives you additional rage when you LAND a critical strike on mob) working wrong, it should give you additional rage when MOB LANDS a critical strike on YOU.

**Comment by notsofamous** [comment]
That makes no sense as bear tanks get crit immune so fast, blizzard wouldn't design a talent that you'd never benefit from. Also gramatically it would be wrong, if they want to put it like that it should be either "You receive a critical strike" or "You get critical striked".

The wording they use when talents trigger on critical strikes against the player:
Blessed Resilience: "Critical strikes made against you...."
Martyrdom: "...after being victim of a melee or ranged critical strike"
Eye of the Storm: "...after being the victim of a melee or ranged critical strike"
Enrage: "...after being the victom of a critical strike"

The wording difference is because the bear benefits from all critical strikes, white and special. The cat only benefit from special attacks that add a combo point. Also they probably don't want to write the exact same thing twice as it looks bad.

**Comment by bigripper** [comment]
I too reported this. Didn't realize this had already been posted 14 days ago. Still not fixed. Any updates?
