### ISSUE TITLE
[Bug] Conjured Items

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#1414]
Can take infinite stacks of Conjured Items like Mana Biscuits or Healthstones while players should have only limited amount of them. Can take infinite charges of entities.

**Comment by notsofamous** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1307

The problem seems to be with the "unique" tag, not those items in specific. Anything that is unique can be stacked in your bags or equipped multiple times. 

Can't seem to replicate it on the closed beta server though? Only on SSC realm.
