### ISSUE TITLE
[Hunter] [Pet] Weird +Spell Bonus on pet stats

### ISSUE THREAD

**Issue by Scarith** [SunwellWoW/Sunwell-TBC-Bugtracker#1560]
Decription: 
There's a random +279 spell bonus on my pets stats I have no clue where from

How it should work: 
This wasn't on retail and isn't on any other servers

Source (you should point out proofs of your report, please give us some source): 
![captura de pantalla 2018-11-16 a la s 11 53 51 p m](https://user-images.githubusercontent.com/45055496/48657744-45170600-e9fb-11e8-954c-5249c39d8ffb.png)

**Comment by notsofamous** [comment]
Starting with Patch 2.0, hunter pets now benefit from "pet scaling". Pet scaling just means that your pet gets to add some of your stats to his own stats, so that his power scales with your power. The basics are very simple: 

Pets get 45% of the hunter's stamina added to their stamina. 
Pets get 35% of the hunter's armor added to their armor. 
Pets get 22% of the hunter's ranged attack power added to their melee attack power. 
Pets get 12.5% of the hunter's ranged attack power added to their spell damage. 
Pets get 40% of the hunter's resistances added to their own resistances. 
Pets inherit the hunter's hit and critical rates.
