### ISSUE TITLE
[Spell];[Aura ];[Hunter];[Rogue] Frozen Trap & Cloak of Shadow

### ISSUE THREAD

**Issue by Jeansapin** [SunwellWoW/Sunwell-TBC-Bugtracker#1580]
Decription: The Frost Trap Aura seems to be a bit buggy with the cloak of shadow spell. 

How it works: Quite well, as you can see here : https://imgur.com/4jYF0mD but once i've used my Cloak of Shadow, the aura can't be reapply to me as you can see here, I'm slacking in the Frost Trap area, but i'm not affected by the aura anymore ... https://imgur.com/agNQLyJ

Something else : When I'm under Cloak of Shadow, and I walk on a Frost Trap ... this happens : https://imgur.com/ZZqDlCW . The trap is triggered, that is normal. But I'm also affected by the aura, even under my cloak, and that's not normal.

How it should work: The aura should be resisted by the Cloak of Shadow, but once my aura is gone, it should affect me again.

Source (you should point out proofs of your report, please give us some source): 
I can't find a duel rogue vs hunter doing this on youtube :<
still researching

**Comment by Wojtyas** [comment]
Somethings still wrong here.
Test:
1. Frost Trap aura -> Cloak of Shadows
For now it looks fine cuz Cloak removes Frost Trap effect.
2. Cloak of Shadows -> Frost Trap
**Before** Cloak of Shadows buff ends we get Frost Aura debuff. Look like Cloak works only for 3 sec instead of 5 sec here.

Also I'm not sure about Entrapment immobilize effect cuz it proc on rogue so easily even with Cloak (shouldn't be +90% resist for that)? @Jeansapin

**Comment by akrom23** [comment]
@Wojtyas Because frost trap is a Aoe aura, that tick every 500ms.
Cloak of Shadow give you 90% chance to resist. So it's possible to resist single ticks of this aura, but after you may be affected by it.

**Comment by Wojtyas** [comment]
Fair enough @akrom23 Then this part works as intented. Not sure about Entrapment one
