### ISSUE TITLE
Shamanistic focus

### ISSUE THREAD

**Issue by Avishai97** [SunwellWoW/Sunwell-TBC-Bugtracker#1670]
Decription: Autoattacks / Flametongue weapon eat the procs

How it works: Autoattacks / Flametongue weapon eat the procs

How it should work: Shocks eat the procs

Source (you should point out proofs of your report, please give us some source):

**Comment by zapsuu** [comment]
Works good, melee/wf/ft/totems don't eat Elemental Focus.

There is a problem with UI the Elemental Focus buff. It has 2 stacks, when we cast 1 spell (non-crit) it's still show us 2 stacks, but after second non-crit spell buff fade. The problem is only UI.

![wowscrnshot_112118_113150](https://user-images.githubusercontent.com/43937876/48836242-763c6100-ed82-11e8-8ee3-873492a30a1d.jpg)

**Comment by Wojtyas** [comment]
Fixed & implemented.

**Comment by Bzmode** [comment]
This isn't fixed

**Comment by FrauHolle86** [comment]
not working on LIVE
