### ISSUE TITLE
[Quest] The Exorcism of Colonel Jules

### ISSUE THREAD

**Issue by Haradokz** [SunwellWoW/Sunwell-TBC-Bugtracker#1705]
Decription: 

Just randomly died during the event 100-0. Nothing in combat log

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![inastantly died](https://user-images.githubusercontent.com/37354103/48750998-134aad00-ec50-11e8-99fb-bc4a0288a859.jpg)

**Comment by Haradokz** [comment]
Might be because I fkd up. Trying again.

**Comment by Haradokz** [comment]
Ok so,never mind the original report. This encounter summons the darkness reveales, The little black balls that fly around the room and do dmg. When you kill these mobs with the quest item or by attacking them they all instantly respawn.

**Comment by Azathothh** [comment]
Number of Darkness Released (22507) looks fine, but they are standing still in 4 spots, instead of flying around, only sometimes they're moving quickly between 2 spots.
Same with Colonel Jules - when he begins "flying around" he does move quickly between 4 points (and it seems random which spot he choose) instead of flying around slowly in circles.
If exorcism was successful and we speak with Colonel Jules to complete quest, he should say in gossip window : "Oh, thank you! The pit of blackness inside of me has been lifted! I can see again... and i see the face of my savior!" now he's saying: "Be gone, <class>! Leave us be, or we will enter you next and show you true despair!"

**Comment by riedling11** [comment]
This still does not work.  After killing the black balls, and using the prayer beads during the ritual several times.  You need to talk with Jules to complete the task.. unfortunately, he cannot be talked to.
