### ISSUE TITLE
[Druid] Travel Form size

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#1726]
Travel Form is currently far too big.

Sunwell:
![Image](https://i.gyazo.com/1be753babffa578ebce225d4a24d0c39.jpg)

How it should be:
![Image](https://i.gyazo.com/01dbb4a65f89b2ac55ae44a003634af2.jpg)

Note: I think it might be the case for all druid forms... but was most noticeable for me in travel form.

**Comment by notsofamous** [comment]
GAMEBREAKING!!!!!!!

**Comment by akrom23** [comment]
Because it's a cat, not a kitty.

**Comment by notsofamous** [comment]
Yes. The size might not be correct there either, but the sunwell travelform is way too big.

**Comment by akrom23** [comment]
Hmm. The size of this model comes directly from client files.

**Comment by pleasse** [comment]
ah yeh was gonna make a report, obviously not game breaking but does not feel smooth!!!!!, last time i played druid was actually in wotlk "retail" and i felt something was off with the size of the travel form for sure, did not feel smooth, 100% remember the model felt like it ran faster because it was smaller = moving feet more often

uff was annoying to find proof but here you go https://youtu.be/9q5P2IaYgrk?t=86 uploaded 2008 so probably "retail tbc" ;)

**Comment by Jeansapin** [comment]
Agreed, on this server the size is bigger than it should be
