### ISSUE TITLE
[Raid] Gruul's Lair

### ISSUE THREAD

**Issue by Adamsek** [SunwellWoW/Sunwell-TBC-Bugtracker#173]
**1. Trashes and overall things:**

- [x] I was able to pull trashes behind gate with HKM still alive, mobs there shouldn't be targetable.
- [x] When one minion from a pack is killed and other is not after raid-wipe the killed one should respawn, for now killed mob is not respawning.
- [x] One patrolling mob behind the gate is Gronn Priest, it should be Lair Brute, becouse of fact that every patrolling mob is Lair Brute.
- [x]  Gronn-Priest and Lair Brute are not immune to poly, stuns, snares etc. Both of them should be immune to everything, except that Gronn-Priest heals should be interruptable (kick, pummel, counterspell etc.)
- [x]  According to first patch of TBC, only one token per boss should drop.

http://wowwiki.wikia.com/wiki/Gruul%27s_Lair

- [x] There is no visual effect of Lair Brute's charge, what's more charge is hitting tank (should be minimum range of 8y) and if it hits any member of raid the damage is too high, according to wiki it should be about 700 dmg and stun only.
- [x] When Lair Brute is near death (10%) he is not calling for help of other ogres (40y range).
- [x] He is using his Mortal Strike really weird, i was hit by it standing about 15y away from him.

http://wowwiki.wikia.com/wiki/Lair_Brute

**2. High King Maulgar**
- [x] Kiggler the Crazed has bugged melee attack and has wrong interaction with tank who run in and out of melee range, he's not atacking with melee when tank is in range and occasionally casting lightning 
bolts.
- [x] Blindeye the Seer has too low melee damage, should hit +100/150% more
- [x] Olm the Summoner should use Dark Decay more often and debuff should stack on a tank (at the moment first debuff is gone when olm casting next).
- [x] Wild Stalkers after enslaving don't have their spell bars to be used by warlocks

http://wowwiki.wikia.com/wiki/High_King_Maulgar

**3. Gruul the Dragonkiller**
- [x]  Gruul's HP is too low (too easy to kill :D) should be about 5.6M HP as pre-nerf boss.
- [x] When Gruul takes aggro from someone behind the gate, encounter resets.

**I need to admit that we check it once, there could be some other minor bugs we didn't notice, but i listed the most impactful. Damage from spells and melee attacks seems fine, but there is a chance that particular mobs should hit more.**

**Comment by babno** [comment]
Adding onto yours, after the first shatter he does not move. He doesn't evade but just sits still and takes whatever ranged damaged you do till dead. If you move into melee he will attack you.

**Comment by notsofamous** [comment]
Adding to yours

### **Trash**

**Lair Brute**

- [ ] Lair Brute casts Mortal Strike on random people instead of the tank.

- [ ] The random Charge does not wipe threat.

- [ ] "These "trash" mobs 1-shot most of the classes and (looks like they) do a random secondary target "charge" so are really hard to tank." Hits for 4000-4500 on leather, not nearly enough to one shot most classes. Increase damage by 3k?

https://www.wowhead.com/npc=19389/lair-brute#comments
http://wowwiki.wikia.com/wiki/Lair_Brute

**Gronn-Priest**

- [ ] Gronn-Priest only heal themselves

- [ ] Should hit for 1500-2000 more

http://wowwiki.wikia.com/wiki/Gronn-Priest

- [ ] All trash respawns even if the boss they are linked to is dead, it shouldn't.

### **Maulgar**

**Maulgar**

- [ ] Maulgar Dual-wielding, should no do this until 50%. Wrong weapon model. (He should reduce his damage by 50% when he swaps to dual-wield to make up for the faster attacks+flurry.)
https://github.com/Looking4Group/L4G_Core/issues/2766

- [ ] Casts Arcing Smash during Whirlwind https://i.gyazo.com/6cbe8ad96afc19a87462b1303d26029e.png

- [ ] Still moves at full speed during whirlwind, should be 50% speed.

- [ ] Does not randomly charge players.

**Kiggler**

- [ ] Kiggler does not lower your threat when he casts Arcane Explosion.

- [ ] Arcane Shock does not interrupt spells for 5 seconds (you even continue casting as you fly away from the knockback).

http://wowwiki.wikia.com/wiki/Kiggler_the_Crazed

**Blindeye the Seer**

- [ ] Blindeye the Seer melees for 480-780 (on leather), should hit for 1400-2400

http://wowwiki.wikia.com/wiki/Blindeye_the_Seer

**Olm the Summoner**

- [ ] Olm the Summoner the Wild Fel Stalker he summons despawns shortly after he summons a new one. They should need to be killed or banished until the fight is completely over, that's when they should despawn.

- [ ] Olm the Summoner's Death Coil shows up as a buff instead of a debuff, you can even right click it. It should also be cast more often. Here: 20 sec CD. Retail: 10-15 sec.

- [ ] Wiki says: "Casts a heavy shadow DoT which cannot be removed and stacks". Dark Decay is not cast nearly often enough to get more than one stack. It drops off and takes a few seconds before he casts it again. Here it seems to be around 20 seconds between the DoT applications, should be 6-9 seconds.

- [ ] Olm should summon the first Wild Fel Stalker way earlier, as they are ment to tank him. 
In this video he casts it after getting shot by an arcane shot: https://www.youtube.com/watch?v=4302sPx4k-U
Instantly in this video: https://www.youtube.com/watch?v=B0teB1CU2QI&feature=youtu.be&t=8
On sunwell: after 15 seconds.

- [ ] Wild Fel Stalker missing ability when you Enslave them; Taunt. +Wild bite?

http://wowwiki.wikia.com/wiki/Olm_the_Summoner
http://wowwiki.wikia.com/wiki/High_King_Maulgar
https://docs.google.com/spreadsheets/d/1y3Jf9kqP_9jzAQcPkgKzvlSecLS3ui3diQ7Ku-z11P4/edit#gid=511402210
https://github.com/Looking4Group/L4G_Core/issues/2212
https://github.com/Looking4Group/L4G_Core/issues/2207

**Comment by notsofamous** [comment]
Very good research: https://github.com/Schaka/TBC-research/issues/20

**Comment by Riztazz** [comment]
re-test please after ptr update

**Comment by notsofamous** [comment]
Gruul buggs
Trash
- [ ] Lair Brute(19389) - Not charging
- [ ] Lair Brute(19389) - Call for help doesn't work/range too small
- [ ] Lair Brute(19389, GUID 81647) - Is linked to GUID 65618 and GUID 83206 when pulled, shouldn't be the case

High King Maulgar
- [ ] Weapon is tiny, should be as twice as big
- [ ] Below 50% he uses charge during whirlwind
- [ ] Nearly always hits with his left hand
- [ ] Charges the main tank? Not sure if this is supposed to happen
Olm the Summoner 
- [ ] Deathcoil no cooldown, around 3 seconds atm
- [ ] Melee damage might be low, 3000-3500 on Leather, Wowwiki says 5000
Kiggler the Crazed
- [ ] Lightning Bolt damage is low, 1500, Wowwiki says 3000

Gruul
- [ ] Aggro range feels way too small. See video 3.35 https://youtu.be/IPinkYtXCv8?t=3m28s
- [ ] Shatter cast delayed, should happened 1 seconds after players get 'Stoned'
- [ ] Shatter damage max 6100 when standing on top of each other, Wowwiki says 8500(with gear on) if very close. See screenshot, 6653 with gear on while standing 8-10 yards away 
![Image](https://i.gyazo.com/abc2c75dd8300e95944f88de202fe80f.png)
- [ ] Gruul stuck after Shatter, should rush to highest threat target from before the ground slam
- [ ] Hateful strike doesn't hit targets at max melee range
- [ ] Doesn't target and turn to the target of the Hateful strike
- [ ] Melee range increases with grows
    - Counts for both his melee range as well as his melee hitbox
    - Does not apply to his hatefull strike range
    - At high stacks(around 15+) the difference between being able to melee and shoot your bow is 1 step
- [ ] Can use Blessing of Protection when silenced
- [ ] Blessing of Protection does not remove the slow but does make you immune to 'Stoned'. (Shouldn't work on either spell)
- [ ] Only one Cave in up at a time, should be multiple pre-nerf, see video at 3.42 there's one in the melee and one behind the priest https://youtu.be/tp-yqVtLeYA?t=3m42s
- [ ] You can LoS Cave in by using the pillars in the back, debuff just keeps getting refreshed but doesn't do damage

**Comment by notsofamous** [comment]
Found this: http://wowwiki.wikia.com/wiki/Gruul_the_Dragonkiller?oldid=642044

Cave In: Random AoE which causes ~3000 damage every 3 seconds in the area. This occurs more frequently in later stages. This counts as melee damage and can be mitigated by armor. Growth also affects Cave In. 

Suggesting that it should happen more often as the fight goes on.

**Comment by notsofamous** [comment]
> Shatter: After being Stoned, Gruul will shatter everyone, the damage dealt increasing if players are closer to each other. If players are 0yds between each other, the damage dealt will be around 5000. The more apart players are, the less damage is taken - no damage will be taken if players are 15yds(changed in recent patch from 20yds) away or more. 

Pre nerf shatter should be 20 yds. Might be a bit too crazy?

**Comment by Silroth** [comment]
@notsofamous Pre-nerf Shatter range and damage should be added here, if i remember correctly the pre-nerf Shatter damage for 0 yards is around 9k, will add more info later on.

**Comment by notsofamous** [comment]
We tried it, it did 8.7k without any armor, 6100 when wearing leather gear and standing right on top of each other. In that screenshot the guy is wearing mail and taking 6.6k while ~8 yds away.

**Comment by notsofamous** [comment]
Added a task to the list.

**Comment by Silroth** [comment]
Shatter should ignore armor and that guy is standing more than 8 yards away.

**Comment by notsofamous** [comment]
I could not find a source of shatter ignoring armor, got a link?

**Comment by Riztazz** [comment]
Shatter ignoring armor makes sense, most of mechanics like that do ignore armor, also based on your screenshots, vids and so on - it makes even more sense for it to ignore armor (damage complaints above:P)

**Comment by notsofamous** [comment]
**Kiggler the Crazed**

- [ ] Weird AI, if you run out of range he will run to the position you were when you got out of range. He should only attempt to chase you to try to get in range of his own lightning bolt.

**Comment by Riztazz** [comment]
re-test after ptr update please

**Comment by notsofamous** [comment]
- [ ] Run speed of Maulgar and his adds are too slow, can be kited super easily.

- [ ] Can't right click Wild Fel Stalker abilities Determination or Threaten on the bars for auto cast. Have to go into spellbook to make them auto cast. Wild Bite works properly.

- [ ] Kiggler's Arcane Shock is missing its DoT component. Not sure how much it should tick for, shouldn't be a lot.

> Arcane Shock, 720–800 damage plus additional damage every 3 secs for 12 secs. Ranged attack he uses infrequently on the person with the highest threat. 
http://wowwiki.wikia.com/wiki/High_King_Maulgar#toc

- [ ] NPCs during the Maulgar fight do not go for the second threat target if the target is feared/death coiled/polymorphed.

- [ ] Gruul aggro range is now a few yards too big, you should juuuust about be able to move around the outer edge of the room without pulling him. (Sorry for nagging about this!!!)

**Comment by notsofamous** [comment]
From WoW bestiary (patch 2.3)

Gruul's Lair

    Lair Brute: N/A
    Gronn Priest: 6304-8907
    High King Maulgar: 12214-17270
    Olm the Summoner: 4104-5792
    Krosh Firehand: 4101-5792
    Kiggler the Crazed: 6834-9653
    Blindeye the Seer: 1724-2435
    Wild Fel Stalker: 1474-2084
    Gruul: 6904-9761

**Comment by notsofamous** [comment]
**Trash**

- [ ] Brutes don't reset threat when they charge

**Maulgar**

- [ ] Olm the summoner doesn't cast death coil

**Gruul**

- [ ] Totem's do shatter damage to players

- [ ] Ground slam doesn't sometimes fully stun you before shatter

**Comment by Wojtyas** [comment]
Clearing this one cuz its overspammed. Creating one final with new report + leftovers from here.
