### ISSUE TITLE
[PvE][Mobs] Mob behaviour after changing target.

### ISSUE THREAD

**Issue by Ibuprofeno** [SunwellWoW/Sunwell-TBC-Bugtracker#1778]
Decription: I have noticed 2 different weird behaviours when mobs change threat.
1) If you want a mob chasing another player, they will sometimes keep chasing their previous target while targetting the taunting player. They will stand still with a charging attack animation.
2) After changing target, they  will stand still until that players gets in range.

Don't really have much more info as it seems to happen randomly (doesn't always happen with taunt, doesn't always happen with threat target-changing
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by badmannerkid** [comment]
Lair Brutes have some targeting issues, they have trouble reaching their target. If someone pulls threat they just stand there targeting that person not moving towards them.
https://streamable.com/60txt

**Comment by badmannerkid** [comment]
also relevant: https://streamable.com/whm4o

Mobs are proximity aggro'd by a different target. The hunter pulls threat as they are on their path to the first target, they finish their path to satisfy the melee range hitbox of their first target. Then, they turn around and target the hunter but do not move towards the hunter. They just sit there targeting the hunter until the first target has died and then eventually reset because they can't register the ability to run into melee range of the hunter/ranged player

**Comment by Wojtyas** [comment]
Fixed & implemented.
