### ISSUE TITLE
[Raid] Magtheridon's Lair Pre-Nerf

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#187]
- Hellfire Warder base damage should be 5335-7537.
Health should be 295150.
Vulnerable to Curse of Tongues and Mind Numbing Poison, immune to everything else.
Shadow Bolt Volley - Deals roughly 2k shadow damage. Range is > than 41 yards. (Base cast time should be 1 second).
Death Coil - A single target damage and fear. They seem to randomly target someone and use it on them.
Rain of Fire - AOE Fire spell that deals 2-3k damage a tick.
Shadow Word Pain - should tick for 1k, dispellable.
Unstable Affliction - should tick for 500, if dispelled it will deal massive damage and silence the dispeller.
Shadow Burst - used on their main target, deals 1600-2400 damage, knock backs and reduces aggro.
Fear - Undispellable 8 seconds fear. 40-yard range.

4 packs in total, 1 patrolling 3 stationary

https://i.imgur.com/wWlHRsy.png
![image](https://user-images.githubusercontent.com/42102450/44482309-3ca36f00-a648-11e8-8614-3722b631e5b2.png)
Pack shown in image above should be channelling green visual, Spell ID 39165 for green channel visual.

Other pack that is facing each other with dummy NPC in middle should be channeling red visual,
Spell ID 33827 for red channel visual.

- Hellfire Channeler base damage should be 4926-6957.
Health should be 364200.
Vulnerable to Curse of Tongues and Mind Numbing Poison, immune to everything else.
Shadowbolt Volley - Deals roughly 2k shadow damage. (Base cast time should be 1 second).
Burning Abyssal - Deals 2628-3329 on random player and summons a Burning Abyssal. Can summon up to 2 Burning Abyssals per Channeler. Fist cast is 30 seconds after engaging and following casts are on a 30 seconds timer.
Dark Mending - Heals self or other Channeler for 69375 to 80625. Has 60 yard range. (Spell ID 30528)
Fear - Undispellable 8 seconds fear. 40-yard range.
Soul Transfer - When one Channeler dies all surviving Channellers gain this stacking buff, increasing size by 20% and damage and casting speed by 30%.

- Burning Abyssal base damage should be 2500-3300.
Health should be 2095800.
Fire Blast - does 3300 damage in a 20-yard range.
Vulnerable to Fear, Banish, Hunter Traps and other forms of CCs. Despawns after 1 minute.

2 minutes after the Hellfire Channelers are aggroed Magtheridon breaks loose and starts attacking.

- Magtheridon base damage should be 14604-20649.
Cleave - 150% damage cleave, used every 6-10 seconds or so ?
Conflagration - A small AoE spell cast on random floor patches that does 6000 fire damage over 8 seconds.
Quake - 50-second cooldown, first cast after 40 seconds. A knockback that hits every player every second for 7 seconds, interrupts spells.
Blast Nova - 60-second cooldown, about 2,500 damage every 2 seconds for 10 seconds to every player in the lair.
At 30% Magtheridon shatters the walls of his lair, causing the roof to crash down. This deals 5250-6750 physical damage plus a 2 sec stun to every raid member.
Collapse - Only active in Phase 3 after Magtheridon shatters the wall of his lair, targets random player on aggro list and after 3 seconds deals 100000 damage to anyone standing in the 8 yard radius area.

Enrage: 22 minutes after the start of the fight, Magtheridon enrages and wipes the raid.

- Manticron Cubes:

When clicked by a player, a channeling effect starts. This deals 800 damage per tick (400 dps) to the player clicking it. If all 5 cubes are active at the same time, Magtheridons Blast Nova is interrupted, and while the five cubes all stay active, he takes 300% damage
When the channel breaks, the player receives the 90 seconds Mind Exhaustion debuff.

https://www.youtube.com/watch?v=A5Ma8G8ZScc

**Comment by notsofamous** [comment]
Copied from: https://github.com/Schaka/TBC-research/issues/6


Mob | Damage | Health | Mana | Abilities | Immunities | Source | Comments
-- | -- | -- | -- | -- | -- | -- | --
Hellfire Warder | 8200-11600 | 295150 | 99270 | Shadow Bolt Volley for 1700-2300, Rain of Fire ticking 2800-3200,  Unstable Affliction ticking for 500, Shadow Word: Pain ticking for 1000,  Death Coil for 1300-1600, Shadow Burst for 1600-2400, Fear | ? | Educated Guess, 1 | Appear to be treated as boss level mobs due to their ability to crush and higher chance to resist spells
Hellfire Channeler | 8000-12000 | 364200 | 1016100 | Shadow Bolt Volley for 1488-2012, Burning Abyssal for 2628-3329, Dark Mending for 70000-81000, Soul Transfer | Immune | Educated Guess, 1 | N/A
Burning Abyssal | 2500-3300 | 2095800 | 0 | Fire Blast for 1750-2250 | Can be feared and banished | Educated Guess, 1 | N/A
Magtheridon | 14604-20649 | 4818380 (verified) 6883400 (CC) | 0 | Cleave for 150% damage, Blast Nova ticking for 2200-2750, Cave-in for 100000, Conflagration ticking 750 | Immune | Educated Guess, 1, 2, Bestiary

**Comment by Riztazz** [comment]
closed by 80e9dd5
