### ISSUE TITLE
"Failed Attempt" on Professions

### ISSUE THREAD

**Issue by Nidok** [SunwellWoW/Sunwell-TBC-Bugtracker#2168]
Description: 
Ive seen it on Skinning and Herbalism so far. Sometimes i try to skin a mob and it just keeps saying "Failed Attempt" after im done and i have to do it again. Happens on maybe every 3 mob or something and sometimes more than once. The same also happens on Gathering nodes for Herbalism.

How it works: 
Description

How it should work: 
Shouldn`t happen.

Source (you should point out proofs of your report, please give us some source):

**Comment by Yavannie** [comment]
Failed attempts do happen when the skill is "orange", but on this server it's happening at the wrong point of the skill attempt. Failed attempts should come after the cast bar of skinning/herbing has completed, but right now you can spam right click through these failed attempts. I've seen this on several private servers, I figured it was just one of those things that for some reason don't work properly on private servers.

**Comment by Nidok** [comment]
You can still skin the mob after the 2nd or 3rd attempt maybe i didnt make that clear enough :D the issue is just that it should work on the 1st attempt and not on the 2nd ord 3rnd which is just a little annoying.

**Comment by Yavannie** [comment]
Yes, I know, but this is the way it was back in the days on retail. Some herbs, like Black Lotus in vanilla, you never got a high enough skill to ensure you could pick it on the first attempt. As long as the skill required is close to the skill you have, there is a chance that your attempt to pick/skin will fail. It doesn't mean you can't pick/skin it, it just means you have to try again. When you gain enough skill that the herb/beast is yellow, green or grey, you don't get failed attempts.

Maybe this explains it better, 3rd paragraph down: https://www.engadget.com/2014/02/14/wow-archivist-what-has-never-changed/?guccounter=1

However, the "check" for whether it should be a failed attempt or not should come at the end of the attempt, not at the beginning, so in reality the failed attempt should be much more annoying than it currently is, because it should come after you've already completed that 3/5 second cast.

**Comment by Nidok** [comment]
Oh god i honestly didnt know / remember that :D Thanks for clearing it up :) Probably should have done some more research before posting here. Well i guess ill close it then :)
