### ISSUE TITLE
Charge movement prediction mechanic

### ISSUE THREAD

**Issue by SuddenDeath** [SunwellWoW/Sunwell-TBC-Bugtracker#229]
The Problem: Currently there is no prediction mechanic for charge spells such as Charge, Intercept, Intervene and Feral Charge.

See video: https://youtu.be/RDPYpeFfiVs

How it should work: Should be using prediction to some extent.

Basically from what I can see, your character should path to a location that is in melee range of where your target was when the stun from charge/intercept was applied(after spell delay), not the location where your enemy was when you first used charge.

This would allow for you to always(unless enemy lag?) reach your target unless he jumps your charge.

Proof:
https://youtu.be/VfSy660jSsI?t=5m39s
https://youtu.be/VfSy660jSsI?t=5m58s
https://youtu.be/VfSy660jSsI?t=6m
https://youtu.be/VfSy660jSsI?t=4m04s
https://youtu.be/VfSy660jSsI?t=4m28s
https://youtu.be/VfSy660jSsI?t=3m28s
https://youtu.be/VfSy660jSsI?t=14m57s
https://youtu.be/3z2nV3pRDS0?t=43s
https://www.youtube.com/watch?v=4JnQaXSHzEE&feature=youtu.be&t=12m19s
https://youtu.be/3z2nV3pRDS0?t=108
https://youtu.be/mGIv1P4QEdc?t=1m58s

Wotlk jump charge: https://youtu.be/tM1caZepbog?t=23m44s

**Comment by Patrulek** [comment]
I don't know if I should make another issue... the problem is that pathfinding for charge is bugged, but i don't know if it's a problem with charge itself or the mmaps. 

Example: Blade's Edge Arena - target standing on the bridge, warrior on the pillar. Charge try reach the target following the straight line. Warrior should charge to the target by rope, but instead is getting stucked on the edge of pillar. Another example is near the alliance graveyard at WSG. I'll provide screens later to make my post clearer.

Another problem with charge may be distance calculation to target, but i don't know how it should really work, so dont wanna start a false issue on GH.

**Comment by lukaasm** [comment]
BEM Arena and its ropes are own issue here.
I will generete navmesh manualy here, somewhat in the future.

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/48948225-17b6e480-ef34-11e8-8082-e85ed752ca69.png)
not working yet
