### ISSUE TITLE
Druid: Double Energy/Rage refund for misses

### ISSUE THREAD

**Issue by Jseay1313** [SunwellWoW/Sunwell-TBC-Bugtracker#2472]
Description:  When you miss ANY ability in cat form (and some in bear form) you are currently being refunded double the amount of energy, as well as ferocious bite automatically refunding 35 energy regardless.

How it works: Miss an ability in cat form, and watch your energy soar from 0 to 70.

How it should work: You should be refunded the normal % and not double.

Source (you should point out proofs of your report, please give us some source): This is a high priority bug, this absolutely changes feral into a legitimate dps class and despite maybe it being something that might be needed to make them more viable it is incorrect.

**Comment by Kittykatreporter** [comment]
What i've noticed, this doesn't apply to finishers (i've tried to reproduce this multiple times by using 1 combo point ferocious bite/rip) and everytime i missed it didnt refund energy at all. Seems like it's doing that with only combo point builders. 

If i remember correctly, refund of combo points builder's was 80% for rogues - i think same applies for cat's, so if my math is correct claw is currently giving 72 energy, instead of 32

**Comment by Jseay1313** [comment]
That's correct, ferocious bite isnt refunding anything on a miss, but it is giving 35 energy everytime you hit with it. Devs should also check if its refunding on a dodge/parry cause it did seem so at one point that it was

**Comment by Aledati** [comment]
It should refund 80% of energy cost of spell on miss, parry, dodge..etc and this also applies for spell RIP which is finishing move in cat form.
