### ISSUE TITLE
Loot disapearing

### ISSUE THREAD

**Issue by Francken123** [SunwellWoW/Sunwell-TBC-Bugtracker#2568]
Loots disapear if you are in a dungeon and green or blue items drop and you win the item but your inventory is full.

**Comment by Francken123** [comment]
Loots disapear if you are in a dungeon and green or blue items drop and you win the item but your inventory is full.

**Comment by Magmalia** [comment]
Yes i have had this happened to me several times during Wailing Caverns today. Won 2 blue items, a pair of pants and a staff and because of tiny bagspace that gets full in a blink of an eye, the items i won, dissapeared. 

First item lost Darkweave Breaches, second item lost Living root. Both were major upgrades for me and im very sad this happened. 

Full inventory - win roll on loot - item(s) is gone.
