### ISSUE TITLE
(Alliance) Quest chain - The Missing Diplomat.

### ISSUE THREAD

**Issue by TBCKillshot** [SunwellWoW/Sunwell-TBC-Bugtracker#2622]
Description: 
The quest is a long chain that requires u to do alot of walking and fighting,after going midway thru quest i found out once u come to the NPC named - Dashel Stonefist ur out of your luck,once u defeat him he won't have question mark over his head that quest is completed.

How it works: 
Once u defeat mob,nothing happens.

How it should work: 
Once Dashel Stonefist is defeating he should let u hand in quest of defeating him.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120618_163453](https://user-images.githubusercontent.com/42093565/49593977-26aa8780-f975-11e8-9416-66de2d47ab57.jpg)

**Comment by TBCKillshot** [comment]
After reloging and redoing quest for 3-4 times it eventually worked,seems to be a problem when my pet gets into a fight ..
Basically once pet do not attacks the NPC quest will work .

**Comment by Doppelmoral** [comment]
Doesn't belong here, but how did you obtain the TBC Fel Ravager pet at level 28?

**Comment by Doppelmoral** [comment]
Doesn't belong here, but how did you obtain this pet ? This is a TBC ravager that should not even tamable at all, especially not for a sub-30 hunter.

https://www.wowhead.com/npc=24922/razorthorn-ravager#comments

By Dayanth (3,491 – 1·5·24) on 2008/05/14 (Patch 2.4.2)		
This ravager is NOT tameable as of right now. As I just tried with my hunter to no sucess. Most probably due to the Sunwell quest lines that involve this beast.
Last edited by Dayanth on 2008/05/15 (Patch 2.4.2)

**Comment by Doppelmoral** [comment]
Doesn't belong here, but how did you obtain this pet ? This is a TBC ravager that should not be tamable at all, especially not for a sub-30 hunter.

https://www.wowhead.com/npc=24922/razorthorn-ravager#comments

By Dayanth (3,491 – 1·5·24) on 2008/05/14 (Patch 2.4.2)
This ravager is NOT tameable as of right now. As I just tried with my hunter to no sucess. Most probably due to the Sunwell quest lines that involve this beast.
Last edited by Dayanth on 2008/05/15 (Patch 2.4.2)

**Comment by TBCKillshot** [comment]
Dear friend Doppelmoral i see you are new to TBC.

This ravager is easy to pick up on even level 10. How you wonder?

Well with out Goat friends  (Drenai) had come special animals on their planet of Exodar which are Ravagers ranging from lvl 10 to 17. I went on my foot to Exodar and obtained one :).

**Comment by Doppelmoral** [comment]
You are right, my bad. Disregard my comment.
