### ISSUE TITLE
[Quest] [A Necessary Distraction

### ISSUE THREAD

**Issue by Trolltilla** [SunwellWoW/Sunwell-TBC-Bugtracker#2671]
Description: 

Sunfury Warlocks / Sunfury Summoners don't drop or have very low drop % for Scroll of Demonic Unbanishing which is required to do the quest

How it works: 

Sunfury Warlocks / Sunfury Summoners don't drop or have very low drop % for Scroll of Demonic Unbanishing which is required to do the quest

How it should work: 

They should have higher drop chance

Source (you should point out proofs of your report, please give us some source):

**Comment by Mikju1** [comment]
Managed to get scroll but when used on Azaloth i'm not getting quest proggression.

**Comment by koshimo** [comment]
I also used scroll on him and didn't get quest completion. 
Edit: It didn't show me having question completion in my quest log, but I was able to turn in the quest after using the scroll on him.

**Comment by LezChap** [comment]
Very low drop rate...farmed for a long time and couldn't get it.

**Comment by Swiplington** [comment]
Killed about 30-40 mobs, no drop

**Comment by Dootz** [comment]
drop chance will be increased with next server update. Thank you for reports

**Comment by LezChap** [comment]
Something's still massively messed up with this quest...I farmed for 90 minutes from the quest I picked up 4 days ago, saw no drop.  Party with someone else on the quest like 20 minutes into that grind session, first Warlock dropped it for them (I looted first and didn't see it in the corpse).

After like 45 minutes I abandoned the quest and re-took the quest.  Partied with 2 other people on the quest, and they both got the scroll drop within a handful of kills (I never saw it even after about 2 more cycles of respawns).  So, one of them uses the scroll on the NPC.  None of our quest logs showed the "NPC Freed" objective complete, but we were all able to turn it in.

So two problems:  
One: feels like I had a ghost/invisible scroll was preventing me from seeing the scroll drops.
Two: Quest objectives don't mark complete on the client quest log even though they are because the server allows turn-in.

edit:  All this grinding took place minutes before making this post, after the fix seems to have gone live.

**Comment by doomnyx** [comment]
not fixed

**Comment by FiveEYZ** [comment]
after using the scroll and get credit for the quest it wont say "completed" in quest log, but i was able to turn the quest in

**Comment by Azathothh** [comment]
10688 - [A Necessary Distraction]  - Scryers version of that quest
10637 - [A Necessary Distraction]  - Aldors version of that quest
Seems like 30811 - [Scroll of Demonic Unbanishing]  can drop only when we're at 10637 - it's not dropping when we're at 10688
+ in both quests when we use [Scroll of Demonic Unbanishing] we're getting this quest completed, and we can return it to quest giver but in quest log it still appears as "Azaloth freed: 0/1"
