### ISSUE TITLE
Hunter pets don't get increased xp

### ISSUE THREAD

**Issue by Nelthalor** [SunwellWoW/Sunwell-TBC-Bugtracker#2805]
Description: 
Hunter pets don't gain increased xp rates.

How it works: 
They gain normal xp from kills.

How it should work: 
Should be increased with low lvl or 3x from store.

Source (you should point out proofs of your report, please give us some source):

**Comment by cokolele** [comment]
Please fix this one, very annoying. I am outleveling my pet really fast

**Comment by ujellyx** [comment]
#2376

Bug was reported days ago and even GMs acknowledged it via ticket and said that this problem is known... still no fix or reaction.

**Comment by cokolele** [comment]
Funny, some random quests get High Priority but hunters pets don't. Leveling a hunter with outleveled pet is like leveling a warlock without shadow bolt.

**Comment by Nelthalor** [comment]
It isn't that they are ignoring it, there are probably a lot of problems with fixing it. I'm not sure if it is, but I think Hunter pets are hidden away and in a different place than character experience gains. It is very easy to modify character experience, so I assume pets are as well. But I'm not sure where you change it so I can't suggest where to go to.

**Comment by cokolele** [comment]
I can be wrong, but i think it should not be hard. I am not sure what core they use but in trinity there is one constant in pet.cpp that is related to xp rate. I think it is related to max hp as well so they might have to change some code and recompile

**Comment by xyrol** [comment]
can you finally fix that annoying shit? why did i bought a x3 buff if i need to level up my pet for days now?

**Comment by xyrol** [comment]
fix it finally...

**Comment by peanutcheese** [comment]
bump

**Comment by siof** [comment]
For me it seems to work as should but if you have any informations that on TBC pet XP calculations had different formulat please post links with proofs. Below are informations how it is working currently.

All values are examples AFTER modifications by rates/party/etc not real data
Pet is getting XP ONLY from killing and not from explore/quests.

Consider that player should get 100 experience (after modifications by rates).

There are 2 possible situations for calculate pet xp from this value and one huge modifier to it which will be described later.

First situation: Hunter is not in party (solo with pet)
If hunter is not in party then pet is getting 100% of experience which was calculated for player.
In our example situation if player will get 100 XP then pet will get 100 XP (if player is not in party).

Second situation: Hunter is in party
If hunter is in party then pet is getting 50% of experience which was calculated for player.
In our example situation if player will get 100 XP then pet will get 50 XP (if player is in party).


Those are two main possible situations which modifies XP get by pet, but as i said in the beginning there is also one huge modification to them.

Pet's experience gain is not modified by player rest bonus. 

If player has rest bonus then player will get other values than written above.

Lets consider first situation again with rest bonus:
If XP calculated for player was 100 then with rest bonus he will get 200. But as i said before Pet's experience gain is not modified by rest bonus so pet will get only 100 XP.

Lets consider second situation again with rest bonus:
If XP calculated for player was 100 then with rest bonus he will get 200 but pet only 50 XP (because base 100XP/2 = 50).

Here is video which shows values got by pet without rest bonus on x2 server rates with and without .blizzlike command active:
[https://drive.google.com/file/d/1P2prevP_6Wk7H1-6Pue_XSgEmn56EXbO/view](https://drive.google.com/file/d/1P2prevP_6Wk7H1-6Pue_XSgEmn56EXbO/view)


If you will have proofs that those calculations are incorrent from TBC point of view please share links with us.

**Comment by ujellyx** [comment]
Wanted to chime in again as I did some testing with the formulas I could find on the internet (mainly archived thottbot and wowwiki). The XP-rate for solo-killing mobs seems to fit the formula, the pet even gets the 3x xp rate. Where the XP drastically drops is when mobs are killed in a party. With only three people in the party, my pet would get approx. 1/5th of the experience it would get when killing mobs alone. The experience for me as a player was fine while killing mobs in a 3-party, but my pet's experience strongly lacked behind. Maybe that information is a start to investigate how pet-experience behaves in a group. As I'm already level 70 as of now, it's hard to compare player-experience with the actual pet-experience again - but the experience gain for player and pet should always be roughly the same.

**Comment by siof** [comment]
@ujellyx As i said in my previous post - pet in party is always getting 50% od XP which will get player without rest - basicly in code its something like that (it's not actual code):
```
xp = CalculateXpForPlayerInGroup();
player->GiveXP(xp);
player->pet->GiveXP(xp/2);
```

while without group its:
```
xp = CalculateXpForPlayer();
player->GiveXP(xp);
player->pet->GiveXP(xp);
```

I just need to know two things (best with TBC proofs):
1. Pet in party should get 50% or other % of player XP gain (currently 50%)
2. Pet xp gain should be modified by player rested bonus or not (currently not)

EDIT:
From 5 different TBC repositories which i checked only mangos-tbc has 100% xp gain for pet while in group. Rest (including ccshiro/corecraft repo) has 50% for pet.

**Comment by ujellyx** [comment]
@siof That would explain it. But it seems that the 50% penalty doesn't allow for the 3x increase from the boost. It seems like it's 50% of the original 1x experience, not being multiplicative with the 3x boost (so it'd be effectively at 150% xp). Can you check/confirm that? As the pet experience gain is based off the player's experience, it should also apply for the increase by the boost.

**Comment by siof** [comment]
50% is after modifications by rate so:
If base exp for player in party is 50 and with x3 player should get 150 without rest (300 with rest) then pet will get 75 exp (because of 150 / 2).

**Comment by Hahahahahahahahahahahahahahahahahahah** [comment]
Any update on if this is going to be fixed? It's insane how bad it is to try and level a pet.

**Comment by siof** [comment]
I'm closing issue because there are no proofs that current behaviour is invalid. I think that waiting more than 3 weeks is enough.

If someone will have any proofs in future please open new issue and post them with link to this issue.
