### ISSUE TITLE
[Hunter] Traps are visible to enemies

### ISSUE THREAD

**Issue by Aeded** [SunwellWoW/Sunwell-TBC-Bugtracker#2831]
How it works: 
1. Traps are visible to enemies
![wowscrnshot_120818_112909](https://user-images.githubusercontent.com/45561230/49686527-12da5f00-faf6-11e8-994a-5f97eb048776.jpg)

How it should work: 
1. Trap should not be visible to hostile units when they are armed. 

Source (you should point out proofs of your report, please give us some source): 
Common knownledge

**Comment by Zarant** [comment]
Source;
https://youtu.be/hS82JzE6F0I?t=410 
If you watch the duel closely, the druid is not able to see traps at all, however, at the 8 minutes, 30 seconds mark, the hunter laid down a trap right next to the druid and the druid is able to see it. 

Traps do have some kind of stealth mechanic, because the druid was only able to see the trap at a very close range. Traps are either completely invisible after the 2 second arming time or it's just that the trap activation radius is larger than the stealth detection radius.

**Comment by akrom23** [comment]
Trap detect distance is ~7y + player's size.
