### ISSUE TITLE
Parry/dodge special attack rogue glitch

### ISSUE THREAD

**Issue by Kalisss** [SunwellWoW/Sunwell-TBC-Bugtracker#2848]
How it works: 
When I do a special attack (tested on SS and Hemmo) and opponent dodges/parries, I'll get an instant 20 energy.

**Comment by ujellyx** [comment]
Same for feral druids. Missing attacks somehow grant extra energy that it should not.

**Comment by zapsuu** [comment]
Dodge should always bring some energy, but never add it.
Parry shoud always bring some energy, but never add it.

Finishers dodge/parry should bring some energy and combo points should stay on the target. Atm dodge/parry bring all energy and stay all CP.

Miss should always bring all energy and all combo points (miss bring back energy to druid and we dont lose any CP on target)

**Comment by BanditOMG** [comment]
It seems to be a different value of energy given back based on the move used, but I can confirm through tooooons of time now that it is more than 20. If I have 70 energy, use mutilate and it's dodged/parried I then have 110 energy and just do two mutilates/muti and a finisher. It's actually ridiculous and has literally won fights in pvp for me that I should not have won at all (as well as a ton of encounters in general) It's basically become a begrudged part of my rotation because it feels so phr33 and unfair.

**Comment by akrom23** [comment]
There are spells that refund energy on dodge/parry/deflect. Multilate, Hemo and SS are among them.
