### ISSUE TITLE
Heartstone&unstuck

### ISSUE THREAD

**Issue by tr0n3** [SunwellWoW/Sunwell-TBC-Bugtracker#2858]
Description: buged unstuck  teleportation

How it works: teleport to different places 

How it should work: should port to same destination every time

Source (you should point out proofs of your report, please give us some source): yesterday when i used unstuck it ported me wwhere my hs is , today it ported me in ewlyyn  forest

**Comment by siof** [comment]
Iirc unstuck teleports you to home if you don't have CD on hearthstone and to race start location otherwise. It's to prevent abuse on unstuck option.

EDIT:
How unstuck option is working:
- if player is on taxi/arena/bg - do nothing
- if player is dead - teleport to nearest graveyaard
- if player don't have cooldown on hearthstone and hearthstone is in his backpack - use hearthstone for teleportation
- otherwise - teleport to race starting location
