### ISSUE TITLE
Quest in ramparts 

### ISSUE THREAD

**Issue by treety17** [SunwellWoW/Sunwell-TBC-Bugtracker#2914]
Description: From the last boss in Hellfire Ramparts, there should drop a letter from the chest. 

How it works: 
right now, the chest seems to disappear or the letter just doesnt drop

How it should work: 
The letter should drop and its a quest that continues into Blood  Furnace. 

Source (you should point out proofs of your report, please give us some source): 
We've ran hellfire ramparts and none got it. I think the GM said he had over 50 tickets about this.

**Comment by Jseay1313** [comment]
The boss himself drops the letter, I looted it earlier - the letter has never dropped from the chest. The issue here is that the corpses despawn in 25-30 seconds, so for instance on a fight like this if you dont loot the orc right as he dies and then kill the dragon, it will despawn by the time the fight has ended.
