### ISSUE TITLE
Hunter Trap Radius

### ISSUE THREAD

**Issue by sadfx** [SunwellWoW/Sunwell-TBC-Bugtracker#3002]
Description: The distance at which a trap freezes you isn't Blizzlike

How it works: You avoid the trap (not even remotely close) but get trapped anyway

How it should work: Freezes you if you're practically on top of it

Source (you should point out proofs of your report, please give us some source): brain

**Comment by baade123** [comment]
thats funny, i was going to make the report saying the opposite....

**Comment by baade123** [comment]
ive sat ontop of traps while warriors attack me, this should not be possible.

**Comment by sadfx** [comment]
> thats funny, i was going to make the report saying the opposite....

I've walked around them multiple times making sure I wasn't even close then I was frozen out of nowhere

**Comment by Zarant** [comment]
The video is accurate, frost traps triggers before the ice slick animation shows up on your screen, if you advance it frame by frame you can see the shaman getting quite close. 


> trap radius is like 2yards, melee range is like 5y
> didnt test it thais patch but always before it was like that:
> hunter staying on top of trap -> melee class at max melee range hiting hunter and not getting traped
> moreover hunter takes step back -> melee still hiting him through trap

Source: http://www.arenajunkies.com/topic/93057-freezing-trap-trigger-range/ - Here a player described how traps used to work prior to Patch 3.2

So, trap activation range should be shorter or equal than 5 yards, since melee leeway mechanics might come into play. Another interesting bit came from a hotfix during the WoD expansion, saying that prior to that, traps had 5yd trigger radius.

> Hotfix (2015-01-08): "Freezing Trap now has a trigger radius of 3 yards (down from 5 yards)." 

Source: https://wow.gamepedia.com/Freezing_Trap


And regarding the trap arming time:
> Traps can be set while in combat, but require a 2 second arming time.

Source: http://wowwiki.wikia.com/wiki/Patch_2.0.1

**Comment by akrom23** [comment]
Default radius is 5y.
