### ISSUE TITLE
[Warlock] using pet abilities causes pet to attack target

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#305]
Decription: Any pet ability will cause the pet to run and attack the target

How it works: Regardless of stance and current (if any) target using something like spell lock or seduction will cause the pet to attack the spells target

How it should work: If the pet is passive and not currently attacking it should run into range and los to cast the spell then return to the warlocks side. If the pet is attacking another target they should run into range and los to cast the spell then return to their previous target.

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
@babno Cannot reproduce. Some video?

**Comment by akrom23** [comment]
No response.

**Comment by babno** [comment]
Sorry, must of missed an email. I can't do video. It happens in arena consistently where if the pet is attacking player A, if I tell it to spell lock player B it will then go attack B. Here's a combat log of some random mobs too 
![image](https://user-images.githubusercontent.com/244626/53349785-db58a300-38eb-11e9-844a-854a23967cfe.png)

**Comment by akrom23** [comment]
Casting an offensive spell is treated as an 'attack' command - that's why it works like this.

**Comment by babno** [comment]
Yes, it shouldn't be.

**Comment by akrom23** [comment]
@babno Tell me something:
```
if the pet is attacking player A, if I tell it to spell lock player B it will then go attack B
```
If pet is not in combat and you cast spell (left click on pet bar) on random target - pet should start attack that target?

**Comment by babno** [comment]
"If pet is not in combat and you cast spell (left click on pet bar) on random target - pet should start attack that target?"

No. The pet should remain on the same target always until either the target is dead or the attack command is used on another, and that applies if there is no target. If you use a spell while its passive and not attacking, the pet should run towards the target until they are in range and LOS, use the ability, and then return to the warlocks side.

**Comment by Lorious** [comment]
https://clips.twitch.tv/InterestingInterestingOrcaHassaanChop

So this fucks things up for hunters that use Passive (all of us I hope).
If I issue an attack command like /petattack and then use a petspell while it's on it's way to his/her/its target they just perform that action and move back to the user. This randomly appears to happen in combat as well, guessing this might be related to swapping targets mid fight but not sure.

Since hunters use pet skills in PVE macros to force our pets to use their spells without delay this is critical.

**Comment by Lorious** [comment]
To further explain, Macros I've been using since the start of the server.

To send in my pet:
/petattack
/cast Dash
/cast Hunter's Mark

Steady shot rotation (3:2):
/tar Spitfire Totem
/script UIErrorsFrame:Hide()
/cast !Auto Shot
/cast [exists,target=pettarget] Kill Command
/cast Steady shot
/script UIErrorsFrame:Clear() UIErrorsFrame:Show()
/cast [exists,target=pettarget]Bite
/cast [exists,target=pettarget]Gore

So here lies the issue, Hunters want to force our pets to use their spells without delay (can happen while set on autocast). If a pet is issued an attack command like in Macro 1 they shouldn't run back to their user if they later are issues an pet skill command. The attack command should still apply.

**Comment by Lorious** [comment]
Both hunters in our guild with problems first had them after entering a dungeon after this "fix" was applied. Everything worked up untill we zoned in to dungeons. FYI not sure if that was just coincident but this means that My problems started a full day after our otherr hunter started having his. Symptoms are the same though.
