### ISSUE TITLE
[Talent][Priest][Shadow] Blackout

### ISSUE THREAD

**Issue by tacotal** [SunwellWoW/Sunwell-TBC-Bugtracker#3083]
Description: 
I have tested the talent for a while, and there seems to be at least 2 bugs with the spell:
1. It only procs when a spell LANDS, not when it does damage. For example, it does not proc off shadow word: pain dot damage or mind flay damage after the initial tick.
2. From the previous point, since it only procs when it lands, that means spells like shadow word: pain applies the stun even though it has done no damage yet (since sw:p doesn't do initial damage). The tooltip says "gives your shadow damage a x% chance to stun the target.

How it works: 
Casting shadow spells apply blackout upon being cast, and not when they do damage.

How it should work: 
Every time a shadow spell deals damage, there should be x% chance that the target will be stunned (depending on the rank of the talent).

Source (you should point out proofs of your report, please give us some source):

**Comment by Aloise3** [comment]
As far as I know the blackout only procs on the spell application.

https://vanilla-twinhead.twinstar.cz/?issue=5157 - A dev from another server confirming (altough it is a different expansion, but I cannot find changes to Blackout in WoWhead database until Cataclysm) and a wowwiki link which was the only source I could find with a random google search.

If you have a source that proves otherwise, link it. That is what the last part of the template is for (yet nobody uses it).

PS: You excluded a word from the tooltip. “...shadow damage -spells-”. Even though you can not always trust tooltips in WoW, it implies that blackout is procced on application and not on damage.

An example of the horrible tooltips from Blizz: According to WoWwiki only damaging shadow-school spells should be able to proc Blackout.

**Comment by tacotal** [comment]
> As far as I know the blackout only procs on the spell application.
> 
> https://vanilla-twinhead.twinstar.cz/?issue=5157 - A dev from another server confirming (altough it is a different expansion, but I cannot find changes to Blackout in WoWhead database until Cataclysm) and a wowwiki link which was the only source I could find with a random google search.
> 
> If you have a source that proves otherwise, link it. That is what the last part of the template is for (yet nobody uses it).
> 
> PS: You excluded a word from the tooltip. “...shadow damage -spells-”. Even though you can not always trust tooltips in WoW, it implies that blackout is procced on application and not on damage.
> 
> An example of the horrible tooltips from Blizz: According to WoWwiki only damaging shadow-school spells should be able to proc Blackout.

I guess you're right. Blackout worked as I described on other servers so I took it for granted, but upon researching it, it would appear it is probably working correctly. Thanks for the clarification!

**Comment by Aloise3** [comment]
No problem ^^

Yes, playing too long on private servers make you forget the real deal. Just look at several of the “Classic” youtubers. A quick google search can usually get you comments that intially falsify your theory. If it looks like a bug you can check old theorycrafting forums through webarchive. 

I’m only putting the above section hoping that people will check the message and start using sources, as I honestly hate undocumented claims.

Another source would be good if anyone has it btw, as I’m still not certain on how Blackout worked.
