### ISSUE TITLE
[Quests][Professions] Changing Alchemy Specializations

### ISSUE THREAD

**Issue by badmannerkid** [SunwellWoW/Sunwell-TBC-Bugtracker#3201]
Description: 
When you go to respec your alchemy specialization from one Mastery Specialization to another, you must pay the 150g. After you pay the 150g, you then have to do a new Mastery Specialization pre req questline. This is incorrect. You should just have to pay the 150g respec fee and be able to choose the new Mastery Specialization for free, without having to do any pre req questline

How it works: 
When you go to respec your alchemy specialization one Alchemy Specialization to another, you must pay the 150g. After you pay the 150g, you then have to do a new Mastery questline. You should just have to pay the 150g respec fee and be able to choose the new Mastery Specialization, you shouldn't have to also do the pre req to the new Mastery Specialization questline as well.

How it should work: 
You should just have to pay the 150g respec fee and be able to choose the Mastery Specialization, you shouldn't have to also do the Mastery Specialization questline as well. This was implemented on launch, this is NOT a 2.4.3 feature: https://www.wowhead.com/quest=10899/master-of-transmutation#comments:id=28770

Source (you should point out proofs of your report, please give us some source): 
https://www.mmo-champion.com/threads/646398-Alchemy-Change-specialization
https://www.wowhead.com/forums&topic=33627
https://github.com/Looking4Group/L4G_Core/issues/404

**Comment by chme3921** [comment]
Still bugged, now I've been scammed out of 250g and 4 Primal Mights.

**Comment by Trolltilla** [comment]
Got scammed for 150g aswell

**Comment by letsfixthis** [comment]
can u fix this already please? thanks

**Comment by Theokrat** [comment]
please fix this already, got into the trap today as well
i wrote a ticket and hgm said go bugtracker, i dont wanna look up everything in here before i do something in game
also for record, character name: Bud (Warrior), so that i dont get scammed when it get fixed and i have to do the quests again

**Comment by RemiBaldy** [comment]
fix plz

**Comment by Theokrat** [comment]
fix plzz

**Comment by Epidemus** [comment]
fixerino fasterino please :(

**Comment by jketch** [comment]
During the fix for this issue please consider what I believe is the central desired outcome:

Players who completed a Specialization quest chain, gained a Specialization, and then dropped the Specialization via 150g option will be given an option to pay a fee to relearn any specialization from a Alchemy prof. trainer. 

Thanks!

**Comment by Theokrat** [comment]
wait i need to pay 150g again or what O.o ?

**Comment by Trolltilla** [comment]
This has been on high priority for ages now and still not fixed :(

**Comment by mhdemn** [comment]
Same. I made two tickets, and they refuse to give me my money back or my desired or old spec too. Just telling me to report it when it's been reported for 3 weeks haHAA

PS get rid of this stupid ass policy of not helping anybody, and besides it doesn't apply here, since it's not the player's mistake. It's your bad. You didn't script it correctly. People got fucked because you people don't do things right. So give people their money back, or complete their quests, or preferably fix your shit. Thanks

**Comment by MiekZer** [comment]
still not fixed  22 days later.

**Comment by Lethalbacon2** [comment]
Still bugged. come on sunwell lots of people losing gold over this! fix it already

**Comment by Dootz** [comment]
Will be fixed with next server update.

Step 1: Unlearn mastery from your trainer.
Step 2: Go to different trainer
Step 3: He will offer you option to learn spec.

**Important** note: Do **Not** Unlearn before update. **If you unlearn before update you'll have to complete quest** in order to get new alchemy spec. I'll post an update here + I'll ask dreed to post something on discord once it is live.

**Comment by Trolltilla** [comment]
So if you already unlearned it before fix for 150g you have to do another mastery q and then unlearn it for another 150g?

**Comment by Dootz** [comment]
Each unlearn costs 150g. Right now, once unlearned you can pick up any other mastery quest. After the fix when you unlearn mastery trainers will offer you instant option to learn new mastery. Unforunately if you already unlearned profession you'll need to complete quest to get alchemy mastery. Hope this answers your question.

**Comment by mhdemn** [comment]
> Will be fixed with next server update.
> 
> Step 1: Unlearn mastery from your trainer.
> Step 2: Go to different trainer
> Step 3: He will offer you option to learn spec.
> 
> **Important** note: Do **Not** Unlearn before update. **If you unlearn before update you'll have to complete quest** in order to get new alchemy spec. I'll post an update here + I'll ask dreed to post something on discord once it is live.

People that got their money stolen by this unprevisible bug will get their 150 golds refunded?

**Comment by Lethalbacon2** [comment]
what is with people who already tried to do this before the update and lost the 150g? its just gone?

**Comment by letsfixthis** [comment]
Is it online now? @Dootz

**Comment by Theokrat** [comment]
nice scam man

**Comment by Dootz** [comment]
@letsfixthis yup, online.
