### ISSUE TITLE
Tar beast in un goro spamming disarm

### ISSUE THREAD

**Issue by Mallekito** [SunwellWoW/Sunwell-TBC-Bugtracker#3228]
Description: 

The tar creatures in Un Goro, are spamming disarm. They chain disarm you, and its really awful for melee to deal with them
How it works: 
They chain disarm you

How it should work: 
It should disarm you, and have an internal CD like any skill.

Source (you should point out proofs of your report, please give us some source):

**Comment by Robin-Combeau** [comment]
I got the same issue with the tar creatures. It's pretty much not doable if your class depends a lot on your weapon damage like warrior or rogues since the proc chance is around 90-100% chance.

I didn't find any cooldown information but a 10% aura proc chance on classic database : _classic.wowhead.com/spell=14178/sticky-tar_

And the proc chance seems to be confirmed by a comment from the 2.0 version of the game : "[...] And their 'Sticky Tar' armor will randomly disarm you."

You can find the comment here : 
_fr.wowhead.com/item=11834/goudron-ultra-collant#english-comments_

Summary : The ablility Sticky Tar from the Tar creatures in Un Goro is an aura that has a chance to disarm you when you hit them. **Right now the proc chance is too high (90-100%). It should be lowered to 10%.**
