### ISSUE TITLE
Arcanite Bar Transmute Incorrectly Has Cooldown

### ISSUE THREAD

**Issue by Delfury** [SunwellWoW/Sunwell-TBC-Bugtracker#3278]
Decription: Arcane Bar Cooldown period was removed in 2.4.0.

How it works: Currently, it has a 24 hour cooldown when using transmute arcanite bar.

How it should work: Since we are playing on 2.4.3, the cooldown for transmute arcanite was removed in 2.4. Therefore, it should have no cooldown whatsoever.
**-The argument has been made that since this is a change from patch 2.4.0 it should be implemented later with the Sunwell content.  However, mount required levels and costs are from 2.4.3, as well as the talent trees.  Alchemy should match the 2.4.3 content as well**.

Source:
http://wowwiki.wikia.com/wiki/Transmute:_Arcanite
http://wowwiki.wikia.com/wiki/Patch_2.4.0

**Comment by ZaoQ** [comment]
Well add Engineering head to the game as well and metagem and all other things ...

**Comment by Wojtyas** [comment]
We didn't change several things only cuz we wanted to make ur playing more comfortable, otherwise we would remove guild banks till 2.3 and increase prices of a lot of stuff but that's not the point. We can't change talent trees cuz its client version. Professions has been simply modified where we could do change.
