### ISSUE TITLE
seer udalo

### ISSUE THREAD

**Issue by thearmo** [SunwellWoW/Sunwell-TBC-Bugtracker#3318]
Description: Seer Udalo is not there in Arcatraz and I can't turn the quest in

How it works: He isnt in arcatraz

How it should work: he should be in arcatraz dead in the room before the last boss

Source (you should point out proofs of your report, please give us some source):

**Comment by notsofamous** [comment]
It has to be completed on heroic
https://www.wowhead.com/quest=10705/seer-udalo

**Comment by thearmo** [comment]
I read the comments and people during TBC said it does not have to be done in Heroic mode and can be completed in normal. Not sure if I am correct.

**Comment by KimmoKM** [comment]
Well, luckily you don't need to read Wowhead comments because it shows right there in the quest log:
![2018-12-14_195952_387594304](https://user-images.githubusercontent.com/1533992/50019320-eaad9d00-ffda-11e8-8a65-0f3e6b9f8eba.png)

"Dungeon". If it was heroic-only, it would read "Heroic" (like the Trial of Naaru above it, the Arca part of which can currently be completed in normal by the way).

**Comment by mjk6994** [comment]
https://www.wowhead.com/quest=10705/seer-udalo

The dude in the other thread Woj or w.e saying its heroic omg is retarded. This is a NORMAL QUEST. Level REQ IS 67. Put him back in normal. This is dumb.

**Comment by Aledati** [comment]
I am 100000000% sure seer udalo is in Arcatraz Normal mode.
Any discusion about this one is pretty stupid.
Put him back in Normal mode
