### ISSUE TITLE
shy rotham

### ISSUE THREAD

**Issue by Kuakertupu** [SunwellWoW/Sunwell-TBC-Bugtracker#3341]
Description: Can't turn in the quest

How it works: Killed both cats, quest says done but can't turn in

How it should work: Should be able to turn in the quest

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_121318_185813](https://user-images.githubusercontent.com/45856903/49957763-1b250680-ff09-11e8-9911-7b727b0a3e5f.jpg)

**Comment by ZaoQ** [comment]
already reported ...

**Comment by xethra89** [comment]
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2460

For reference. In order to make it work @Kuakertupu the person who puts down the meat is able to turn the quest in. The others have to put down the meat as well in order to be able to turn in. Definitely a bug, but that is the work around.

**Comment by Azathothh** [comment]
Exactly like xethra89 said - there's a "hidden" requirement right now - players need to summon him as well, not only kill. It is a bug, and duplicate as well
