### ISSUE TITLE
Herbs spawn timer

### ISSUE THREAD

**Issue by Yasur7** [SunwellWoW/Sunwell-TBC-Bugtracker#3382]
Description:  Herbspawn around Netherstorm and Shadommon Valley should be much higher

How it works:  Spawn of Netherbloom and Nightmare Vine is much too low

How it should work: These herbs should spawn much faster

Source (you should point out proofs of your report, please give us some source):  I was flying around Netherstorm for like 2 hrs and collected maybe 8 Netherblooms

**Comment by Euphemistic** [comment]
Any info on this? It's still unchanged, Netherbloom and Nightmare Vine are going for close to 150g a stack which is insane, considering the respawns of those herbs in retail TBC was around 10 mins. They seem to be 45 mins to an hour on Sunwell, possibly even longer. I flew around Netherstorm for an hour and found 1 Netherbloom. Kind of a pain in the ass especially when farming your own mats for consumables, which makes herbalism kind of a shitty profession because I don't know anybody that's actually buying herbs off the AH because of their ridiculous price.

**Comment by Moonchuck** [comment]
It's still the same. Im usually gathering herbs for like 2 hours per day while im at work. I'm trying Netherstorm from a week now. There're around 1 to 7-8 herb node per two hours. It's insanely low than the retail. On very high and high populated realms on Retail I was collecting about 4-5 stacks per 2 hours in terms of netherbloom and nightmare vine. Since the online numbers are doubled aswell it should be around 1-2 stacks per two hours even with the x1 rate as retail. It should be even much more spawn rate to stabilize respawns for number of players since there is no dynamic respawn system for herbalism. Mining nodes seems to be fine as they're spawning faster due to the number of players. Same should be applied to herb aswell.

**Comment by Nghedi** [comment]
Bump up. Herb prices are totally insane.

**Comment by chme3921** [comment]
Netherbloom is 170g a stack. Fix this already
