### ISSUE TITLE
Spell dmg scaling (Rogue poison and items)

### ISSUE THREAD

**Issue by luddeguuut** [SunwellWoW/Sunwell-TBC-Bugtracker#3480]
Description: 
Spell dmg scaling for rogue's poison and other item proccs. ( example; Darkmoon Maelstrom )

How it works: 
Poison has 0 scaling with spell dmg on the server.

How it should work: 
As i've spoken to an Admin here allrdy, im not a scripter/coder or whatever. So im not  sure about the numbers, but it should scale pretty well with nature spell dmg, It worked back in the day on tbc, and some private server. i don't think blizzard removed it untill late wrath.

Source (you should point out proofs of your report, please give us some source): 
I dont know if this is a proof, but here is a vid from a private server. where a rogue playes with spell dmg gear. https://www.youtube.com/watch?v=-B4rVZ2IpfY
I might even have vods from when i played several years back with the spec,
I understand that this isnt your main concern at this point, you guys prolly have your hands full.
But i realy realy love unusual specs like this.
So if you could look into it when u get control of your server it would be great :) 
Ty for the server so far, keep it up! 👍

**Comment by Ibuprofeno** [comment]
Feenix isn't a source rogue poisons don't scale with spellpower it was a bug on THAT server.
They never scaled at all until wotlk when they added an AP scaling.
Wrath of the Lich King Patch 3.0.2 (2008-10-14): Damaging poisons now scale with attack power. Poisons skill removed. All finished poisons are available on vendors rather than created by the rogue.

**Comment by Thempest** [comment]
I can confirm, I've played on Feenix server and it was only their issue, not common feature.
