### ISSUE TITLE
Core delay/lag

### ISSUE THREAD

**Issue by trevorjk** [SunwellWoW/Sunwell-TBC-Bugtracker#3493]
Description:  There seems to be a delay/lag in the server thats not normal, it comes and goes regardless of population load.  happens in EU peaks (7k pop) and NA times (3k pop) so.  this is not that same as normal lag, this is like a 1second delay on all abilities regardless of ping.

How it works:  long ass delay on abilities randomly

How it should work:  ability should work near instantly

Source (you should point out proofs of your report, please give us some source):  common knowledge

**Comment by Grasswalker** [comment]
It is true.
Server has lag, instant skills have about 1 sec delay. As of today, the real PvP does not exist here, because it is impossible to perform an action, a combination of skills. I can not imagine the arenas in such lags ... 70 soon.
To make sure that this is server lag, all you need to do is enter a different TBC realmlist.
