### ISSUE TITLE
BG honor mark quests

### ISSUE THREAD

**Issue by kinghunterx** [SunwellWoW/Sunwell-TBC-Bugtracker#3591]
Description: 
the quests " For Great Honor " : http://db.darkwizard.pl/?quest=8367 and " Concerted Efforts" : http://db.darkwizard.pl/?quest=8371 are not being given by the NPC's: Horde Warbringer and Alliance Brigadier General

How it works: 
the npcs are not giving the quests so the honor farm at the moment is super aids and slow

How it should work: 
they should give these 2 quests in order to change your pvp marks so you get honor and farm your pvp gear.
Source (you should point out proofs of your report, please give us some source): 

this is quest was also in vanilla but now we have the 70 version that adds the eye of the storm mark;  http://wowwiki.wikia.com/wiki/Quest:Concerted_Efforts

**Comment by Azathothh** [comment]
Vanilla quests that you're talking about were removed in tbc and the one that need 1of each mark was added in 2.4.0 patch

"Marks of Honor earned from battlegrounds are no longer turned in for reputation or honor. They are now used in addition to honor points in order to purchase rewards. "
http://wowwiki.wikia.com/wiki/Patch_2.0.1
"Players can now turn in one of each battleground mark for an honor reward. The questgivers for this turn-in are the Horde Warbringer and the Alliance Brigadier General and can be found near the battlemasters in the capital cities. "
http://wowwiki.wikia.com/wiki/Patch_2.4.0

**Comment by username-is-not-taken** [comment]
Well, isn't this supposed to be a 2.4.3 server?

If you're planning to release this quest along with the other 2.4.x changes (i.e. - by the time isle quel'danas/sunwell will be released), then - sorry to break it to you - you will be completely killing pvp on the server. The amount of players in each BG is really low as it is and it will decrease very quickly if this quest isn't implemented somewhat soon. Farming ~78k honor each season without this quest in the game, and with these low-populated BGs, will be an absolute nightmare. Not to mention 78k is the minimum and it will rarely be this low honor required (86k season one, 108k season three, 118k season four if i recall correctly).
