### ISSUE TITLE
Karazhan Chess

### ISSUE THREAD

**Issue by zanthed1** [SunwellWoW/Sunwell-TBC-Bugtracker#3615]
Description: Karazhan Chess encounter is completely broken.

How it works: Move has no CD, pieces change direction with no CD, Poison Cloud does no dmg, Medivh is cheating every 10-20 seconds, pieces that are abandoned in the middle of movement stay put between squares, some uncontrolled pieces did not auto-attack, fire does dmg to players, players get kicked out of pieces randomly, players get kicked out of pieces upon dealing a killing blow, King's cleave hits 360 degrees. Pieces may possibly be affected by warrior stances. 

How it should work: Move and direction should have a CD, Poison Cloud should do dmg, Medivh should cheat less often, abandoned pieces should finish their movement, fire shouldn't players on the board, you shouldn't get kicked out of a piece unless it dies, king's cleave should hit the square in front of it and the two flanking squares. Pieces should not be impacted by warrior stance.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=b496Mc9A4U0

**Comment by deftelite** [comment]
After controlling the King for many attempts, the damage from the king appeared to be reduced by some armor value, and his melee damage had a range.  I distinctly remember abilities hitting for even 1000s and 500s of damage, for example cleave would hit for 3000.

**Comment by akrom23** [comment]
@zanthed1 

> Medivh is cheating every 10-20 seconds

The first cheat is done after 60-90 sec - repeated after 30-45 sec.
The second cheat is done after 75-120 sec - repeated after 32.5-60 sec.
The third cheat is done after 120-180 sec - repeated after 60-90 sec.

These cheats are activated only on specific amount of damage done by your pieces.

Still remember about Bishops - they spam heal for 12k every 20 sec.

EDIT: I will change these timers a little bit.

> Poison Cloud does no dmg
Some uncontrolled pieces did not auto-attack

I'm not able to reproduce these ones - provide some video, please.

**Comment by deftelite** [comment]
This event as it currently stands is an absolute mess timing wise and on the whole from numbers.

I don't know if there is some bizzaro 2.0 chess version where everything moved much faster, but it felt like the pacing of the chess event was completely off.  And after looking at a video of the content from the time period... It seems to agree.  
Here is a video from Mar 16, 2007 ( patch 2.0.10)

https://www.youtube.com/watch?v=w4sWDR8acyg

You can clearly see that moving a  piece incurs a **12 second cd** on movement, and a **12 sec cd** on change facing.  This may actually be effectively 15 seconds from when the click was made on the square.  : on this server pieces can literally sprint across the board since there is only about a 3 sec movement cap (1.5 sec gcd + a little bit of time for the piece to actually move)

This movement cd was apparently changed in later patches to 5 seconds to match the other abilities.  But I certainly remember doing the fight and sitting in fire for what felt like forever because movement was on cd.  

Medivh uses his first fire cheat at ~2 minutes into the fight, and never uses it again.  From my own experience I do remember this ability being used a few times on most chess kills.  (2-3 times usually)

He uses his super charge piece cheat at more than 5 minutes into the fight.  From my own experience I can't recall ever seeing this ability used more than once in the fight.  

He never casts the heal all pieces cheat in the video and the kill was almost 10 minutes (that I saw).  I personally didn't even know that he had this ability until seeing it on private bc servers having never seen it before and looking it up to verify that it was an actual ability. 

Most abilities (like the clerics abilities show in the video) have a multiple of 5 second cd.  The king for example had a 5 sec cd on his cleave and a 15 sec cd on his heroism/bloodlust.  The conjurer/warlock having a 5 sec cd on their fireball and a longer 15 sec cd on their dot ability.  

I know my own anecdotal evidence isn't really evidence and is the memory from 10+ years ago, but the chess I just experienced was grossly off.

Notice in the video how all abilities that the pieces use deal clean even multiples of 500 to pieces at all times.  When I was controlling the king today He would cleave for ~2600 or so (to all targets around him not just the three units in front of his facing like he should) and melee for ~500-700 almost like the numbers were coded and then reduced by the standard armor values of mobs.  Upon reviewing some videos it looks like an even 4k dmg cleave.  
Numbers wise the list at 
http://wowwiki.wikia.com/wiki/Chess_event seems fairly accurate.  

**Chess was not a difficult encounter** and was widely viewed as a loot pinata, so much so that you would occasionally have stealth classes steal a lockout and go solo/duo the chess event especially late in the expansion (it was not easy nor 100% to solo it due to the RNG nature of the opponent's moves but it was possible)

Kudos on the reset though with the chess pieces moving back into position on the board.  It looks cool, I personally never saw them move like that ever... and when the chess event was reset the pieces would just appear in their starting locations.

**Comment by akrom23** [comment]
@deftelite Thanks a lot :)
@deftelite Got a question: pieces from opposite faction should have also 12 sec cooldown on move ability?

**Comment by deftelite** [comment]
I'd have to look at the video for a better reference on that.  

After looking: It actually appears to be a little bit different.  The fastest I saw a piece move in the video was almost exactly 10 seconds.  at time index 1:32 the orc neophyte's move lights up, and then doesn't move again until 1:42.  There are also a couple instances of grunts moving at the same rate.  He also appears to move pieces every 5 seconds and only moves 0-2 pieces for each 5 second move.  This sometimes results in pieces just chilling on the side, as you can see from the video one of the doomguards on the horde side doesn't move until almost 5 minutes into the encounter.  

Edit: at 4:15 into the video it looks like he uses the all heal.  (just by the animation and he doesn't repeat that animation for the rest of the video that I saw.)  Its hard to tell because the person doesn't target any of the enemy pieces for like 30 seconds after the ability is used.

**Comment by akrom23** [comment]
Okay.

**Comment by deftelite** [comment]
So I watched through the full video and he used the heal ability twice, once at 4:15 in the video and again at 8:11.  Its one of those things I don't remember, and maybe in later patches they reduced its frequency.  I apologize for getting it wrong in my initial long post.

**Comment by akrom23** [comment]
@deftelite And the last question - pieces should have armor?

**Comment by deftelite** [comment]
No, they should not. All pieces should deal damage at even multiples of 500/1000.  for example the cleric uses his lance ability for 2000 damage, the king cleaves for 4000 damage on all targets in front of him regardless of which piece it is.  (unless the mob has a buff like the water ele/doomguard's 50% damage reduction, or footman/grunt's absorb, or the piece making the move is debuffed by the knight/wolf's stomp)
