### ISSUE TITLE
Black Lotus often respawn

### ISSUE THREAD

**Issue by blackabbath** [SunwellWoW/Sunwell-TBC-Bugtracker#3721]
Description: 
Spawn time of Black Lotus is very fast and predictable.

How it works: 
For now there're many respawning points of this flowers at Burning Steppes and it respawn timer is about 10 minutes.

How it should work: 
It's very rare flower which have respawn time is about 60-70 minutes. Only few respawn places in the world at the same time.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/object=176589/black-lotus#comments

**Comment by xethra89** [comment]
That was only in vanilla, in TBC it became a 'normal' herb with multiple spawns and can get multiple lotus from a single pick.

**Comment by blackabbath** [comment]
> in TBC it became a 'normal' herb

why is it still green then?

>  can get multiple lotus from a single pick.

not certainly. multiple lotuses could be picked with single pick in vanilla too.

**Comment by xethra89** [comment]
No, it couldnt have multiple picks in vanilla. And its green because blizzard never changed it. Why didn't they? Who knows, probably just never thought about it. They had a heck of a lot of other stuff on their minds than whether or not black lotus had green text vs white text. I remember specifically in TBC when picking herbs everyone was wondering why fel lotus was white instead of green. But we just went with it.

**Comment by blackabbath** [comment]
> No, it couldnt have multiple picks in vanilla. 

may be you doesn't play vanilla enough.
multiple lotuses from single pick - it's reality
