### ISSUE TITLE
Vanish/stealth latency bug

### ISSUE THREAD

**Issue by Rrecklessz** [SunwellWoW/Sunwell-TBC-Bugtracker#3742]
Description: 
When ever I Vanish in pvp combat  I cannot cheap shot the target fast enough. 

How it works: 
When ever I Vanish in pvp combat  I cannot cheap shot the target fast enough.  When u stealth u should get u're stealth bar  activated. For Example  My Hemorrage is on nr 2 and Sap is on nr 2 aswell(stealth bar). So when i hit stealth /vanish just to sap someone passing by i Hit it with Hemorrage instead of sap. although My auro says Stealth.

How it should work: 
Stealth bar should by instantyl usable instead of waiting half a second

Source (you should point out proofs of your report, please give us some source):

**Comment by Azmoddan** [comment]
You posted no links proving it should work other way. It worked that way on many WotLK servers because there always must be some latency lag depending on diff and other things, however creating macro should do the trick but it is one more bind on the action bar:

0. Shows the tooltip of Vanish.
1. Casts Stealth once, you'll gain stealth while not in combat
2. Casts Vanish while not stealthed, you may try adding [combat] tag as well to cast only in combat.
3. Casts Cheap Shot once.

#showtooltip Vanish
/cast !Stealth
/cast [nostealth] Vanish
/cast !Cheap Shot
