### ISSUE TITLE
Divine Intvention

### ISSUE THREAD

**Issue by lugiebob** [SunwellWoW/Sunwell-TBC-Bugtracker#3818]
Description: Bubbles a live party member making all adds ignore them.

How it works: 
This can be used on a priest that is in Spirit of Redemption 

How it should work: 
Shouldn't be able to. 

Source (you should point out proofs of your report, please give us some source): 
Minor bug

**Comment by akrom23** [comment]
> Enemies will stop attacking the protected party member, who will be immune to all harmful attacks but cannot take any action
Mobs do not attack enemies if they're immune to its damage.

**Comment by akrom23** [comment]
@lugiebob Cannot reproduce it. Divine Intervention is not applied on priest.

**Comment by Devrak** [comment]
I think what he means is that you can cast it on Spirit of Redemption and therefore waste the cooldown.

Paladin can only be cast Divine Intvention on an alive party/raid member and nothing else.

maybe it was a case where priest death was at the same time as Divine Intvention was cast and since priest was in transition it got applied, cant test this.

**Comment by akrom23** [comment]
Okay.
