### ISSUE TITLE
Precision  rogue talent not working 

### ISSUE THREAD

**Issue by kornbedo** [SunwellWoW/Sunwell-TBC-Bugtracker#3879]
Description: Talent Precison in combat tree that up %hit not working

How it works: dont get any hit chance

How it should work: should give 1% hit per talent point

Source (you should point out proofs of your report, please give us some source): 
Leaving all my hit stuff and got 0% hit chance with Precision 5/5  , trying to unlearn talents dont fix problem.

**Comment by Azathothh** [comment]
It does work but it's not displayed in your "Character Info" because Precision is increasing hit chance ([0] SPELL_AURA_MOD_HIT_CHANCE, amount: 5, base amount: 5) while in character info you can check your hit rating and how much hit chance your getting from hit rating only.
If it was increasing your hit rating then you would be able to see it in Character Info panel

**Comment by ahlens** [comment]
After so many years I finally understand why it's not displayed in character pane :P

**Comment by kornbedo** [comment]
Ok so why in my character pane the day before i got 16.5%hit and now only 11.5? Thats not my imagination
