### ISSUE TITLE
Seal of Command not scaling with Sanctity Aura

### ISSUE THREAD

**Issue by Felynda** [SunwellWoW/Sunwell-TBC-Bugtracker#3920]
Description: 
I've felt the entire time that SoC damage is really low, this is one of the reasons. More bug reports will follow. Please give target dummies to make life easier.

How it works: 
It does not scale, here is me attacking with no aura up:
![soc no aura](https://user-images.githubusercontent.com/45050227/50547398-31390380-0c39-11e9-9b9c-ec6d8ddf3c43.png)

and here with aura up:
![soc with aura](https://user-images.githubusercontent.com/45050227/50547402-37c77b00-0c39-11e9-9766-5c39c95ea9ca.png)

As you can see the damage did not increase with 10%

I know it's really small sample size but given the spread on my weapon it's more then enough. my lowest hit without aura was 321. 321x1.1 = 353. which is alot higher then my highest hit was. so its guaranteed bugged.

How it should work: 
Seal of Command damage should increase by 10% when you use Sanctity aura

Source (you should point out proofs of your report, please give us some source): 
Spell tooltip

**Comment by Felynda** [comment]
BUMP for huge paladin dps nerf not being fixed in almost a month.

**Comment by Devrak** [comment]
To get it right since its being looked at.

SoC damage math example: 

(  base melee swings damage * 0.7 + spell power bonus )  * crusade talent * vengeance buff  *  sanct aura (10% ) * imp sanct aura ( 2% ) * any other % dmg modifier like wings

SoB esample:

( base melee swings damage * 0.35  )  * crusade talent * vengeance buff  *  sanct aura (10% ) * imp sanct aura ( 2% ) * any other % dmg modifier like wings

Base melee swings damage = melee swings / attacks damage before any modifiers like armor reduction etc.
