### ISSUE TITLE
[NPC]Scryer Arcane Guardian

### ISSUE THREAD

**Issue by Mikov1605** [SunwellWoW/Sunwell-TBC-Bugtracker#3971]
Description: 
After asking him for the gem vendor, he immediately points at the aldor gem vendor.

How it works: 
Description

How it should work: 
After choosing option "Gem Vendor" two options should appear "Scryers gem vendor" and "Aldor gem vendor". Its a pretty small issue, so the fix should be easy :) 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
From what i found it seems that Scryers gem vendor in Shattrah was added in patch 3.1 
https://www.wowhead.com/npc=33637/kirembri-silvermane
So it's probably working fine right now. Please correct me if i'm wrong.

**Comment by Mikov1605** [comment]
https://www.wowhead.com/npc=19330/lisrythe-bloodwatch
Patch 2.2.0 mate ;)

**Comment by Mikov1605** [comment]
You linked the jewelcrafting trainer, i linked pure gem vendor.

**Comment by Dootz** [comment]
ok, that makes sense. But since it's **Scryer** Arcane Guardian https://www.wowhead.com/npc=18568/scryer-arcane-guardian it would be logical that he only shows location of Scryer's vendor https://www.wowhead.com/npc=19330/lisrythe-bloodwatch ? So a fix would be to replace current Aldor vendor co-ordinates with ones of Scryer's vendor. What do you think? :)

**Comment by Mikov1605** [comment]
Both factions got gem vendors :) So yeah, it would be nice if the scryers guardians would point you to scryer gem vendor, and simmiliar on the aldor side with their guardians :)
