### ISSUE TITLE
hunter deadzone

### ISSUE THREAD

**Issue by vititus** [SunwellWoW/Sunwell-TBC-Bugtracker#3975]
Description:  Hunters do not have a deadzone whatsoever. Either you get ranged or meele'd.

How it works: No deadzoning a hunter.

How it should work: There should a small zone where hunters can neither ranged nor meele you.

Source (you should point out proofs of your report, please give us some source): 
here's a screenshot of the min range on autoshots. 1 step closer and i got meele'd. I can 100% recreate this ingame at any time.

https://imgur.com/gallery/80ofBGN

**Comment by firngrod** [comment]
While I cannot find it in the patch notes, googling "wow hunter dead zone" brings up some forum posts suggesting that the dead zone was removed in patch 2.3.

**Comment by Mikov1605** [comment]
altough raids are at 2.0.1 or smth, the game itself and class skills and mechanics are at 2.4.3. So there shouldnt be a deadzone :)

**Comment by vititus** [comment]
@firngrod maybe you can link some of those?


https://www.wowhead.com/forums&topic=196566

says here that it hasn't been removed until 4.2.2 . And on all he 2.4.3 servers i've ever played on, hunters could always be deadzoned.

http://www.arenajunkies.com/topic/2471-hunterdruid-2v2-strategy-guide-videos/

also here if you ctrl+f search for deadzone it states multiple times to deadzone hunters.

**Comment by firngrod** [comment]
I was mistaken, it wasn't a forum post.  It's from a wiki.
[http://wowwiki.wikia.com/wiki/Dead_zone](http://wowwiki.wikia.com/wiki/Dead_zone)
It states that the dead zone was pretty much removed at 2.3, referring to closing the gap between melee and ranged judging by the quoted blue post.

The dates on the strategy guides you linked are from just before that patch went live, so that doesn't tell us anything.

The forum posts on wowhead refer to the dead zone being "GONE, along with hunter melee weapons", four years later around patch 4.2.  I don't think they kept the gap between ranged and melee that long.  I would guess that the dead zone for hunters at this point in time had come to mean melee range in which most of the hunter's abilities (The ranged ones) are useless.

**Comment by firngrod** [comment]
To clarify my previous comment:  The forum post from around 4.2 mentions melee weapons disappearing along with a deadzone.  My point was that I don't think they kept the deadzone for as long as they kept melee weapons on hunters, because we all agree that at some point there was a direct transition between melee and ranged, right?  No such transition without melee weapons.

**Comment by akrom23** [comment]
Works fine to me.

Melee:
![wowscrnshot_012719_215446](https://user-images.githubusercontent.com/1035215/51806752-3613c600-227e-11e9-976f-188a2300a2fb.jpg)

Deadzoned:
![wowscrnshot_012719_215454](https://user-images.githubusercontent.com/1035215/51806754-3b711080-227e-11e9-9626-c117c07f7f7b.jpg)

Ranged:
![wowscrnshot_012719_215501](https://user-images.githubusercontent.com/1035215/51806755-3dd36a80-227e-11e9-88c0-46c6361bcf67.jpg)

**Comment by akrom23** [comment]
This sums up:
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3679#issuecomment-450716014

> 2.4.3 client means 2.4.3 mechanics. 2.0 is the content we're playing-

Deadzone was removed in 2.3.3, not later.
https://us.battle.net/forums/en/wow/topic/2842564433#post-3
