### ISSUE TITLE
Ignite talent

### ISSUE THREAD

**Issue by justicex123** [SunwellWoW/Sunwell-TBC-Bugtracker#3979]
Description: 

How it works: 
Only 1 Ignite debuff can be applied on target

How it should work: 
Every fire mage can have his own Ignite debuff

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Ignite_(old)

**Comment by MadderThenMad** [comment]
Confirming the issue. This is a game breaking issue in terms of fire mage PvE (ignite can account for up to 15% of mage dps).

**Comment by tethbetatest** [comment]
I can also confirm that this is consistent with the results we're getting in our raids.

This needs to be adressed as soon as possible - as of now, bringing more than one _fire_ mage to a raid could even be seen as non-optimal - which shouldn't be the case, at all.

Therefore, I agree with the above poster - this is a **game breaking issue** for raiding mages.

**Comment by tethbetatest** [comment]
Any update on getting this fixed? This is a **game breaking issue** for mages. This issue is almost deserving of a "Critical"-label.

@akrom23 @Afgann @Dootz - do you guys need additional information in the form of a video or a more in-depth description? Let me know if I can be of any help in troubleshooting this. Thanks!

**Comment by akrom23** [comment]
Okay, okay :)

**Comment by tethbetatest** [comment]
Thank you @akrom23 <3!

**Comment by MadderThenMad** [comment]
Thanks a lot
