### ISSUE TITLE
[Karazhan][Nightbane] Aggro reset between phases

### ISSUE THREAD

**Issue by ninc** [SunwellWoW/Sunwell-TBC-Bugtracker#3990]
Description: 

How it works: 
Nightbane does not reset aggro before landing, which basicly kills all healers.

How it should work: 
He should reset aggro before landing. Only killing healers if they have hots rolling or are stupid...

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=UOxP0Ca-9c4

**Comment by neheri** [comment]
So the problem is that he resets aggro at certain moment when he's flying. He should reset it at the moment he touches ground and becoms attackable.

Now he flies and throws damage on players, healers gain a lot of aggro and it seems to be impossible to take over sometimes. I hit NB with shield slam + heroic strike then revenge + heroic strike, after that I had ~5-6k threat and he still went after healer.

Delay the moment he resets aggro until he touches ground.

**Comment by Vaanx** [comment]
When will this fix be implemented?

**Comment by marfiljamrockz** [comment]
this doesnt seem to have been implemented, Nightbane still agros mid air and its pretty hard for a druid or a warrior to pick up without serious help (Soulstone, BoP, etc)
