### ISSUE TITLE
Bandages being Improperly Interrupted

### ISSUE THREAD

**Issue by Yzzomrots** [SunwellWoW/Sunwell-TBC-Bugtracker#3995]
Description: 
When using a bandage on a Pet, while you have no DoTs nor anything attacking you. The bandage will immediately interrupt your cast bc the pet is being attacked.

How it works: 
Bandages act like a channeled HoT but damage interrupts this cast.

How it should work: 
Bandages should only be interrupted when the caster takes damage not the target unless the target is the caster.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Bandage

**Comment by firngrod** [comment]
While not conclusive, it's worth noticing that a tip describing your desired effect was removed from the linked wiki article in October of 2006, around the time when BC came out because it was pointedly NOT true at that time.  This may have changed later, but I distinctly remember damage to the target interrupting bandages at some point.  I don't know if it was ever changed or if so, when.

http://wowwiki.wikia.com/wiki/Bandage?diff=270805&oldid=85977
