### ISSUE TITLE
[spells] channeled spells/arcane missiles having no effect during the cast

### ISSUE THREAD

**Issue by Ibuprofeno** [SunwellWoW/Sunwell-TBC-Bugtracker#4005]
Description:  Arcane missiles will start its cast as normal but no missiles come out of it. Kinda hard to replicate best hint I can give is tryning to turn the camera around while starting the cast so it has to reface your character.
I don't know if this happens to other classes channeled spells such as drain life-mana/mind flay. It doesn't happen to blizzard.
How it works: Arcane missiles will sometimes does no dmg/casts no projectiles during the channeling.

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Can u record short video of this? Including combat log with missing tick.

**Comment by Ibuprofeno** [comment]
I'm trying but it's too random best I've recorded yet is it spending mana then cancelling itself instantly cast didn't even start in combatlog

**Comment by Bugadin** [comment]
Hey, I wouldn't want to let this die. Check a look at this

https://gyazo.com/49d0b6fc3cbc8781c17b045ee81cf022 
In this one the arcane missiles doesn't land while u channel the spell


https://gyazo.com/094cb5ff1753886b5e0e22e42579cd24
https://gyazo.com/54edd4b2ddd52c0f7d681c256805d348

In this 2 you can clearly see how you cast both frostbolts and none of them lands when the cast finishes.

**Comment by akrom23** [comment]
@Bugadin Show me your talent tree and char stats - spell and base stats.

**Comment by DmonicDude** [comment]
This issue still occurs when casting AM on higher lvl mobs. (player lvl +2/more) I was lvl 45 casting on lvl47/48 green ooze, AM bugged out 7~8 times over 15 minutes.

**Comment by akrom23** [comment]
@DmonicDude Because the mob resisted your initial cast, but there is no spell error displayed.

**Comment by vallsiannodel** [comment]
Hello There, i had about 2 Months to test the issue, it keeps occuring still. i have a few more informations, but to screen it - not possible, because it occures while bossfights in the worst form (A), while Farming (not provable, there is nothing indicated except global cd, server declining to cast bc gcd) (B). The Third problem occurs provable when you farm at lowlevel mobs: Casting arcane missiles on lower level mobs (in this example level 44 Hyena and a level 62 basilisk)
![WoWScrnShot_031519_005206](https://user-images.githubusercontent.com/32348181/54398966-95a62380-46bc-11e9-9a95-56d1cbcddd00.jpg)
![WoWScrnShot_031519_005208](https://user-images.githubusercontent.com/32348181/54399003-bd958700-46bc-11e9-8025-f9add98b9100.jpg)
![WoWScrnShot_031519_005014](https://user-images.githubusercontent.com/32348181/54399278-f41fd180-46bd-11e9-9323-96c1b8b23ed3.jpg)


Obviously, something is off with arcane missiles.

(A) - Arcane Missiles start casting on a boss, but after the first cast it just stops, i got that 6 times today while fighting against magtheridon, standing perfectly in range, i even moved closer to the boss to prevent it from being the range, but just one missile kept coming out the spell ending without any more cast indications
(B) - Arcane Missiles never happen after instantly hitting something with a spell (arkane blast - Polymorph) you press, there was no global cd anymore, your first spell (arcane blast) hits, but the arcane missiles never happens after pressing, but global cd hits me.
(C) - Arcane Missile Ranks down automatically on low level mobs (which shouldnt be the case for damage spells or on hostile mobs. (didnt test it in pvp). I tested it with the following Talent spec:

![WoWScrnShot_031519_005848](https://user-images.githubusercontent.com/32348181/54399172-8378b500-46bd-11e9-8384-f7b636d963d4.jpg)

Please note; That this is my Main Character and my Main spec (i raid the whole content using this spec), and i cant use my mana-damage rotation effectively if i dont have my arcane missiles working. Please fix this soon to being blizzlike. 
Thanks Alot: and kind regards!
Ingame Cython
