### ISSUE TITLE
Al'ar

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#4033]
As my previous report got closed: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/534

Reference map:
![Image](https://i.gyazo.com/0c943202d7fd1e9672887f7ba0162b4e.png)

- [ ] Still moves in a hexagon pattern before you engage him, should be flying around in a circle.

- [x] Seems like he always wants to go to platform 2 when you pull him. He should go to the platform you're at when you pull him.

- [x] Ember of Al'ar can spawn after quill, should only spawn if he moves platform

- [x] **After quill he should always go to platform 2 or 5.** (prio this please)

- [ ] Ember of Al'ar sometimes spawn on the ground during p1 instead of up at the platform.

- [x] Meteor/dive bomb should do 150k damage, currently ~85k

- [ ] Was difficult to record, but his movement is very choppy when he moves
https://i.gyazo.com/f27748dfebee028b8a9b873e58a6a343.mp4

- [x] Server crashes shortly after Dive bomb/meteor in P2 (happend on beta, not sure if it still occurs)

- [x] There should be at least 4 moves before the second wave of adds spawn

- [x] Raid encounter didn't reset after a Phase 1 wipe, couldn't enter instance.

- [x] The platform changes should be way more random, he was pretty much always picking the next platform in his rotation.

- [ ] Flame buffet damage is too low, raid members should start dying at 4 stacks.

**Comment by nennx** [comment]
fyi, random platform movement is a valid version of the fight. whether or not thats intended who knows

https://www.youtube.com/watch?v=0jzsVKPKr6I

**Comment by notsofamous** [comment]
- [x] First move should always spawn adds

**Comment by mchayes** [comment]
What is the deal with Al'ar being interruptable? Every guild streaming even discusses it.

Like here: https://clips.twitch.tv/ArtisticPopularStapleKevinTurtle

**Comment by notsofamous** [comment]
Reported it 2 weeks ago, but they need to fix the platform issue after quill before they fix that tbh. And the platform issue was reported 2 months ago.....

**Comment by xethra89** [comment]
Any update on fixing Al'ar? The fact the primary strategy right now is no tanks in phase 1 and just interrupting the Flame Buffets just makes half this fight a joke.

You have marked "After quill he should always go to platform 2 or 5. (prio this please)" as complete. If this is indeed complete, there should be no reason Flame Buffet should be interruptible anymore. 

I was also informed that "Each time one is destroyed, Al'ar's health is drained by 2% of max health." mechanic doesn't work. I haven't tested it myself, as my guild is not quite to this point yet, but I hope to see a properly working version of the fight when we do reach Al'ar.

It's cool and all that people get loot for bosses they kill, even though they aren't working correctly and have to abuse bugs to kill them because they wouldn't be able to be killed otherwise... But we should still work towards getting the fights correct because it's simply the right thing to do. Some of us don't want to kill bugged bosses, we would like to progress on how the fight is intended. 

Thank you for your efforts.
