### ISSUE TITLE
normal murmur instant casts sonic boom

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#4061]
How it works: Murmur will randomly instantly cast sonic boom killing any close to him.

How it should work: It would be a cast timer, usually after he pulls everyone into center. It actually works correctly on heroic, just not normal.

**Comment by blackwife** [comment]
Okay so I've tested this and figured out what the problem is.  Murmur has a cast timer on Sonic Boom as long as you don't attempt to interrupt Murmur's Touch at any point during the fight.  If Murmur's Touch is interrupted then he will instant cast the Sonic Boom.  I'm not sure it should be possible to interrupt this spell at all, but couldn't find any source with some quick googling.
