### ISSUE TITLE
Quest: City of Light

### ISSUE THREAD

**Issue by Berroes** [SunwellWoW/Sunwell-TBC-Bugtracker#4123]
Description: The Quest City of Light is bugged and my elemental disappeared

How it works: 

How it should work: My Elemental disappeared. Normally you just take 4 seconds of your time and auto complete it for me. However here i am waiting for you to fix this crazy small bug that has a huge effect because i cant pick aldor or scryer. 

Source (you should point out proofs of your report, please give us some source):

**Comment by firngrod** [comment]
For me, when it went up the ramp from the lower city, it went underground for a bit.  It came back up at the top of the ramp, though, and the quest continued as normal.  Was that where yours disappeared?  Also, you should be able to abandon it and try again, or is that not possible for this quest?

**Comment by Berroes** [comment]
So the proper fix is to assume you have to attempt a quest multiple times?

**Comment by neheri** [comment]
The elemental has bugged pathing when it comes up the ramp (near arakkoa part of lower city), you can complete the quest, just keep him targeted all the time and stand on the top of the stairs.

Sunwell team, please make pathing top priority. While other parts are starting to work well pathing is just unacceptable. For example ohf castle, rfc & sfk, city of light but there are also a lot of open world examples. It seems to be a general core problem. Can't say that server script is fine until this is fixed.

**Comment by firngrod** [comment]
That was not what I meant, though it can certainly be read that way.  I agree that the bug should be fixed, but it's probably more time-efficient for you to retry rather than just sit around and wait for a GM to have time to fix it for you.

Also, the questions I asked were to possibly get some more information, not to confront you in any way.  Was it the well-known "mob went below ground for a bit" but or was there something new and more sinister at stake?  And if the quest could not be repeated if failed, that would be a wholly different kind of priority bug.

**Comment by Dootz** [comment]
still have some issues that will be resolved with next update. currently cant be completed, servant gets stuck at some point.
