### ISSUE TITLE
flight form

### ISSUE THREAD

**Issue by gurtash** [SunwellWoW/Sunwell-TBC-Bugtracker#4130]
Description: 
Flight form cannot pick herbs correctly

How it works: 
you cannot loot herbs while flying in flight form

How it should work: 
you should be able to loot herbs while flying

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=Wr0EUdfOiBc

**Comment by gurtash** [comment]
server rev 2605

**Comment by firngrod** [comment]
Wiki article on flight form as of just before Wrath pre-patch landed:
https://wow.gamepedia.com/index.php?title=Flight_Form&oldid=1617441

It specifically states that:

> Although you cannot use items such as healing and mana potions while in Flight Form, you CAN interact with the world in ways that a flying mount doesn't allow: you can loot, pick herbs and skin (but not mine!) while 'sticking to the ground', when you're not 'flying'. This means you are able to avoid danger by increasing your altitude if caught unaware. Be warned that this might be an unintended result, and it might be removed in future patches.

So while it should be possible to gather herbs in flight form, it should only be so while you are effectively earth-bound, specifically so that you cannot gather herbs right on top of mobs as it's shown in the video.  The video is probably from before (And possibly a reason that) it was patched to only be possible to gather herbs while "on the ground".
