### ISSUE TITLE
[Critical] When mobs leash they will aggro anyone on their path back to starting position.

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#414]
Decription: 
If someone runs by on their mount for example, when the mobs leash they will aggro anyone in the vicinity before going back to their original location. It doesn't matter what faction you are, in party or if you're in combat with the mob. If you're close to it you'll aggro it.

How it should work: 
It should evade and go back to its normal position.

Source (you should point out proofs of your report, please give us some source): 

https://github.com/Looking4Group/L4G_Core/issues/1213

**Comment by akrom23** [comment]
@notsofamous 
Cannot reproduce.

**Comment by notsofamous** [comment]
https://i.gyazo.com/8e18c21b3957c6c90cc89f027547cd2a.mp4

**Comment by akrom23** [comment]
It's more complicated.
Let's say:

- Mob spawn spot  - the place where mob is spawned.
- Player A - this is the place of maximum distance from spawn spot - here mob is going evade and go back to the spawn spot.
- Player B - another player.

We've got 3 situations:
![situation1](https://user-images.githubusercontent.com/1035215/45777567-74590300-bc56-11e8-8665-c0ee023bb6b8.png)
In this situation, when Player A is out of aggro range, the mobs starts evade and **do not** aggro on player B, because he's too far from the spawn spot (just like player A).

![situation2](https://user-images.githubusercontent.com/1035215/45777624-a2d6de00-bc56-11e8-9a1c-684423b1ec88.png)
In this situation when Player A is out of aggro range, the mob starts evade and **do not** aggro on player B, because he's too far from the mob when he evades (not within 25y of player A).

![situation3](https://user-images.githubusercontent.com/1035215/45777799-1f69bc80-bc57-11e8-95b2-88fa8f14b539.png)
In this situation when Player A is out of aggro range, but the mob **does** attack player B, because he was near the player A (25y), when the mob was going to evade. The mob wanted to come back, but it found nearly target (player B) and the target was within aggro range (unlike the player A).

And now the question is about the 3rd situation - is it blizzlike behaviour? Should the mob evade anyway?

**Comment by notsofamous** [comment]
The mob should evade anyway. Imagine resetting a boss in a raid, if you drag him out of the room he will instantly run back to his original position. He will not first attack the few players around him and then reset.
