### ISSUE TITLE
sometimes when i use PVP trinket I get rooted in place permanently... 

### ISSUE THREAD

**Issue by baade123** [SunwellWoW/Sunwell-TBC-Bugtracker#4168]
Description: 

sometimes when i use PVP trinket I get rooted in place permanently... 
How it works: 
happened to me on hunter traps, fear/kidney , other things, sometimes i notice i get rooted for 2-3 seconds also, most of the time its no issue, and then sometimes its PERMANENT...  

How it should work: 
should not bug out

Source (you should point out proofs of your report, please give us some source): 
If needed, I started screen recording after it happened, but im not sure how to edit/upload it.... hoping others can chime in if this has happened to them..

**Comment by akrom23** [comment]
Needs screenshots with your combat log.
You can upload your screenshots here: https://imgur.com

**Comment by baade123** [comment]
i only took video and combat log was not displayed : / next time it happens what do you want me to capture?

**Comment by akrom23** [comment]
Yes. I need your combat log from the moment when you got root aura.

**Comment by ninc** [comment]
Happened to me every game in arena today. I don't have a screenshot yet, but I'll try to fix it.

**Comment by Ibuprofeno** [comment]
This happens with more skills: 
Warrior: Charge/intervene/intercept
Mage: Blink/Ice Block while jumping (this only happened once to me: i got ice block mass dispelled and i stood in the air while every attack showed immune as if I was still in block)
Druid: prolly feral charge as it happens with warrior's charges

**Comment by akrom23** [comment]
@Ibuprofeno 

> Yes. I need your combat log from the moment when you got root aura.

**Comment by Ibuprofeno** [comment]
will check through vids to see if I got to record any of these

**Comment by Ibuprofeno** [comment]
https://gyazo.com/1a6b78f5c339a43b2c281d9a0d3542ab didn't have a full combat log but this is the only one I could find through my files I was rooted 'til I died here and only lost my immunity ~10 secs after divine shield ended (a rogue tried to kick a heal and scrolling combat text showed immune)

**Comment by akrom23** [comment]
@Ibuprofeno It's not enough sadly.
I need to see when the root/stun effect/aura applied on you and removed (with timestamps).

**Comment by zefurr** [comment]
I have also been able to inflict this permanent root on others with Freezing traps and the Boar pet charge ability.

I also have this issue occur against me frequently in battlegrounds, especially it seems to occur when I die while under many forms of crowd control. In these cases the permanent root follows me in death. My ghost becomes immobile at the graveyard, after the battleground spirit healer revives me I remain immobile. I can still cast abilities, shoot, melee, fight, mount up but I cannot jump or move.

Strangely this is fixed by reloading my UI (dying again also clears this, as does relogging)

**Comment by akrom23** [comment]
@zefurr Screenshots please with combat log.
