### ISSUE TITLE
Improved Hamstring Breaks from Damage

### ISSUE THREAD

**Issue by Rocksmasherx** [SunwellWoW/Sunwell-TBC-Bugtracker#4180]
Description: Hamstring Breaks from damage like roots/nova and it shouldnt

How it works: When warrior improved hamstring procs it breaks from 1 auto atack

How it should work: Improved hamstring should never be broken from damage

Source (you should point out proofs of your report, please give us some source):

**Comment by Azmoddan** [comment]
Improved Hamstring shouldn't break through damage taken (we might just get to this conclusion through checking all immobilize-type effects' tooltips) however:

http://wowwiki.wikia.com/wiki/Entangling_Roots
Patch 2.0.1 (05-Dec-2006): All crowd control effects have a chance each second to break earlier, and their duration is capped at 12 seconds in PvP. The chance increases with resistances and the level difference between the target and the caster.

Players should be able to break free from Improved Hamstring earlier sometimes.

**Comment by zefurr** [comment]
As memory serves, Feral Charge, Improved Hamstring, Improved Wing Clip, Entrapment, Counterattack and perhaps other abilities/talents are not meant to break on damage.

They ARE subject to diminishing returns, but having players instantly break out of the 5 second Counterattack root because my pet is hitting them is definitely not normal.

This same issue was supposedly addressed for Feral Charge, the same should be done for these talents.

#3737 

There could be other root talents I am forgetting, but at least the 4 listed above should not break on damage. I am unconvinced by the general Patch 2.0.1 note concerning crowd control effects, abilities such as entangling roots, frost nova and other innately long-duration crowd controls all had early break conditions in late vanilla wow patches, I believe that the patch note listed by Dolamor was simply an expansion of the break conditions for the moves that already possessed such conditions.

Feral Charge, Improved Hamstring, Improved Wing Clip, Entrapment, Counterattack (and possibly others) never had early break conditions in vanilla wow. From observation of other private servers, these moves typically do not break on damage, this fact is never contested, leading me to suspect this is the intended behavior (otherwise, these effects being unbreakable would likely be a huge source of complaints)
