### ISSUE TITLE
[Item] Darkmoon Faire: Blue Dragon proc-chance

### ISSUE THREAD

**Issue by aeyers** [SunwellWoW/Sunwell-TBC-Bugtracker#4190]
Description: Darkmoon Faire: Blue Dragon's proc-chance might be wrong. 

How it works: I have both Eye of gruul(2% proc-chanse) and Darkmoon Faire: Blue Dragon(2% proc-chanse) on a resto druid. Eye of gruul got 45 procs during a 2.5 hour raid and Darkmoon Faire: Blue Dragon got 15 procs.

How it should work: If the proc-chance on Eye of gruul is right Darkmoon Faire: Blue Dragon should have a higher proc-chanse.

Source (you should point out proofs of your report, please give us some source):

**Comment by Azmoddan** [comment]
You should test it more than once - you could have been just unlucky with the RNG.

**Comment by aeyers** [comment]
Got 13 procs in our 4 hour raid yesterday. 67 procs with eye of gruul.

**Comment by aeyers** [comment]
Another raid with low procs, 17 vs 71 procs, 4 hour raid. Should proc ALOT more with the amount of casts i have as a druid.

**Comment by MiekZer** [comment]
Have it on my priest.
I confirm that proc rate is too low.
Looks like it has been nerfed to 1% like some other level 60- trinkets but this one trinket proc rate is not supposed to scale down in tbc due to it's 2% statement. I think the text was then changed and nerfed on a later expansion but not tbc.
Should be 2% on every cast, instant casts like non instant casts. even a buff/totem placement/etc should be able to proc it.

**Comment by Cherryxo** [comment]
At least post a print screen to show that what you are saying is actually accurate. This whole thing where people don't care to provide any info that what they are saying is actually true is getting really annoying.
