### ISSUE TITLE
[Crafting] Dragonstrike etc.

### ISSUE THREAD

**Issue by SlizeTBC** [SunwellWoW/Sunwell-TBC-Bugtracker#4199]
I wonder why Dargonstrike is already in the Game and Items like "Deathblow X11 Goggles" aren't out yet. Same with all those other Goggles.

Dragonstrike and Goggles were released at the same time. If you go with that timeline, Purified Shadow Pearl shouldnt be out yet aswell.

https://www.wowhead.com/item=32836/purified-shadow-pearl
https://www.wowhead.com/item=28439/dragonstrike
https://de.wowhead.com/item=32478/totmacherbrille-x11

Summary of 2.1 Patch releases:
https://github.com/ccshiro/cc-buglist/issues/1046

**Comment by Bugadin** [comment]
I don't know netiher. Sunwell respects some "blizzlike stuff" and some not. I would like that they were fair with all profs but there is no justice in this world, you know :/

**Comment by SlizeTBC** [comment]
I guess it's not intended to be unfair from the Sunwell Team. It is an old game and there are false Informations out their. I mean I could be wrong aswell. But as far as I could figure it out, alot of the Items from JC are banned, but some arent.

Like: 
"Necklace of the Deep". Afaik it has been banned, but "Purified Shadow Pearl" or "Purified Jaggal Pearl" are still in the game.

Same with "Mystic Dawnstone" from Halaa. This should be even Patch 2.4 based on my Link "ccshiro/cc-buglist#1046" above.

**Comment by SlizeTBC** [comment]
Either you ban all those Gems and Items or make it equivalent for everyone. I mean noone will craft Engi goggles after T6 release, since most of the ppl will have T5 or gear with equal or better statsthan those goggles.

It's all about making professions equal.

**Comment by Bugadin** [comment]
> Either you ban all those Gems and Items or make it equivalent for everyone. I mean noone will craft Engi goggles after T6 release, since most of the ppl will have T5 or gear with equal or better statsthan those goggles.
> 
> It's all about making professions equal.

True, it's unfair to release googles with t6 raids because they become useless... I know it would be pretty much op at the release of the server but it's not that much anymore at this point so please...

Think about it.

**Comment by Kiszh** [comment]
Dragonstrike wasn't added in patch 2.1. It was, however, only usuable in mainhand for a good while. Your source is wrong, which is funny considering you talking about false information. 

Wowhead also lists some heroic instance loot being 2.1 items. 

For instance: https://www.wowhead.com/item=29353/shockwave-truncheon&bonus=4091or https://www.wowhead.com/item=30541/stormsong-kilt&bonus=4109 or https://www.wowhead.com/item=30538/midnight-legguards&bonus=4105

or karazhan loot: https://www.wowhead.com/item=28579/romulos-poison-vial 

Or Gruul loot: https://www.wowhead.com/item=28825/aldori-legacy-defender

My best guess is that it's because items were upgraded in 2.1.

I do, however, agree with the sentiment of this report. Some stuff is already out, which is unfair to some classes or professions. A good example would be the boots of blasting that some casters are sporting, while no one else can get their boots.

**Comment by SlizeTBC** [comment]
First of all, I never said my Information is correct, as you can see i already said that I could be wrong aswell. 

> I guess it's not intended to be unfair from the Sunwell Team. It is an old game and there are false Informations out their. **I mean I could be wrong aswell**. But as far as I could figure it out, alot of the Items from JC are banned, but some arent.
>

And why is my Information about Dragonstrike wrong? Can you proof it? If you check this link from WowHead it clearly says Patch 2.1:
https://www.wowhead.com/item=28439/dragonstrike

Everything I said is based on Information from WowHead and that old Link from github about TBC Patch releases. If im wrong and Dragonstrike was added earlier pls correct me and link that source.

**Comment by Ironjudgment** [comment]
First mention of Dragonstrike on wowiki is on May 10, 2007 which on the wow timeline is before patch 2.1 https://wowwiki.fandom.com/wiki/Dragonstrike?oldid=636198

**Comment by Kiszh** [comment]
What I tried to show you with the ocean of wowhead links was that the patch numbering on wowhead is off. Kara loot didn't release in patch 2.1, nor did heroic instance loot. That unequivocally proves that wowhead is not to be trusted. 

Further more, you can go to the comment section of the wowhead link that you yourself provided and read the oldest comments. 

I'll spoil it for you:

By Dain (2,026 – 2·20) on 2007/01/23 (Patch 2.0.6)

"(...) However, this weapon now represents probably the best SS/Hemo weapon currently in game, beating out even the Gladiator weapons by a comfortable margin (...)"

Thats 7 days after TBC release.

**Comment by Bugadin** [comment]
We were talking about googles guys xD

**Comment by Ibuprofeno** [comment]
Them problem is they use item release dates but 2.4.3 mechanics/stats.

BS maces were one handed 'til 2.4.2 when: Most Main-Hand weapons are now One-Hand weapons.  (https://wowwiki.fandom.com/wiki/Patch_2.4.2)

Karazhan/(some) heroic loot got buffed in 2.1: The majority of level 70 epic items have been upgraded to reflect their intended power.  (https://wowwiki.fandom.com/wiki/Patch_2.1.0, not a proper source but adding a forum from april'07 (2.1 hit in may '07) 

All this means is we got some 2.1+ content out (ie: druids having badge of tenacity, even if it got removed from loot tables later) and some unbalanced proffs: engineering boots were disabled in arena in 2.4.3 ([Rocket Boots Xtreme] and [Rocket Boots Xtreme Lite] can no longer be used in the arena. These no longer have a failure chance. ; https://wowwiki.fandom.com/wiki/Patch_2.4.3 ) but they can't be used in this 2.0 content, and don't have 2.1 goggles either. Even some 2.1 mats to make cosmetic such as the eng epic flying mount aren't even though you can learn it at the trainer.
Meanwhile BS maces are one-handed instead of main-hands making every melee use them) (also, mh and oh haste buff stack, which it shouldn't...) 

It's pretty messy atm. I honestly hope all 2.1 content is released with Hyjal because this customly gated content is bullshit.

**Comment by Dootz** [comment]
yup, most of missing things will be most likely released with Hyjal
