### ISSUE TITLE
Mage Arcane Missiles 

### ISSUE THREAD

**Issue by michv321** [SunwellWoW/Sunwell-TBC-Bugtracker#4214]
Description: 
Sometimes Arcanes Missiles don't work properly. 

How it works: 
It looks like spell is started and just after that cancelled. You lose mana, but there is no spell at all. I waited few seconds and try casting it again - same result. If i casted other spell, or hit, then next Arcane Missile worked properly. For me that issue often appear when AM are combined with Polymorph spell (for ex. poly -> AM, or poly for one target and AM for other).

How it should work: 
Properly.

Source (you should point out proofs of your report, please give us some source): 
I checked that few times, bug appears, but not always.

**Comment by DmonicDude** [comment]
I have had the same issues. However I have found that casting AM on high level targets also causes the effect, best I can think of is that it is also related to resist/miss chance. I was able to reproduce effect each time I engaged with mops 4+ lvls higher

**Comment by akrom23** [comment]
More info #4005.
@DmonicDude @michv321 Give me an answer there.

**Comment by vallsiannodel** [comment]
Hello There, i had about 2 Months to test the issue, it keeps occuring still. i have a few more informations, but to screen it - not possible, because it occures while bossfights in the worst form (A), while Farming (not provable, there is nothing indicated except global cd, server declining to cast bc gcd) (B). The Third problem occurs provable when you farm at lowlevel mobs: Casting arcane missiles on lower level mobs (in this example level 44 Hyena and a level 62 basilisk)
![WoWScrnShot_031519_005206](https://user-images.githubusercontent.com/32348181/54398966-95a62380-46bc-11e9-9a95-56d1cbcddd00.jpg)
![WoWScrnShot_031519_005208](https://user-images.githubusercontent.com/32348181/54399003-bd958700-46bc-11e9-8025-f9add98b9100.jpg)
![WoWScrnShot_031519_005014](https://user-images.githubusercontent.com/32348181/54399278-f41fd180-46bd-11e9-9323-96c1b8b23ed3.jpg)


Obviously, something is off with arcane missiles.

(A) - Arcane Missiles start casting on a boss, but after the first cast it just stops, i got that 6 times today while fighting against magtheridon, standing perfectly in range, i even moved closer to the boss to prevent it from being the range, but just one missile kept coming out the spell ending without any more cast indications
(B) - Arcane Missiles never happen after instantly hitting something with a spell (arkane blast - Polymorph) you press, there was no global cd anymore, your first spell (arcane blast) hits, but the arcane missiles never happens after pressing, but global cd hits me.
(C) - Arcane Missile Ranks down automatically on low level mobs (which shouldnt be the case for damage spells or on hostile mobs. (didnt test it in pvp). I tested it with the following Talent spec:

![WoWScrnShot_031519_005848](https://user-images.githubusercontent.com/32348181/54399172-8378b500-46bd-11e9-8384-f7b636d963d4.jpg)

Please note; That this is my Main Character and my Main spec (i raid the whole content using this spec), and i cant use my mana-damage rotation effectively if i dont have my arcane missiles working. Please fix this soon to being blizzlike. 
Thanks Alot: and kind regards!
Ingame Cython
