### ISSUE TITLE
Crit doesn't back to normal after disarm

### ISSUE THREAD

**Issue by icarovps** [SunwellWoW/Sunwell-TBC-Bugtracker#4283]
Description: 
The crit doesnt back to normal after disarm. When disarmed, the crit drops because the unarmed skill and negated stats of the weapon. To fix this, need replace weapons or re-equip then.

How it works:

How it should work: 
After a disarm, the crit drops, but when the disarm finishes, the crit need go back to normal.

Source (you should point out proofs of your report, please give us some source): 

Video: https://youtu.be/zh9y1uT-e2o

**Comment by Pikseh** [comment]
Are you sure this is in fact correct and not just a bug on your character's sheet stats?

Like let's say you have 20% crit before, and 5% crit after disarm. If this is a bug, then testing your distribution of crits and hits after the disarm wears off should be much lower than before the disarm. If this is not the case, and the distribution is unchanged, then the bug is only visual on your sheet stats and not on your character's actual stats when calculating your hit/crit distribution.
