### ISSUE TITLE
[Shaman][Talent] Thundering Strikes

### ISSUE THREAD

**Issue by icarovps** [SunwellWoW/Sunwell-TBC-Bugtracker#4284]
Description: 
Thundering Strikes doesnt working

How it works: 
The talent skill adds 5% crit chance

How it should work: 
The talent doesnt add any crit chance. In character interface, the crit is 12.51%, but the addon shows the correct: 17.51%.

Source (you should point out proofs of your report, please give us some source): 

![wowscrnshot_020619_132648](https://user-images.githubusercontent.com/39803279/52378545-1b480b00-2a4f-11e9-8a29-621374970f3a.jpg)

**Comment by firngrod** [comment]
It is possible that the wording of the talent is relevant for this.  From the talent:  "Improves your chance to get a critical strike with your weapon attacks by X%."
The character sheet specifically shows melee stats, as opposed to melee weapon stats.  It's possible that the "weaponless" attacks in ghost wolf form, for instance, plays in to this distinction.  However, if any of this was the case, I would have expected the character sheet to reflect the state of any attack made with the character in it's current state, including which form the character was in, whether or not it would be with a weapon or not and so on.

Have you run any tests on whether or not the talent crit chance is actually applied to your attacks?  This might help determine whether the bug is in the interface or in the core game.

https://wow.gamepedia.com/index.php?title=Thundering_Strikes&oldid=1399936

**Comment by icarovps** [comment]
Ill run a instance with recount to test the crit chance

**Comment by akrom23** [comment]
Works fine.
