### ISSUE TITLE
[Aggro mechanic] Evade removes auras, that should prevent evade mechanic.

### ISSUE THREAD

**Issue by kovaq** [SunwellWoW/Sunwell-TBC-Bugtracker#429]
Decription: I've sapped mob, and his friends got aggro on me while i was in stealth. Lucky for me, he couldnt reach me and lost his aggro. The problem is that he chainpulled his sapped friend with him, he was sapped during that pull, and when lost aggro, that sapped one cleared himself from sap aura. 

How it works: His evade removes stuns that should prevent him from removing that aura.

How it should work: He should not spin to me while sapped, and should not got evade while losing aggro. He should just stand and wait till sap will end, then run to me with aggro, if im still in combat. When he lost aggro, he should still stay with sap.  (because sap can be applied off-combat, and should not apply combat on player)

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Sap
https://classicdb.ch/?npc=4853 (that creature was sapped, chainpulled with https://vanilla-twinhead.twinstar.cz/?npc=4854 , his pet and one more stonevault trogg (mauler?)

**Comment by akrom23** [comment]
So who got aggro on you? The sapped mob or his friends?
If you first sap mob and other mobs aggro on you, then the sapped one shouldn't attack you at all.

**Comment by akrom23** [comment]
It seems it's not a bug. Let me explain that.
We have three or four mobs out there. You sapped one, but unfortunately the other one (I guess boss) aggro on you. 
When mob aggroes, it also searches the area for other mobs that can help him in fight.
So in this case, every mob around the boss aggro on you (even the sapped one - you didn't see it, because it was stunned). 
After you used vanish, every mob evaded (including the sapped one) and this caused sap aura to be removed - that's a normal behaviour.

**Comment by kovaq** [comment]
No vanish here, i just hid behind pillar, and caused LoS (Lose of Sight or Line of Sight as you want), he couldnt find range to engage fight by hitting and destealthing me, but yes, its the same effect. By the way, i saw his aggro on me, because of "target of target" feature. If you say that evade is more powerful, im accepting that. I always thought, that sap is prevailing over evade, because of his off-combat use, nothing more, nothing less :)
