### ISSUE TITLE
Aran (and more) cc exploit

### ISSUE THREAD

**Issue by MiekZer** [SunwellWoW/Sunwell-TBC-Bugtracker#4295]
Magic dust (easy farmable vanilla object) can be used to cc 30sec any mob without any chance to fail. 
This object is supposed to fail very often on level 30+ mobs.
On Aran you can then cc every elementals with this object instead of tanking the ones you cannot cc.
Probably exploitable on other bosses too.

**Comment by thenumberpurple** [comment]
Magic dust is not supposed to fail very often on level 30+ mobs. Why does this wrong bug post get insta fixed with no proof, source, etc? I wonder why the HUGE bugs I took the time to beta test and report (with proof btw) are still not fixed

**Comment by MiekZer** [comment]
On wowhead they state that before build 13914 (aka before 4.1.0, probably that after this build chances are strictly 0 above level 30) it's unreliable on targets above level 30 without mentioning % chance to work on a target level 60, 70, etc.

Also I have never seen a video mentioning this trick on Aran, it's obviously a trick found on private server when the boss is too hard and the script is bugged allowing this trick (and other bosses with adds) to trivialize fights.

But don't worry my boy, just ask your tank to build some threat on adds that are not cc and you will kill Aran easily.

**Comment by thenumberpurple** [comment]
What are you talking about? This was 100% usable in tbc. You still provided 0 proof of it not. You say there is no video of people using it on Aran but theres multiple comments on the wowhead from 2006-2008 of people talking about using it. 

Also dw my boy, my tanks are holding just fine in t5. Don't need magic dust to do kara fights. Was ofc never my point. Point was this is wrong, ofc has 0 proof because its wrong, yet still got insta fixed. Meanwhile I spent time in the beta reporting big bugs with proof that still have not been fixed. 

It was really changed in patch 3.2

**Comment by mchayes** [comment]
It's really weird, all these posts that @MiekZer did yesterday got instantly fixed even though there was zero proof of anything added. Please explain @Afgann

**Comment by MiekZer** [comment]
All wowhead comments only talk about pvp. Never about pve use of thid object because it's obviously not supposed to be a reliable source of instant cc. 
Do you imagine the whole raid having magic dust and using them on Hydross adds how the fight will be easy as fuck? cc kt items, cc skeletons adds in sunwell and so more

**Comment by thenumberpurple** [comment]
You saying they only talk about PvP uses tell me you only read the first comment. I also don't think you even know how this item fully works. The item would not work on either of this bosses you gave as examples, so I really question if you have any idea about anything you talk about.

**Comment by MiekZer** [comment]
Hydross elementals : can be banished and fear by warlocks so this item if we folllw the aran logic will work on them. 

Kael thas items : can be cced freezing trap and stuns so this item with the actual script will work on them.

If we follow this logic then it will also works on bt fights and sunwell.

This item is obvioisly not supposed to be a reliable source of infinite and instant cc on pve otherwise it would have been already known since retail tbc and this is absolutely not the case.

It's just a trick found on some private serv lacking some scripts.

Pve and pvp mechanics differ.
And I have read every comments. If you mention the use level 60 for hunter quest I suggest you look videos of the said quest(retail) and will realize in 2 videos the dude wiped due to a fail using his magic dust. So it's not working all the time.

So if you agree (as you stated) the item doesn't work against bosses like hydross kt then you agree it cannot work against aran elementals.

Ps : show me a retail video of za malacrass fight where they use magic dust to cc the 4 adds and trivialize the fight as fuck?

**Comment by chme3921** [comment]
Show us a video of it failing repeatedly in TBC. You can't find one, because any such video doesn't exist.

If you want something changed, the burden of proof is on you for this exact reason. Magic Dust usage in TBC wasn't very well known, which is why it was changed in WotLK (check the 3.1 patch notes) because more people found out about it and were using it more and more in PvP, where it had a full 30 second duration, even in PvP. The people that knew about it in TBC just kept it quiet, even though it isn't that significant. It just makes a few fights a bit easier. More of a convenience than for ease tbh.

Mobs immune to CC are still immune to it. Mobs not immune to CC will not be immune to it.

**Comment by thenumberpurple** [comment]
I said that I question if you know anything that you talk about. You then said magic dust is a "reliable source of infinite and instant cc on pve". Again proves to me you have never even used this item, let alone use this item to "trivialize fights". My biggest laugh so far was you suggesting to CC felmyst skeletons.
