### ISSUE TITLE
Mage Invisibility does not reduce threat

### ISSUE THREAD

**Issue by MadderThenMad** [SunwellWoW/Sunwell-TBC-Bugtracker#4312]
Description: Mage Invisibility does not reduce threat with each second of it's duration. Only when mage goes fully invisible threat is modified (wiped actually). With each second of "channel" mage threat should be reduced by some % - source tell it's 10% per second and after 5 you are fully invisible and your threat is completely wiped. 

How it works: 

Threat is not being altered at all during pre invi channel duration.  (confirmed with .debug threatlist).

How it should work:  For each second of channel threat should be altered by 10%. 

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/forums&topic=13158

**Comment by Ironjudgment** [comment]
documented testing (video, screenshot) would be nice but I can confirm its supposed to work like explained but instead of 10%, should be 20%.

`Every second for which Invisibility is counting down, the Mage loses 20% of his current threat (if used in a PvE situation). Once the timer hits 0, the Mage gains full invisibility, and is removed from combat. `

Source dated 7 May 2007 before patch 2.1 release.
https://wow.gamepedia.com/index.php?title=Invisibility&oldid=628853

**Comment by MadderThenMad** [comment]
@akrom23 

#1791 by Anakin
Spells: Invisibility should reduce threat by 10% each second.
(https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4312)

It should be 20% as Iron proved
