### ISSUE TITLE
Paladin Talent: Sanctified Seals

### ISSUE THREAD

**Issue by Rasnia** [SunwellWoW/Sunwell-TBC-Bugtracker#4313]
Description:  Paladin talent: Sanctified Seals - Makes seals 100 % Resistance to become dispelled on enemies, and also increases crit by 3 % (3/3 talented)

How it works: Seals can be dispelled

How it should work: 100 % to resist dispells

Source (you should point out proofs of your report, please give us some source): None

**Comment by firngrod** [comment]
How are they being removed?  Which skill(s) are being used?  I'm asking because certain skills don't do the "dispell" action, but rather an immunity or downright remove action, such as Divine Shield and Ice Block.  These abilities would still remove the seal, even if Sanctified Seals is maxed.

You can see a list of spells which perform the resistable dispell action on the following page:

https://wow.gamepedia.com/index.php?title=Dispel&oldid=1432725

**Comment by zefurr** [comment]
SEALs refer to the buff on the paladin himself.

JUDGEMENTs refer to the debuff on the enemy.

Reading the talent, I would expect its still perfectly normal to be able to dispel the judgement debuff. It's the paladin himself who cannot have his buff removed

**Comment by firngrod** [comment]
True, I was way off on that one.
It's possible that the original poster made the same mistake.
The question also still stands, the issue may be with one of the dispelling skills rather than with the seals/talent itself.

**Comment by akrom23** [comment]
Tested - works okay.
