### ISSUE TITLE
Hunter abusing bugged freezing trap

### ISSUE THREAD

**Issue by Freshbtw** [SunwellWoW/Sunwell-TBC-Bugtracker#4315]
Description: As you can see in 3 clips here, the hunter is abusing a freezing trap bug to instantly trap people. 

How it works: When the hunter places the trap and uses Feign Death, the target gets trapped instantly.

How it should work: There is a short delay when the target should be able to be trapped after it is placed(around 2sec I think)

Source (you should point out proofs of your report, please give us some source): 
https://clips.twitch.tv/GorgeousScaryLardChocolateRain
https://www.twitch.tv/freshkimo_/clip/InventiveSavoryLionNerfBlueBlaster
https://www.twitch.tv/freshkimo_/clip/FlaccidBoldVelociraptorFloof

**Comment by firngrod** [comment]
I'm not absolutely certain on this, but if I'm reading the below article correctly, the 2 second arming speed is only if the hunter is in combat while laying the trap.  Thus, using Feign Death cleverly should allow you to instantly trap someone, although I would expect Feign Death to have to be used before laying the trap.

https://wowwiki.fandom.com/wiki/Trap?oldid=1421833

**Comment by Ironjudgment** [comment]
> Traps may be placed in combat and are on a 30 second timer with a 2 second arming time while in combat. Only one trap can be active at a time. 

In every clip you can see that he has had used feign death (cleared comabt) before placing the trap, making the arming process instant. (Everything seems ok?)

Quote from wowwiki dated March 14, 2007
https://wowwiki.fandom.com/wiki/Trap?oldid=543586

**Comment by Freshbtw** [comment]
In no way it's correct that it should be trapping instant. The team of the hunter/druid that is using it even said that it's bugged.

**Comment by Ironjudgment** [comment]
How is it bugged then?
If hunter clears his combat and places trap, it will be armed immediately. In the video you even move away/towards from/to hunter activating the trap. If you stood still the trap wouldn't activate immediately.

The point is that he is placing the trap while not in combat which allows the trap to be armed instantely without the 2sec period (not in combat).

**Comment by Freshbtw** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2081

Same issue on a different server some time ago. Read everything there, you have your proof

**Comment by Ironjudgment** [comment]
Placing trap while not in combat: https://youtu.be/LamuL4e4Y0E?t=104

Hunter using FD and then instantly placing the trap: https://youtu.be/LamuL4e4Y0E?t=150

Video from 2006

Anything else?

**Comment by Freshbtw** [comment]
That was not even close to being instant FYI. Check the first and second clip I linked.. that is instant

**Comment by Ironjudgment** [comment]
Okay fine, let Devs decide...

And also you say that in this clip https://youtu.be/LamuL4e4Y0E?t=150 in the time frame of 3 secs (2:31-2:34), hunter had time to use FD then place trap for 2 sec and run away? It's obvious it was an instant cast. You can also see that opposing player has run into the trap and activate it after a sec.

**Comment by Freshbtw** [comment]
On another note, both target + caster have to be out of combat for it to be an instant trap. Otherwise it's 2 sec arm time.

@Ironjudgment As you can see on the vid you linked, his trap is on the right top actionbar. He places it pretty much instantly after his FD, right on top of the warr. Yet he did not get instant trapped. There was a delay

**Comment by firngrod** [comment]
I see no proof in that bug report from another server, nor can I see that they reached your conclusion, hence the angry post that it was still an issue three years later.

An important thing to keep in mind here is:  If it was bugged during retail 2.4.3, that's how it should be on this server.  I can't find anything saying definitely that it worked one way or the other during retail.  It's pretty clear that the intention was to have a 2 second arming time, but the intention is irrelevant.  There are indications that the behavior for casting traps out of combat was instant arming.  If this was the (unintended) behavior at 2.4.3, it should be intended behavior on this server, unless I misunderstand the developers' intentions.

Ultimately, this will be up to the developers to decide.

**Comment by Freshbtw** [comment]
“The desired situation is if the Hunter is out of combat (after using FD) but his target is in combat the trap should have 2 seconds arming time. Traps should be instant only when both the hunter and his enemy are out of combat.

Desired:

Hunter in combat, victim out of combat - instant arming time.
Hunter in combat, victim in combat - 2 seconds arming time.
Hunter out of combat, victim out of combat - instant arming.
Hunter out of combat, victim in combat - 2 seconds arming time.
Hunter combat state is irrelevant.“

From the dev.. how is that no proof of a fix xD

**Comment by Ironjudgment** [comment]
From dev, from another server, from 27 Nov 2012 and without any sources you might add.

Let devs decide.

**Comment by firngrod** [comment]
@Freshbtw:
As @Ironjudgment mentions, you can prove that someone not involved with Blizzard made that decision in 2012, not that it was that way on retail in 2008.

I'm not sure how that behavior would even be handled.  "Target is in combat."  Is that the target of the hunter at the time of casting the trap?  If so, just macro clear target and we're back to the start.  If it's "Anyone about to trigger the trap", do we then have a case where one player can trigger the trap but another can't based on whether they were in combat at the time?  That would require an odd way of thinking and structuring the data where the arming time for any given trap is set for the players rather than the traps.  Seems odd to me, and I find it it unlikely that that is how it was done on retail.
Furthermore, Feign Death should remove the hunter from combat, again putting us back to square one.

> It can be used to exit combat in order to drink water or if one needs to go the bathroom in the middle of a fight (does not work anymore during boss fights as of patch 2.3.0).
(https://wow.gamepedia.com/index.php?title=Feign_Death&oldid=1434435)

**Comment by zefurr** [comment]
Playing a hunter, so there's some degree of bias.

If we can agree on hunter traps having no arming time when the hunter is out of combat, and there are no explicit patch notes about this issue since vanilla I'd say look to the vanilla behavior. Did a hunter using FD trap on a scattered target trigger instantly freeze or was there a delay? What was the behavior if walking up to yellow (non aggressive) mob and dropping a freeze trap at it's feet?

**Comment by estenv** [comment]
What a completely pointless discussion.

On server:
[https://clips.twitch.tv/GorgeousScaryLardChocolateRain](https://clips.twitch.tv/GorgeousScaryLardChocolateRain)

In retail:
[https://youtu.be/LamuL4e4Y0E?t=104](https://youtu.be/LamuL4e4Y0E?t=104)

It's obviously not working like it did in retail based on these 2 videos. Never have I experienced a instant hunter trap _TRIGGER_ time (not cast, Ironjudgment seems to be talking about trap casting times for some unknown reason)  in PvP. Not in retail or on any private server.

In this case it really should be the other way around, someone should provide proof of a instant trigger trap happening in PvP in retail TBC (because they wont be able to). 

Either way the provided videos here already prove it's working incorrectly on the server, there is a clear delay in both the retail clips, you are supposed to be able to move away from the trap before it triggers. As someone mentioned, that's the entire reason people used scatter shot to set up traps.

**Comment by zefurr** [comment]
That retail clip doesn't seem particularly relevant.

There's no one on the trap to trigger it before the arming time has passed. We need a clip of a hunter out of combat (or feigning to exit combat, with their pet also disengaging) and laying a trap at the feet of another target. Hunter has to be essentially point blank.

That said I'm inclined to agree as I do not recall ever seeing instant feign traps back in the day. Old clips of high rated hunters never seem to show them even attempting to do this, even in situations where another player is at risk of coming over and soaking their traps. I'd expect that if a hunter was scatter trapping a healer and their was a good chance of the healer's partner walking over to soak the trap that they would feign trap for an instant freeze to ensure it wasn't soaked by the partner.

At the same time I DO believe instant trap arming out of combat was a thing, but only observed it being used in PvE.

**Comment by firngrod** [comment]
@asdfman I fail to see that it's pointless when people obviously disagree, and it can have a big impact on the game.

Furthermore, when someone requests a change or reports a bug, the onus is on them to provide some evidence that a change is required, never the other way around.

Later in the video you link, there is a point which does indicate that the Feign-Trap shouldn't instantly trigger, though.
https://www.youtube.com/watch?v=LamuL4e4Y0E&t=2m30s
That's the closest I have seen to what we're arguing about, and it does not trigger until 2 seconds later.  I would consider that proof.  Didn't notice it the first time I watched it.

One thing is for certain, though.  Instant triggering of traps happened in vanilla.  I wonder if people are getting that mixed up.

**Comment by zefurr** [comment]
@firngrod 
I spotted that same moment you linked. The hunter doesn't pull his pet off the priest, so he would not have dropped combat.

**Comment by akrom23** [comment]
https://www.youtube.com/watch?v=LamuL4e4Y0E&t=2m30s
Hunter after FD still have combat.
2:32 uses FD
2:34 cancel FD and drops trap
2:36 trap is triggered.

**Comment by akrom23** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4537#issuecomment-461992520
I think he's right about the arming time.

**Comment by balo-git** [comment]
I agree with the fix, but I still reject that video. (zefurr)

The hunter's pet never stopped attacking the priest in that clip, so the hunter would not have left combat.

**Comment by vakoz** [comment]
Now it always takes 2 sec to arm trap, even if you aren't  in combat. Atleast in duels

**Comment by Nachopie123** [comment]
> https://www.youtube.com/watch?v=LamuL4e4Y0E&t=2m30s
> Hunter after FD still have combat.
> 2:32 uses FD
> 2:34 cancel FD and drops trap
> 2:36 trap is triggered.

Clip isn't relevant to the fix seeing as the hunter is still in combat which you can obviously tell by just looking at his player icon.
