### ISSUE TITLE
[Hunter] Misdirection charges used by Frost (slow) trap

### ISSUE THREAD

**Issue by zefurr** [SunwellWoW/Sunwell-TBC-Bugtracker#4318]
Description: 
Misdirection charges are consumed when enemies walk over a frost trap.

How it works: 
Misdirect someone, pull some mobs over a slow trap, misdirect charges get used up. No shots fired, no attacks of any kind made.

How it should work: 
Misdirect charges should only be used by a hunter's ATTACKS as stated in the tooltip.

Source (you should point out proofs of your report, please give us some source):

**Comment by firngrod** [comment]
An article about Misdirection at the time of BC has a tip about using it with Explosive Trap, indicating that traps should indeed work with this.  However, it's arguable whether Frost Trap should be considered an attack since it does not do any damage.  Neither does Distracting Shot, though, and that should definitely work as far as I can tell.

It seems to me that it should depend on whether or not Frost Trap, or the effect it applies to the targets, cause any threat.  Whether they do, I do not know.

https://wow.gamepedia.com/index.php?title=Misdirection&oldid=1559286
