### ISSUE TITLE
Kael'thas [Staff buff dosn't work]

### ISSUE THREAD

**Issue by Highdps** [SunwellWoW/Sunwell-TBC-Bugtracker#4346]
Description:

How it works: 
Buff from legendary weapon Staff didn't works, players with buff still geting stun/silence/disorient

How it should work: 
Buff from legendary staff should give immune to stun/silence/disorient

Source (you should point out proofs of your report, please give us some source): 
I don't have yet, we get this bug today

**Comment by neheri** [comment]
Staff should not grant immunity to fear. 

It also has 30 yds range and if you move out of range buff from staff is removed. You need to use the staff again once you get in range in order to activate the buff again (best create macro under spammable skill with /use).

We noticed some problems with staff buff as well, but when we ordered people with staff to move so every person is always in range and spam macro with staff usage there were no problems whatsoever.

**Comment by Highdps** [comment]
I get a stun debuff when we move as group with all ranged dps, soo it should not be the range case
MT get dissorient when he had buff on
Idk about more problems with staff buff, we going tommorow soo we will be watching this and capturing screens/videos

**Comment by Highdps** [comment]
Looks like rebuffing staff dosn't overwrite buff
Buff still apear in list but it dosn't works, after removing it and reused staff it works as intended

**Comment by bshakex** [comment]
If you're a hunter then Bestial Wrath is overriding your staff buff immunity. Right clicking the buff or applying a new buff after every Bestial Wrath is the only way to fix the problem currently.

**Comment by akrom23** [comment]
#4429
