### ISSUE TITLE
SSC Lurker bugs

### ISSUE THREAD

**Issue by MiekZer** [SunwellWoW/Sunwell-TBC-Bugtracker#4353]
closing report due to being kicked out from the discord for saying the truth. So I'm removing my tracks.
GL fixing your shit.

**Comment by Ironjudgment** [comment]
Where do you get 3 from?

**Comment by zanthed1** [comment]
Can confirm all of these issues. Third issue is a massive time waster.

**Comment by xethra89** [comment]
#3986  #3926  #4228 

These issues have been posted months ago, with the same video evidence being posted over and over. It feels like a couple things get fixed, then they move on to the next issue and never revisit the large scale posts until we post it again. /shrug

**Comment by babno** [comment]
None of those linked issues mentioned what OP posted, though some of them do still contain issues that are still present, namely that whirl only hits the tank and it should hit everyone in melee.

**Comment by xethra89** [comment]
@babno Partially. The whirl issue only has arisen in the past couple days after Whirl was fixed to affect more than just hitting the tank. The original Whirl issue was reported multiple times before it was fixed, on all 3 reports I linked.

Where you're wrong is 2 and 3. 

2 was reported here. #3986

"As you can see in this video https://www.youtube.com/watch?v=eZJNTmHA7Cg at 1:52 spawned _nagas should swim to their positions and should attack after that._ Dunno if they should be attackable or not when they are swimming, but for sure you shouldnt make any threat since they are at possitions.

They just spawn at the platforms now."

3 was reported here  #3926

"_Issues ressing people on top of the platform. They couldn't accept the ress, it just disappeared. Ressing from the water seemed to work._"

**Comment by Demolla** [comment]
Coilfang ambushers being "nontargettable" after they swim to platform, they refuse to enter platform and randomly hits peoples. Cant kill them, cant taunt them.

**Comment by Jeansapin** [comment]
Now they are running everywhere when we are fearing, when they just should not even move a toe ...
Is that serious ?

**Comment by babno** [comment]
The guardians also swim to the wrong place. They are supposed to go to 3 of the torches, they seem to go fairly randomly.
