### ISSUE TITLE
Seal of Blood/Seal of Command reopen

### ISSUE THREAD

**Issue by Nakadhino** [SunwellWoW/Sunwell-TBC-Bugtracker#4434]
Hello,

i would like to open this theme 1 more time, doing new post since its set as closed:

<--- https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4366 --->

 Seal of Blood and Seal of Command are MELEE HOLY HITS. It should ignore armor, (which it does) should scale from spell dmg, (which it doesnt) BUT not 1:1 to spell dmg. The scale should be lower, and ALSO, it should scale melee and spell crit together.

Hammer of Wrath and Judgement of Command/Blood should count melee + spell crit as well.

Since there are no Target Dummies i cant run tests, i will when they come.

But if you still have access to old HG database, there its been working how it should, ive been testing it on HG those times. And i have never played another content, so im arguing ONLY from TBC experience, and not confused by another patch.

(the link which someone posted in the previous issue isnt for tbc seals mechanisms)

as a non-direct prove:

check talents in retribution tree called -Santified Seals- its increasing melee and SPELL crit, why would it be here, for Exorcism only?! ----> http://db.hellfire-tbc.com/?spell=35397
Check T6 paladin shoulders, it has socket bonus 4 spell dmg. Of course none cares about 4 spell dmg, but its set on that item for some reason. ----> http://db.hellfire-tbc.com/?item=30997

Thanks for working : )

**Comment by akrom23** [comment]
Seal of Command scales with spell power.
Any proofs that Seal of Blood should scale with spell power?

**Comment by NeonicSupersonic** [comment]
It doesnt, but judgement does (which I assume works correctly, too lazy to check it).

https://web.archive.org/web/20080229025527/http://www.91nine.com/dps/index.php
Seal of Blood does not currently take into account spell damage. However, the effect of spell damage on Seal of Blood is minimal and should not result in significant error. Judgement of Blood uses a .45 spell damage coefficient.

**Comment by akrom23** [comment]
Judgements work fine.
Just need more info about Seal of Blood.
https://wow.gamepedia.com/index.php?title=Seal_of_Blood&oldid=1607212

> The seal only scales with weapon damage, not spell damage.

**Comment by Felynda** [comment]
I don't understand what the OP means by this crit stuff. If you have 5% melee crit and 5% spell crit your abilities should have 10% crit chance? That's not true at all.

The spell damage socket bonuses on T6 are just horrible itemization done by Blizzard. Before patch 2.3 paladins used more spelldamage, even Crusader Strike scaled with it. The changed it to it's current form but never bothered to change set gem bonus.

Also you can't really bring arguments in about how it works on previous private servers.

**Comment by Devrak** [comment]
So once more for conclusion:

Strength/Haste/Crit provide more overall dps increase when using SoB ... Even if it scaled with spell power it would be really hard to find proof because s/h/c > spower by a huge margin .... SoB cit % is based on melee crit ( Sanctified seals give spell crit so you can heal better when its needed ... paladin was intended to be the hybrid-support class )

**Comment by domforge** [comment]
@akrom23 There is definitely something off on SoB atm. its hitting for 55 extra damage on average when it should be hitting for close to 300-400 without any modifiers from judging crusader. i know someone complained about getting hit for 300 damage off a 1h but thats right, and noone should complain about a prot pally doing 3-400 dps. this is still well below what a bear tank can put out.
  
   Horde needed SoB to hit harder then rightoueness for tanking due to the lack of the  DoT that seal of vengence brought to the alliance. i haven't found the correct coefficient online but 1h prot pallies should be hitting significantly harder with SoB than they currently are. 

  Once a lot of guilds passed t5 content on retail, it was buffed even more due to horde paladins having issues with holding aggro off t5+ dps without SoV.  also the Wowpedia link was from wrath, very different.

**Comment by NeonicSupersonic** [comment]
SoB was never used for tanking in TBC(or ever), it were wastly inferior to SoR. So as SoC.
SoV (alone) was never used for tanking either, it was used to keep 5 stacks of debuff on boss while filling with as much SoR as possible.
Paladins also were rarely(if at all by a world top 100 guilds wich actually cleared content) used as main tanks.

If you want details
https://web.archive.org/web/20080803030746/http://www.failsafedesign.com/maintankadin/viewtopic.php?t=3637

JoB gains 0.45% of spd while JoR gains 0.71%
SoB swings gain close to 0 spd

**Comment by koostosh** [comment]
I see no bug here, unless you provide some sources that SoB should scale with spell power.

If you want to reopen this issue please stick to template so it would be clear what is reported as bug and what is working correctly.
