### ISSUE TITLE
[Hunter] pet randomly dismissed when dead

### ISSUE THREAD

**Issue by babno** [SunwellWoW/Sunwell-TBC-Bugtracker#4464]
Description: The pet will dismiss randomly when it is dead

How it works: https://www.twitch.tv/videos/395504375 watch at 40 seconds.

How it should work: Similar to when alive it should only be dismissed if you walk too far away from it or mount up.

**Comment by RPAncap** [comment]
Can confirm. What is big part of this issue is that when pets get dismissed it loses happines. So for instance your pet dies during boss fight and you are low on mana - so you cant instantly ress him. Your pet is now "content" (yellow happiness). 
You are waiting for mana pot cooldown. However your pet dismisses automatically. Now you drink the pot and call the pet again - but because you "dismissed him" he is now "angry" (red happiness). 

=> LOST DPS.Especially for BM hunters.
