### ISSUE TITLE
Hyjal -> Rage Winterchill (Icebolt)

### ISSUE THREAD

**Issue by jowns** [SunwellWoW/Sunwell-TBC-Bugtracker#4519]
Description:  Icebolt hits for a random amount, the forum post say 9k. Sometimes it hits over 10k. Not very fun for the clothies etc.

**Comment by username-is-not-taken** [comment]
![winterchill](https://user-images.githubusercontent.com/45629295/56166887-f932b200-5fd6-11e9-8ff3-dfb2476c17c8.png)

great fun

**Comment by NeonicSupersonic** [comment]
I think original post just took average or lowest amount of fb hit as its damage since spells (everything really) does x to y and not static amount.

More severe problem in my eyes is that he casts frostbolt mid dnd channel and castst it without swapping target to a player he casts it on as he should (use bigwigs instead of dbm lol).
