### ISSUE TITLE
[Item][Zone - Winterspring][Icecap respawntimer to way to long]

### ISSUE THREAD

**Issue by aeyers** [SunwellWoW/Sunwell-TBC-Bugtracker#4528]
Description: The Icecap respawntime in winterspring is alot longer then it should be.

**Comment by NeonicSupersonic** [comment]
Plz stop overreacting to herb spawn complains from people who are too lazy to farm those, changing them completely randomly at their whim. Keep it Blizzlike.

Icecap spawn is more or less like it should be, no change needed
Black Lotus still spawns in clusters of 3 instead of 1 node selected from 3 possible spawns, otherwise fine
Dreamfoil is how it should be
Mountain Silversage, again, spawns in clusters
Felweed has overbuffed spawns, 3x or even more spawns than it should have, and extra fast spawns on top of that
Dreamgolry is the same
Terocone is the same
Mana Thistle is the same
Nightmare Vine has 3x or less spawns than it should have, might be because it shares nodes with felweed and felweed having more spawns than it should overtakes nightmare vine nodes
Netherbloom is only(!!!) outland herb which has more or less blizzlike spawn rates

**Comment by aeyers** [comment]
Seems like you havn't been out farmnig for hours checking different respawntimers. 3 hours of farming in winterspring after icecap and got 3 full stacks, 60 icecap, winterspring should be covered with icecap, you even get alot more mountain silversage then icecap. This is with me beeing the only one the whole zone both alliance and horde. Yes, black lotus aswell as golden sansam in burning stepes are all but right. Azshara as a Zone should be a goldmine for herbers but there are no spawns or huge respawntimers.

**Comment by NeonicSupersonic** [comment]
Only 3 stacks of icecap in 3 hours? Cool story bro.
