### ISSUE TITLE
[Warlock] Demon pets scaling

### ISSUE THREAD

**Issue by Silroth** [SunwellWoW/Sunwell-TBC-Bugtracker#53]
Decription: Currently base melee damage of all demon pets (those that use melee attacks aka Voidwalker, Felhunter, Succubus and Felguard) is wrong. 

How it works: Their base melee damage seems to be around 52-54 dps? Its too low and shouldnt be the same scaling for all, different demon pets have different scaling due to their roles.

How it should work: From lowest to highest - Felhunter - Voidwalker - Succubus - Felguard.
Felguard should have 74,24179894 base dps at lvl 70 
https://cdn.discordapp.com/attachments/473950469165940769/475426227977584660/747f9f22-4dac-11e5-86dd-1287aa69d856.png
Retail TBC screenshot ^
74,24179894 DPS (BASE) + 224,7 DPS (FROM GEAR) = 298,94179894 (BASE + GEAR) + 20% (Unholy Power) + 5 % (Master Demonologist) + 5% (Soul Link) = 395,5 DPS as shown in the picture.

Base damage scales with warlock levels and judging from numbers the formula should be as following: 
Felguard: Warlock Level X 2.12117   
Succubus: Warlock Level X 2.02142
Voidwalker: Warlock Level X 1.7 or 1.8? (SEE COMMENT BELOW)
Felhunter: Warlock Level X 1.53571

Comments on wowhead/wowwiki and other warcraft related sites from TBC era mention that Voidwalker has bigger melee damage than Felhunter but lower than Succubus so we can safely assume its around Warlock Level x 1.7 or 1.8 for base damage.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Succubus_(warlock_minion)?oldid=1565074 (TBC)
http://wowwiki.wikia.com/wiki/Felhunter?oldid=1431475 (TBC)
Felguard info was shown in retail TBC screenshot.

123

**Comment by KimmoKM** [comment]
ccshiro/cc-buglist#847 for more sources

**Comment by SuddenDeath** [comment]
How it should work:

Retail examples: http://imgur.com/a/nKI97
Warmane pets with the same player health: http://imgur.com/a/HtTWe
Corecraft pets with the same player health: http://imgur.com/a/mSwL0

I changed the gear to compare mana with retail example as well, was correct on Corecraft, mostly wrong on Warmane. The only pet that seemed to be pretty much correct on Warmane was Felhunter.

Didn't compare spell damage and armor scaling but from the looks of it that seemed more accurate (except for felguards)



Another retail example of Destro warlock with no demo talents: http://imgur.com/a/86EEb
Comparisons are in that album


Corecraft no talents, no gear pets: http://imgur.com/a/BIqPX


Conclusion: Warlock all warlock pets needs their health/mana scaling fixed, possibly damage as well. I can't provide much information on how it should scale, all I know is that for every retail example that I've seen and then replicated on Corecraft, it has turned out 99% the same. They did a lot of research on it.


Retail sources:
https://www.youtube.com/watch?v=LUCv1guR-zQ
https://www.youtube.com/watch?v=czV-xTY6NV0

**Comment by doomnyx** [comment]
Some portion of information regarding felguard dmg and stats:
https://wow.gamepedia.com/index.php?title=Felguard_(warlock_minion)&oldid=1571875

**Comment by doomnyx** [comment]
Succubus: https://wow.gamepedia.com/index.php?title=Succubus_(warlock_minion)&oldid=1602317

**Comment by doomnyx** [comment]
Imp: https://wow.gamepedia.com/index.php?title=Imp&oldid=1575594

**Comment by doomnyx** [comment]
Felhunter https://wow.gamepedia.com/index.php?title=Felhunter&oldid=1556620

**Comment by Wojtyas** [comment]
Probably fixed after recent Afgann's update. Feel free to reopen or create new ticket if needed.

**Comment by Silroth** [comment]
Right now Felguard has 76.4 dps with Master Demonologist + Demonic Knowledge and naked warlock.

Succubus has 79.8 dps with Master Demonologist + Demonic Knowledge and naked warlock.

Voidwalker has 72.5 dps with Master Demonologist + Demonic Knowledge and naked warlock.

Felhunter has 72.5 dps with Master Demonologist + Demonic Knowledge and naked warlock.

So the current formula that calculates the base damage is either wrong or something else is broken. 

Should be:
Base damage scales with warlock levels and judging from numbers the formula should be as following:
Felguard: Warlock Level X 2.12117 (at 70 he should have 148.4819 base damage or 74.24095 dps)
Succubus: Warlock Level X 2.02142
Voidwalker: Warlock Level X 1.7 or 1.8? (SEE COMMENT ABOVE ABOUT THIS)
Felhunter: Warlock Level X 1.53571

**Comment by Wojtyas** [comment]
Okey, I didn't know this fix was only correlated with pet's mana :fire:

**Comment by Gelori** [comment]
Bug persists! Felguard damage is really low
@Wojtyas  @akrom23 
The source - im based not only on commentarys made above but aswell on:

- https://wow.gamepedia.com/Voidwalker_(warlock_minion)
- https://wow.gamepedia.com/index.php?title=Succubus_(warlock_minion)&oldid=1602317
- https://wow.gamepedia.com/index.php?title=Felguard_(warlock_minion)&oldid=1571875

All those sources were added on gamepedia at the end of august 2008 (You can see it in the beggining of each **DEMON RELATED Web Page** ) - it was made based on 2.4.3 version of the game.
According to this patch timelane: http://wowwiki.wikia.com/wiki/Timeline_(World_of_Warcraft)
 WOTLK prepatch was live only  in October, **so this information can be trusted, because based on 2.4.3**


**Felguard stats** [SOURCE](https://wow.gamepedia.com/index.php?title=Felguard_(warlock_minion)&oldid=1571875)
**Here I MUST MENTION THAT THEY MADE AN ERROR IN THE GUIDE - TABLE PROVIDES ROW STATS WITHOUT ANY TALENTS LIKE DEMON KNOWLEDGE AND UNHOLY POWER**
Stats are taken with a Demonology Warlock with no gear equipped, 
- Level | Strength | Agility | Stamina | Intellect | Spirit | Power | Damage | Armor
- 50     | 107         | 71      | 190       | 84         | 80     | 194    | 113-149 | 3494
- 51     | 109         | 72       | 223        | 97       | 81     | 198    | 122-160 | 3559
- 52     | 111         | 73       | 228        | 100     | 82     | 202    | 127-167 | 3624
- 53     | 113         | 75       | 233        | 102     | 84     | 206    | 127-167 | 3686
- 54      | ? | ? | ? | ? | ? | ? | ? | ?
- 55     | ? | ? | ? | ? | ? | ? | ? | ?
- 56     | 120         | 79       | 248        | 108      | 89    | 220    | 135-176 | 3878
......
70        | 153         | 108    | 351         | 196      | 122  | 323    | 176-232 | 7927




This is what is actually **live with ORC** warlock level 50 naked with
Master Demonologist and Demonic Knowledge active pet damage is after Unholy Power. 

- [My stats - stamina](https://imgur.com/xNlpfig) (we will ignore here the **LITTLE difference** of racial stats) 
- [My stats - INT](https://imgur.com/wK5QSoa)
- [Spell power = 48](https://imgur.com/5WbEbDt) with DEMONIC Knowledge talent and OVERBUFFED Stamina of pets due to recent fixes. 48 spell power increase [the attack power of demon by 27](https://imgur.com/FemRlRV)
- [FELGUARD STATS](https://imgur.com/3Iho5qZ) 

Here as you can see we have more attack power ( 221 ap) due to OVERBUFFED STAMINA ISSUE->
Demonic Knowledge = (271 sta + 136 int) x 0.12 = 48 spell power or 27 AP to demon.

**Here we come to the conclusion that Felguard has BASE 194 attack power at level 50! Coming purely from 107 strength!** 
So yes, this table has purely row values without AP gained from Warlock spell power and without any demonology talents increasing weapon damage of felguard!
Link is given, you can use it as reference for each level.
Even with this bigger **221 AP Value for FELGUARD**- according to  the table above it must be 194 
Felguard lvl 50 on server has BASE DAMAGE ([screen](https://imgur.com/3Iho5qZ) ):
91-123 ( 53,5 dps)  2,0 attack speed. This is with ORC racial + UNHOLY POWER + Master Demonologist = 5% + 20% + 5% = **30% increase of damage.**
Сompared to **source having 113-149 (65,5 dps) 2.0 attack speed** without any talents increasing pet damage.

**Now lets calculate real base damage value of FELGUARD on NIGHTBANE outside of attack power:**

- 53,5/ 1,3 ( the 30% increase) = 41,153 dps - without dmg % increases
- 221 /13,98 = 15.8 dps ADDED WITH AP     ( ~14 ap gives 1 dps)
- 41,153 - 15.8 = **25.353 dps - this is the base WEAPON DPS of Felguard WEAPON at lvl 50! Without any ap bonuses or talents.**

**RETAIL real base damage value of FELGUARD**
Formula to calculate the dps knowing the weapon speed is easy: 
- (113+149)/2 = 131 base damage each 2.0 seconds ( weapon speed) **giving us 65,5 dps**
I would like to mention again, that the description to the table has an error and i**t is WITHOUT Unholy power and Master Demonologist!**
Felguard has base 107 str = 194 attack power:
- 194/13,98 = 13,876 dps ADDED WITH AP ( ~14 ap gives 1 dps)
- 65,5 - 13,876 = **51,624 dps  - this is the base WEAPON DPS of Felguard at lvl 50! Without any ap bonuses or talents!**

**Now Lets analyze [RETAIL SCREENSHOT WITH FELGUARD](https://imgur.com/tQXoZHa):**
Felguard weapon damage = 763-819
Felguard attack power = 3146 or 224,7 dps ADDED TO BASE WEAPON DAMAGE!

- (763+819)/2 / 2.0 (attack speed) = 395,5 dps
- 395,5 dps / 1,30 ( 30% damage increase from SLink, UPower, DemoKnow) = 304.23 dps
- 304.23 - 224,7 ( added with AP) = **79,53 or ~ 79 BASE WEAPON DPS ACCORDING TO RETAIL SCREEN**

**Now lets comeback on the Felguard stats table from source:**
- Level | Strength | Agility | Stamina | Intellect | Spirit | Power | Damage | Armor
- 70        | 153         | 108    | 351         | 196      | 122  | 323    | 176-232 | 7927
- (176+232)/2 / 2.0 (attack speed) = 102 dps
-  323 ap / 13.98 = 23.10 dps from AP
- 102 - 23.10 dps = **78.89 or ~79 BASE WEAPON DPS ACCORDING TO PROVIDED SOURCE TABLE**

**So the Table provide RIGHT VALUES, but without Active talents on Felguard!!!**

**COMPARING**:
- Live **felguard lvl 50** base weapon damage dps without AP = **25.353 dps LESS THAN HALF! Comparing to retail!** 
- Retail **felguard lvl 50** base weapon damage dps without AP = **51,624 dps**
- Retail **felguard lvl 70** base weapon damage dps without AP = **79 dps**

We can assume that the BASE FELGUARD WEAPON ( without any Attack power) is calculated based on the level of master. 

@doomnyx made a little error by assuming that the BASE dps of felguard must be 74,4. According to the Reference RETAIL screenshot it is around **79,53 dps**, but the idea of scaling with level is more or less correct. 
Probably blizzard had specific table with fixed values for each felguard level - like it is with Stats added on each level.
- 79,53 dps / 70 lvls = 1,136 dps per level
- 51,624 dps / 50 lvl = 1, 032 dps per level

Since we care about **MAX 70 LEVEL,** the SCALING per level formula must be like this:
BASE FELGUARD DPS WITHOUT AP OR TALENTS:
- DPS= 1,361 X Master_Level.

The scaling for OTHER Pets is not implemented aswell!!
- [Succubus - ATTENTION! HE DOES MORE DAMAGE THAN FELGUARD - NOT CORRECT!](https://imgur.com/VZ3o4Fc)
- [ voidwalker](https://imgur.com/2B15k5e)


WHOLE Screenshots gallery from Nightbane server is **[HERE](https://imgur.com/a/NJnYgZ1)**

**Comment by wombo2u** [comment]
I agree this needs to be fixed asap, and there is tons of evidence. The problem is that this bug breaks whole t4 raiding for warlock as demo, and demo should be strong spec in t4+

**Comment by Gelori** [comment]
other issue breaking demonology rading is incorrect melee crit for warlock pets.
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1534

**Comment by Gelori** [comment]
Since you are based on HELLGround core the formula you use to calculate BASE PET DAMAGE is as follows, same as mangosone btw: 

[src/game/Pet.cpp](https://github.com/Gelori/HLG_core/blob/master/src/game/Pet.cpp)
```
`bool Pet::InitStatsForLevel(uint32 petlevel){}:
switch (getPetType())
    {
        case SUMMON_PET:
        {
            if (owner->GetTypeId() == TYPEID_PLAYER)
            {
                switch (owner->getClass())
                {
                    case CLASS_WARLOCK:
                    {

                        //the damage bonus used for pets is either fire or shadow damage, whatever is higher
                        uint32 fire  = owner->GetUInt32Value(PLAYER_FIELD_MOD_DAMAGE_DONE_POS + SPELL_SCHOOL_FIRE);
                        uint32 shadow = owner->GetUInt32Value(PLAYER_FIELD_MOD_DAMAGE_DONE_POS + SPELL_SCHOOL_SHADOW);
                        uint32 val  = (fire > shadow) ? fire : shadow;

                        SetBonusDamage(int32 (val * 0.15f));
                        //bonusAP += val * 0.57;
                        break;
                    }
                    case CLASS_MAGE:
                    {
                                                            //40% damage bonus of mage's frost damage
                        float val = owner->GetUInt32Value(PLAYER_FIELD_MOD_DAMAGE_DONE_POS + SPELL_SCHOOL_FROST) * 0.4;
                        if (val < 0)
                            val = 0;
                        SetBonusDamage(int32(val));
                        break;
                    }
                    default:
                        break;
                }
            }
            //FIXME: here is the issue for warlock pet damage, the world.pet_levelstats table doesn't have the damage range
            // but world.creature_template table does
            // 1) easy stupid fix - hard code warlock pets Entry id and use formula to calculate base weapon damage
            // Nostalrious (Lighshope) vanilla: https://github.com/brotalnia/server.git
            //uses this formula for base damage of all pets,
            // but again their is hunter pet families doing 7%, 10% more base damage...
            // Formulas reviewed by Clank <Nostalrius>, from vanilla pet tab screenshots.
            //SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float((petlevel * 1.15 * 1.05) * (float)GetAttackTime(BASE_ATTACK) / 2000));
            //SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float((petlevel * 1.45 * 1.05) * (float)GetAttackTime(BASE_ATTACK) / 2000));

            // 2) for each pet level of felguard/succubus/voidwalker/
            // Define  #felguard=17252, imp=416, felhunter=417, voidwalker=1860, succubus=1863 in creature_template table and its damage range and than
            // use it when loading petlevel stats for this level
            // in cinfo we have mindmg, maxdmg loaded from database, so basically new database entrys + this in summon pets of warlock
            // SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, cinfo->mindmg);
            // SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, cinfo->maxdmg);
            SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel - (petlevel / 4)));
            SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel + (petlevel / 4)));`
```

what does totally confrim the **dps of 25 at lvl 50** for all pets: Felguard, Voidwalker, felhunter and succubus.

**This is the proposal of my fix, both mangosOne and hellground have same issue, will work with mangosOne**:
https://github.com/Gelori/HLG_core/commit/cbcb6ffe52a52fad6ac8469d950f6961320a2fe0
