### ISSUE TITLE
[NEW!] Karazhan

### ISSUE THREAD

**Issue by Wojtyas** [SunwellWoW/Sunwell-TBC-Bugtracker#548]
Please put here every issue u encounter on Karazhan since 28.09 ;)

- [x] 1. Spectral Charger not using Charge.
Some packs that have Spectral Charger and Spectral Stallion arent linked together.
- [x] 2. Attumen the Huntsman missing his weapon and he is not using Berserker Charge once he mounts Midnight.
- [x] 3. The Big Bad Wolf timer on Howl should be every 25-35 seconds and timer on Wide Swipe should be 20-25 seconds.
- [x] 4. Curator during his enrage he should double the cast rate of his Hateful Bolt, normal cast rate of Hateful Bolt should be every 10-15 seconds, during enrage should be every 5-7 seconds.
- [x] 5. Shade of Aran Blizzard ability does not go full circle from its starting position, after spawning it deals damage for few seconds then disappears, it should move slowly until it reaches a full circle then last for 4-5 seconds more and despawn.
- [x] 7. Aran's door will sometimes bug out and be unable to be opened or will not close during the fight.
- [x] 8. Chess Event all pieces are missing their weapons.
- [x] 9. Stable Hands healing eachother, when they should be only healing horses
- [x] 10. Some Phantom guests are not properly attacking and are de-aggroing when pulled down the stairs
https://i.gyazo.com/c37972d5a6b92bf6e22d072fab2c75b2.mp4
- [x] 11. Phantom valet should say "The fates have turned against me!" upon dying
- [x] 12. Table line of sight issues in the room, can't attack the adds from the top of the table. Casuses aggro issues
- [x] 13. Baroness Dorothea Millstipe pulled from standing on top of the table, but wasn't linked to Moroes or the other adds.
She also stayed in the same position after being aggro'd and wouldn't react to Line of sight on her casts. https://imgur.com/a/K0RbK0V
- [x] 14. Phantom guests should be sitting down around the table in The Banquet Hall
- [x] 15. Pulled all the adds around Moroes without aggroing Moroes from the top of the table. Then bugged the adds due to Line of sight issues
https://imgur.com/a/BXpQM79
- [x] 16. Skeletal Waiter GUID 406102, entry 16415 pathing on tables
- [x] 17. Difficulty pulling Moroes and adds due to Line of Sight issues, even directly in front him. There are also multiple line of sight issues on the platform Moroes
starts from
- [x] 18. All of Moroes adds are missing weapons: Lady Keira, Lady Catriona, Baron Rafe
- [x] 19. Moroes is blinding while vanished. He is also Vanishing for 12 seconds, when pre-nerf values he is supposed to be vanished for 8 seconds. 
- [x] 20. When Moroes garrotes, he does not leave stealth immediately. He also is supposed to re-appear behind the player he garrotes. He is not re-applying Garrote on players if everyone has the debuff.
- [x] 21. He is also not gouging enough, and doesn't automatically go to the next player on the aggro table. 
- [x] 22. Moroes will also bug on the stairs, and will stay stuck there for a period of time.
- [x] 23. Karazhan bosses should not be dropping badges until 2.3
- [ ] 24. Karazhan bosses should be dropping 100g each, raid bosses 250g, and 800g for world bosses.
- [ ] 25. Spectral Retainers and Phantom Attendants are dropping players from their threat tables after Mind Controls.
- [ ] 26. Mind control players that no longer have valid targets run towards Skeletal Ushers and start attacking them even though they see them as friendly targets.
- [x] 27. Skeeletal Ushers are not resetting to their correct positions. They are all stacking on top of eachother, rather than standing in their original positions.
They are not attacking other players after putting their main aggro target in Ice Tomb. They are supposed to move to the next player on the aggro table.
- [x] 28. Phantom Guardsman not using the ability Summon Phantom Hound on pull
- [x] 29. Wanton Hostess is not casting the ability Banshee Wail which is on a 5 second cooldown, even when players are casting around her. She is casting a shadowbolt Banshee Wail instead
of doing the silence. Wanton Hostess is also supposed to clear all debuffs when she transforms and is not doing so.

**Comment by Recondos** [comment]
Attumen has no 2 handed sword before and after mounting

**Comment by Recondos** [comment]
Attumen no sword, before and after mounting

Stable Hands healing eachother, when they should be only healing horses

Some Phantom guests are not properly attacking and are de-aggroing when pulled down the stairs
https://i.gyazo.com/c37972d5a6b92bf6e22d072fab2c75b2.mp4

Phantom valet should say "The fates have turned against me!" upon dying 

Table line of sight issues in the room, can't attack the adds from the top of the table. Casuses aggro issues

Baroness Dorothea Millstipe pulled from standing on top of the table, but wasn't linked to Moroes or the other adds.
She also stayed in the same position after being aggro'd and wouldn't react to Line of sight on her casts. https://imgur.com/a/K0RbK0V

Phantom guests should be sitting down around the table in The Banquet Hall

Pulled all the adds around Moroes without aggroing Moroes from the top of the table. Then bugged the adds due to Line of sight issues
https://imgur.com/a/BXpQM79

Skeletal Waiter GUID 406102, entry 16415 pathing on tables

Difficulty pulling Moroes and adds due to Line of Sight issues, even directly in front him. There are also multiple line of sight issues on the platform Moroes
starts from

All of Moroes adds are missing weapons: Lady Keira, Lady Catriona, Baron Rafe

Moroes is blinding while vanished. He is also Vanishing for 12 seconds, when pre-nerf values he is supposed to be vanished for 8 seconds. When Moroes garrotes,
he does not leave stealth immediately. He also is supposed to re-appear behind the player he garrotes. He is not re-applying Garrote on players if everyone has the debuff.
He is also not gouging enough, and doesn't automatically go to the next player on the aggro table. Moroes will also bug on the stairs, and will stay stuck there for a period of time.

Karazhan bosses should not be dropping badges until 2.3

Karazhan bosses should be dropping 100g each, raid bosses 250g, and 800g for world bosses. 

Spectral Retainers and Phantom Attendants are dropping players from their threat tables after Mind Controls. 

Mind control players that no longer have valid targets run towards Skeletal Ushers and start attacking them even though they see them as friendly targets. 

Skeeletal Ushers are not resetting to their correct positions. They are all stacking on top of eachother, rather than standing in their original positions.
They are not attacking other players after putting their main aggro target in Ice Tomb. They are supposed to move to the next player on the aggro table. 

Phantom Guardsman not using the ability Summon Phantom Hound on pull

Wanton Hostess is not casting the ability Banshee Wail which is on a 5 second cooldown, even when players are casting around her. She is casting a shadowbolt Banshee Wail instead
of doing the silence. Wanton Hostess is also supposed to clear all debuffs when she transforms and is not doing so.

**Comment by Recondos** [comment]
Spectral Performers should stop attacking a target that they put to sleep, seems to be an AI issue in general.

Spectral Performers are not casting spotlight frequently, and is not buffing the performers standing in it. They are also not casting Curtain Call animation upon death

Phantom Stagehand on Death is not saying "Am I released from my duties?" or "At last, my work is done"

Trash epics are dropping way too much

Opera door should be closed until talking to Barnes

Daring on Romulo should be 50 percent pre-nerf instead of 35% for attack speed and damage dealt

Deadly swathe on Romulo seems to be hitting targets behind him. It's a frontal cleave that affects up to 3 targets. 
Julianne is casting Powerful Attraction (6 sec stun) on Romulo. 

Romulo and Julianne do not have weapons.

**Comment by Young991** [comment]
Spectral stallion packs not linking properly.
Phantom guests getting stuck in the moroes room tables.
Moroes is not aggroing when you aggro his adds.
Moroes adds get stuck on the platform.
Mobs in the maiden hallway are level 66 instead of 70
Stagehand mobs not linking properly.
Stagehands/performers are not recieveing spotlight buff.
Nightbane does not do his flight animation properly.
Lots of Line of sight problems on Nightbane's terrace.
Nightbane's phase switch flight path is wrong.
Weird Line of sight issues on The Broken Stair area.
Arcane anomaly not dropping mana regen AoE on death.
Sealed tomes give more than 1 book.
Sealed tomes not cursing when failed.
Arcane protector's spawned adds "Astral sparks" have the wrong model.
Aggro range seems to be higher than usual.
Spell Shade not aggroing during stealth.
Homunculous from "The Repository" randomly aggro when walking through the wall.
Shade of aran's door is closed.
Attack range for Netherspite is incorrect.
Chess event doors are locked.

Unable to test prince/prince trash/chess since doors are locked.

**Comment by notsofamous** [comment]
From WoW bestiary (patch 2.3)

Karazhan

    Spectral Stallion: N/A
    Spectral Charger: 3851-5446
    Spectral Stable Hand: 1821-2572
    Attumen the Huntsman: 4715-7508
    Midnight: 4248-6007
    Spectral Servant: 2416-3570
    Spectral Apprentice: 2272-3213
    Coldmist Widow: 3081-4357 (105 fire resist)
    Shadowbat: 1450-2142
    Coldmist Stalker: 757-1071 (105 fire resist)
    Greater Shadowbat: 4107-5809
    Vampiric Shadowbat: 3081-4357
    Dreadbeast: 4107-5809
    Shadowbeast: 2416-3570
    Phase Hound: 2020-2856 (105 arcane resist)
    Hyakiss the Lurker: 4780-6758
    Shadikith the Glider: 4780-6758
    Rokad the Ravager: 3585-5068
    Wanton Hostess: 3081-4357
    Concubine: 3081-4357
    Night Mistress: 2859-4039
    Phantom Guardsman: N/A
    Spectral Sentry: 3081-4357
    Phantom Hound: N/A
    Maiden of Virtue: 6157-8696
    Phantom Guest: N/A
    Phantom Valet: N/A
    Phantom Attendant: N/A
    Ghostly Steward: N/A
    Skeletal Waiter: 3850-5446
    Spectral Retainer: 4705-6654
    Spectral Servant: 2416-3570
    Moroes: 4780-6758
    Lady Keira Berrybuck: 2109-2980
    Lady Catriona Von'Indi: 109-980
    Dorothea Millstipe: N/A
    Baron Rafe Dreuger: 2109-2980
    Lord Crispin Ference: 2272-3213
    Lord Robin Daris: 2272-3213
    Spectral Chef: 4621-6535
    Ghostly Baker: N/A
    Spectral Patron: 1136-1607
    Skeletal Usher: 5334-7537
    Ghostly Philanthropist: N/A
    Spectral Performer: 4621
    Phantom Stagehand: N/A
    Dorothee: 2463-3478
    Tito: 841-1180
    Strawman: 4182-5915
    Tinhead: 4182-5915
    Roar: 2509-3549
    The Crone: 4925-6957
    The Big Bad Wolf: 4142-5857
    Julianne: 2955-4174
    Romulo: 3983-5632
    Ghastly Haunt: 8364-11829
    Trapped Soul: N/A
    Nightbane: 9028-12765
    Restless Skeleton: 1615-2499
    Arcane Watchman: 5751-8132
    Arcane Anomaly: 3291-4643 (75 arcane resist)
    Syphoner: 1406-1986
    The Curator: 5467-7722
    Astral Flare: N/A
    Arcane Protector: 7842-11090
    Astral Spark: N/A
    Mana Feeder: 757-1071
    Chaotic Sentience: 2424-3485 (75 arcane resist)
    Mana Warp: 1515-2142
    Magical Horror: 2859-4039
    Spell Shade: 3081-4357
    Shadow Pillager: 1940-2741
    Homonculus: 703-993
    Terestian Illhoof: 5050-7140
    Kil'rek: 1874-2852
    Fiendish Imp: 206-304
    Shade of Aran: 2063-2992
    Conjured Elemental: N/A
    Sorcerous Shade: N/A
    Ethereal Thief: 6273-8872
    Ethereal Spellfilcher: 5820-8222
    Netherspite: 7515-8186
    Fleshbeast: 4600-6506
    Greater Fleshbeast: 7528-10646
    Prince Malchezaar: 6638-9386
