### ISSUE TITLE
Unholy Power / Demonic Tactics - warlock talents

### ISSUE THREAD

**Issue by zapsuu** [SunwellWoW/Sunwell-TBC-Bugtracker#595]
Decription: 
Both talents don't works.

How it works: 
Unholy Power doesn't work. After choosing talents our pets doesn't make more dmg by melee attacks and by Imp's Firebolt.
Demonic Tactics  doesn't work for our pets. I checked it on my Imp, after 40 casts only 1 bolt was crit. It is like 2.5% critical chance. Base critical chance is 5%, with talent should be 10%.

How it should work: 
Unholy Power - should increased melee dmg or pets by 20% and increased Imp's Firebolt dmg by 20%. 
Demonic Tactics - should increased our and pets melee and spell critcal chance by 5%.

Source (you should point out proofs of your report, please give us some source):
It's really easy to check. After choosing Improved Imp/Succubus talent we can see that imp/succubus hits clearly harder. With Unholy Power talent there is no result.

**Comment by arcwizard** [comment]
About Demonic Tactics 40 casts are too few, for such tests you need to make 400 casts (better more) in order to have a meaningful result. But I would recommend to install addon dr. damage, he takes non-displayed statistics from the character, in this case, % of crites from talent. 
![4124](https://user-images.githubusercontent.com/43764742/46587455-ec179200-ca8c-11e8-816c-11c8a5689cca.jpg).
And if you believe more pure statistics, for example (crit. chance in dr.damage and recount is pretty close, but it differs noticeably from that written in the basic statistics of the character).:
![23123](https://user-images.githubusercontent.com/43764742/46587863-a9f14f00-ca92-11e8-9d68-7fa84a19ecac.jpg)

**Comment by Silroth** [comment]
Just tested both, they work but require relogging for the talents to take effect.

**Comment by zapsuu** [comment]
Works good
