### ISSUE TITLE
[Tooltip][Minor] Buffs show numbers unmodified by talents

### ISSUE THREAD

**Issue by nimeral** [SunwellWoW/Sunwell-TBC-Bugtracker#601]
Decription: buffs show numbers unmodified by talents

How it works: when I apply MotW, the numbers on the displayed buff don't match the numbers in the spellbook

How it should work: I should see the numbers from my spellbook, correctly modified by my talents

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/36lgKQC

P.S. I'm not 100% sure it's not "Blizzlike bug", but it would make sense to fix it. Also, sorry for using the same screenshots for reporting twice, but I think it's a different and completely unrelated issue.
P.P.S. I cleared my Cache, so it's not a client-sided issue.

**Comment by notsofamous** [comment]
It's blizzlike

**Comment by Nadiirr** [comment]
Yeah I don't think we can update spellbook tooltips, and like Notsofamous says; it's blizzlike.
I'm going to close this issue, but thank you for noticing.

**Comment by howmanylettersareyoualloweohthirtynine** [comment]
hi noob question here - I am looking into the same issue of buffs showing numbers unmodified by talent (imp motw) - except i had noticed at first in the character menu, and from this assumed that the talent itself was not functioning properly

how do we know that it is actually functioning properly? also I would welcome recommendations for trying to understand the project / contributions for someone like me with no actual experience developing anything since an HTML project in 6th grade

**Comment by howmanylettersareyoualloweohthirtynine** [comment]
noob question here - 

first - actually ;  let me start by saying TY for this post, I hadn't looked at the hoverover in the spellbook and seeing that at proper numbers at least is comforting

how do we know the talent itself is working? I have no experience developing anything since a 6th grade HTML project but any clues to try and understand would be appreciated
