### ISSUE TITLE
[Normal] Hellfire Ramparts Bosses

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#75]
1. Watchkeeper Gargolmar--
Surge ability was casted all the time for 3 Dungeon runs kicking players to INIFINITY. After a random Crash that no longer happened. DO recommend being checked.

Surge KNOCKBACK radius/Range--> https://www.youtube.com/watch?v=ZucKMUb7s_A
The knockback on the TEST realm is way too high i literary flew away fel times after the crash.

Watcher's--> Renew Mana usage incorrect. It was around 5 mana for a renew.
Healing abilities did NOT work. They started casting but the heal never healed the boss. However, RENEW did affect boss. Only great/heal abilities seem to NOT affect the boss. Same issue was observed in other instances with Heal casting mobs such as COILFANG ORACLE.

Watchers--> Kept spamming Shadow Word:Pain untill they ran out of mana.

2. Omor the Unscarred--
Incorrect cast time on "Summon Hound" ability. Issue can be related to Watchers spamming Shadow Pain. He casts Trecherous Aura and immediatelly after he does SUMMON HOUND. For the period of about 40 seconds I believe I counted about 15 or so Hounds.

Trecherous Aura-->RESISTED EVERY TIME as DOT.. I was level 70, got myself down to 60 to check if i am just too lucky. Outcome was the same, everytime the dot was about to tick --> RESISTED///RESSISTED.

Shadow Whip--> Has to be tested,as it cannot affect HTTs (Highest Threat Targets).

3. Vazruden and Nazaan--
Nazan SHOULD only come down once Vazruden is dead/at 30% or Nazan is a bit below 40% health.
He comes down anyway. First time he came after 20 seconds of fight,NOTE that Vazruden was at 80% health. Second time he came after about the same time and Vazruden was this time at 100%.

Support Links: https://www.youtube.com/watch?v=ZucKMUb7s_A
http://www.tentonhammer.com/guides/the-hellfire-ramparts-guide

**Comment by Riztazz** [comment]
Shadow Whip--> Has to be tested,as it cannot affect HTTs (Highest Threat Targets).
thats not true

**Comment by Riztazz** [comment]
Re-test please

**Comment by Silroth** [comment]
- Watchkeeper Gargolmar base damage should be 603-838.
When engaged uses Surge and Mortal Wound properly, he uses Retaliation but at very low health, comments mention he uses it at 30% or so so maybe its in 25-30% health range? Another issue is he never used Overpower (Spell ID 32154) when one of his attacks was dodged, he should use this ability on both normal and heroic version.
NOTE: His adds did not cast Shadow Word Pain on enemies at all and didnt cast Heal on Gargolmar when he requested aid/help or on themselves when they drop below 25% health.

**Comment by Riztazz** [comment]
As far as animation goes, its global and movement related and will get fixed eventually. I'll look into other issues later today

**Comment by Silroth** [comment]
[Heroic] Hellfire Ramparts Bosses

- Watchkeeper Gargolmar base damage should be 1800-2600.
Mortal Wound for 10%, Surge for ~1000 on clothies, Overpower and Retaliation same as in Normal mode.
NOTE: His Watchers prob need tuning as in heroic versions their abilities should damage and heal for alot more.
 
- Omor the Unscarred base damage should be 1939-2741. 
Shadow Bolt for 3100-4000, Bane of Treachery for 2700-3300.

- Vazruden base damage should be 3700-5200.
Stronger version of Revenge on heroic mode.

- Nazan base damage should be 3100-4200.
Should have Bellowing Roar (4 seconds AOE fear) on heroic mode, Fireball for 2400-3200, Liquid Flame leaving Blaze for 4300-5600, Cone of Fire for 4200-4800.
Hitting Nazan with DoTs or other ranged damage before he descends will cause him to use his fear while still airborne. On heroic he will descend when he is below 35% or when Vazruden is below 45%. Has decent Fire resistance probably ~105-120 (Need more info on this).

**Comment by Riztazz** [comment]
As far as demonic shield goes, that's not true
https://youtu.be/DQr09HERuFY?t=26

as you can see on the video, he casts it once and it has 10s duration and after it expires he doesnt cast it again

**Comment by Silroth** [comment]
[Normal]

- Omor the Unscarred when he summons Fiendish Hound the level up animation and sound is seen and heard (this should be hidden), Fiendish Hounds cast all of their spells however sometimes they will interrupt themselves to cast other spell, if they are channeling Drain Life they will interrupt it to cast Mana Burn or if they are trying to cast Mana Burn they will interrupt it to use Drain Life.

- Nazan should have high magic resistance, comments regarding him mention that he is resisting between 30-50% of spells from shadow, fire, frost and nature type thrown at him on both normal and heroic versions which indicate he has high resistance to every school of magic. On Excalibur server Nazan Normal has 105 resistance to all schools of magic and Nazan Heroic has 210 resistance to all schools of magic.


[Heroic]

- Watchkeepr Gargolmar melee damage needs to be increased as comments mention he hits tank for around 2k (will edit my original comment about his base damage for Heroic version), his Surge hits for around 400-500 on heroic while comments mention his Surge should hit for around 1200-1500 on cloth on heroic.

- Omor the Unscarred Currently his Shadow Bolt hits for only 2k, should use Bane of Treachery (Spell ID 37566) on heroic instead of Treachareous Aura.

- Vazruden melee damage needs to be higher.

- Nazan melee damage needs to be higher, Fireball hits for ~900 Blaze for 2500-2700 which should be much higher, has great amount of magic resistance as it should be.

**Comment by Riztazz** [comment]
https://youtu.be/LEvGcXDiIw8?t=19 shows that fireball hit for around 1000 so damage is fine while in air, he has a different fireball while on land phase that hits harder.
Same goes for blaze, it has proper damage currently ;p

**Comment by Riztazz** [comment]
should be resolved with next update, closing. if something is still funky - pm me on discord
