### ISSUE TITLE
[Normal] Hellfire Ramparts Trash

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#76]
Hollow Scryer--> Missing Fear spell. MIssing FEL infused.

Support links :http://wowwiki.wikia.com/wiki/Omor_the_Unscarred
http://www.tentonhammer.com/guides/the-hellfire-ramparts-guide
https://db.excalibur.ws/?npc=17478#abilities

Shattered Hand Warhound--> Furious Howl doesnt affect nearby ALLIES. Effect also does not LAST its spell duration (10seconds) instead it is present for roughly 3 seconds on the Target Caster.

Support Links: https://db.excalibur.ws/?npc=17280#abilities
*** http://wowwiki.wikia.com/wiki/Shattered_Hand_Warhound***

**Comment by Silroth** [comment]
Furious Howl should not last 10 seconds in that regard, the buff itself should last 10 seconds if the buffed unit isnt attacking, if the unit is attacking the buff is spent on next melee attack.

I will test Hellfire Ramparts Trash and Bosses tomorrow when i get some free time then update this post with information.

**Comment by Riztazz** [comment]
Do not test hellfire citadel yet, i'll push bunch of fixes probably tomorrow so you can test with latest updates, ill let you know in this issue

**Comment by Riztazz** [comment]
Alright, server is updated. Re-test please

**Comment by Silroth** [comment]
[Heroic] Hellfire Ramparts Trash

- Bonechewer Hungerer base damage 2464-3465.

- Bonechewer Ravener base damage should be 6800-10400. 
Should be immune to snares.

- Bleeding Hollow Archer base damage should be 2100-2750.
Multi-Shot for 1450-2000.

- Bonechewer Destroyer base damage should be 3500-4800.

- Bleeding Hollow Darkcaster base damage should be 1600-2250.
Rain of Fire for 1460, Scorch for 1600-2150.

- Shattered Hand Warhound base damage should be 2200-3100.
Stronger version of Carnivorous Bite and Furious Howl.

- Bleeding Hollow Scryer base damage should be 950-1250.
Shadow Bolt for 1750-2350.

- Bonechewer Ripper base damage should be 2464-3485.

- Bonechewer Beastmaster base damage should be 1817-2570.
Should use a stronger version of Battle Shout and be immune to all CCs and have a new ability that breaks all CCs on his Warhounds every few seconds.

- Hellfire Watcher base damage should be 2400-3400.
Stronger Shadow Word Pain, Heal and Renew.

- Fiendish Hound base damage should be 1850-2400 (QUESTIONABLE).
Mana Burn for 3000, stronger Drain Life.
NOTE: Comments mention Fiendish Hounds doing ~3000 to cloth wearers. (https://wow.gamepedia.com/index.php?title=Hellfire_Ramparts&oldid=1138436)

- Hellfire Sentry base damage should be 1850-2700.

**Comment by Riztazz** [comment]
When engaged uses all abilities properly however Shadow Bolt right now deals ~500 damage while it should do 1000 damage (2000 damage on Heroic). They are also missing their idle channeling visual as shown in the image above.

not true, checked in sniffs from those days and its around 600 on normal and 1300-1400 on heroic. That comment on wowhead is invalid, while charmed they're getting SP from charmer hence bigger damage

**Comment by Silroth** [comment]
[Normal]

- Bonechewer Ravener still missing Dual Wield ability (he isnt attacking with his offhand for 50% damage)

- Bonechewer Destroyer his Knock Away ability should be used more often.

- Shattered Hand Warhound Carnivorous Bite attacks from multiple Warhounds do not appear as separate bleed effects they just refresh the duration/add new stack of existing debuff. If 2 Warhounds are attacking same target only 1 bleed effect is present instead of 2 bleed effects, if 4-5 Warhounds are attacking same target only 1 bleed effect is present instead of 4-5 bleed effects etc

- Bonechewer Ripper currently he is vulnerable to fear and stuns, should be immune to all CCs.

- Bonechewer Beastmaster His summon Warhounds event seems to be on a long timer (over 30 seconds judging from my fight), should be on a much shorter (prob 15-20 seconds), when the Warhounds event happens they spawn and move properly however they do not have other people on their aggro list so for example if i pull Beastmaster way back they will just move to his default position and stay there, when they spawn they should have some aggro on Beastmaster's current target or party members. Currently he is vulnerable to fear, snare, root and stuns, he should be immune to all CCs except stuns.

- Hellfire Watcher rarely casts Heal and sometimes even interrupt Heal cast to cast Renew on self or other Watcher or boss. If 2 Hellfire Watchers cast Shadow Word Pain on same target the target will not receive 2 debuffs but just have its duration refreshed, should have 2 Shadow Word Pain debuffs ticking.


[Heroic]


- Hellfire Watcher same issue as on normal also on Heroic they are using weak version of Shadow World Pain that ticks for 190, Heal is weak aswell and heals for around 3k, Renew is ticking for small amounts aswell. 

- Fiendish Hound should have stronger melee damage and stronger Mana Burn and Drain Life.

**Comment by Riztazz** [comment]
As far as fiendish hound goes, not true - they do not have heroic version of their spells - checked sniffs and didnt find anything ;p

**Comment by Riztazz** [comment]
Hellfire watchers do cast heal when they're below 40% health OR boss calls for it, otherwise they cast renew and SWP and thats based on many videos

**Comment by Riztazz** [comment]
should be resolved with next update, closing. if something is still funky - pm me on discord
