### ISSUE TITLE
[Normal] Blood Furnace Trash

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#78]
Shadowmoon Technician DONT throw MINES on the ground.

Support Links: https://www.wowdb.com/npcs/17414-shadowmoon-technician#related:casts

**Comment by Silroth** [comment]
[Heroic] Blood Furnace Trash

- Laughing Skull Enforcer base damage should be 7000-9500.

- Shadowmoon Adept base damage should be 5000-7500.

- Hellfire Imp base damage should be 1650-2250.
Firebolt for 2250-3050, Fire Blast for 3200-3500.

- Laughing Skull Rogue base damage should be 2500-3500.
Same abilities as on normal only his poison damage should be higher.

- Shadowmoon Warlock base damage should be 2000-3000.
Shadow Bolt for 2250-3050, Corruption ticks for 1071, Fel Power and Curse of Tongues same as on normal.

- Laughing Skull Legionnaire base damage should be 5800-7300.

- Shadowmoon Summoner base damage should be 1750-2650.
Fireball for 2700-3000, Flamestrike damage unknown (need more info), summons Felhound Manastalker and Seductress same as on normal but with increased stats for its level.

- Seductress base damage should be 1100-1500.
Lash of Pain for 1178 and Seduction.

- Felhound Manastalker base damage should be 2100-2750.
Mana Burn and Spell Lock.

- Shadowmoon Technician base damage should be 2500-3700.
Proximity Bomb for 3500, Throw Dynamite for 860-1000.

- Nascent Fel Orc base damage should be 2423-3485.
Same abilities as on normal.

- Fel Orc Neophyte base damage should be 1334-1887.

- Hellfire Familiar base damage should be 700-850.
Fireball for 850-1150, Fire Blast for 1500-1700.

- Felguard Brute base damage should be 8800-9700.
Same abilities as on normal. Immune to all CCs except stuns and banish.

- Felguard Annihilator base damage should be 10500-12000.
Same abilities as on normal with the aggro dumping mechanic with their Charge. Immune to all CCs except stuns and banish.

- Shadowmoon Channeler base damage should be 2700-3000.
Shadow Bolt for 2400-4500, Mark of Shadow for +1500 shadow damage.

**Comment by Silroth** [comment]
[Normal]

- Laughing Skull Rogue Poisons from multiple rogues are not appearing as separate debuffs ticking but only refresh the duration of current debuff. (Same as on Heroic)

- Shadowmoon Summoner NOTE: When he summons Seductress or Felhound Manastalker the level up animation and sound is seen and heard (this should be hidden)

NOTE: In room where you should fight Broggok some mobs arent patrolling around the room they just stand in place doing nothing. 2 packs of 1 Laughing Skull Enforcer + 2 Laughing Skull Legionnaires are standing in place on top of each other instead of patrolling, they should patrol the room in a manner that first patrol is on opposite side of room compared to second patrol.

In a room after Broggok 2 Laughing Skull Rogues are missing their weapons, in the same room a group of 2 Shadowmoon Warlocks and 3 Hellfire Familiars doesnt appear to be fully linked, for example if i pull 1 Shadowmoon Warlock only him and 2 nearby Hellfire Familiars will aggro instead of whole group, if i pull the second Shadowmoon Warlock in that group only him and 1 nearby Hellfire Familiar will aggro instead of whole group. In the following room that has 1 Shadowmoon Warlock and 6 Hellfire Familiars its a similar situation, if i pull one Hellfire Familiar 2 more + Shadowmoon Warlock will aggro instead of whole group.

[Heroic]

 In a room after Broggok 2 Laughing Skull Rogues are missing.

**Comment by Riztazz** [comment]
Please test after ptr update
