### ISSUE TITLE
[Normal] Underbog Trash

### ISSUE THREAD

**Issue by Kokaina** [SunwellWoW/Sunwell-TBC-Bugtracker#81]
1. Coilfang Observer--
Throw Dynamite incorrect damage (70-90). Also Magma Splash area effect from it is applied TO caster mob instead of PLAYER.

Support Link: https://db.excalibur.ws/?npc=17938#abilities

2. Coilfang Defender--
SPell reflect shield seems to be very spontaneous.

10 Times the shield was tested for enemy attacks being reflected. It seemed that up to 3-4 times he reflected the VERY first spell casted after he casts his shield. The rest times the shield SELECTIVELY reflected spells.

3. Coilfang Soothslayer--
Mind control doesnt work.

Support LInk :: https://db.excalibur.ws/?npc=17960#abilities

**Comment by Silroth** [comment]
- Bog Giant is not using his Growth ability properly.

- Murkblood Tribesman missing Dual Wield passive ability (hitting with offhand for 50%)

- Murkblood Oracle not casting Amplify Damage (Note sure if they are supposed to cast it on Normal).

- Underbog Lord these mobs are missing from dungeon and instead Bog Giants are patrolling in their place.

**Comment by Riztazz** [comment]
Resolved. Please re-test after realm update

**Comment by Silroth** [comment]
- Earthbinder Rayge missing dialogue text and whisper event.

When player come in certain range near him he should do the following:

Earthbinder Rayge whispers: Psst! Hey, <class>, over here to your left. Come here!
"Thank goodness for you! Claw and I were investigating this place when we were jumped by Swamplord Musel'ek. He can control animals, even druids!
Unfortunately, Claw was caught in bear form at the time, and is now the swamplord's pet. I don't dare change into cat form or he'll get me too!
I'm afraid you'll have to fight Claw in order to save him. Just keep heading west; you can't miss him."

- Windcaller Claw missing dialogue text and perform EmoteTalkExclamation, dialogue text should be:

"How embarrassing to be taken as a pet by a hunter!

I owe you my life, but please, trouble yourself no longer with my welfare. Now that you've freed me from Musel'ek, I'll be able to find my way out. Maybe I'll pick up Rayge along the way."
